### ISSUE TITLE
Sometimes themes (and userstyles?) don't load

### ISSUE THREAD

**Issue by Touchcreator** [ScratchAddons/ScratchAddons#931] opened 2020-12-03 17:49 UTC
**Describe the bug**

I set ark mode and sometimes when I refresh its not in dark mode

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

**Additional context**

**Comment by GrahamSH-LLK** [comment] 2020-12-03 17:51
Yeah, I've noticed this! It's a bug with themes/userstyles.

**Comment by WorldLanguages** [comment] 2020-12-03 17:52
Ugh, here we go again... Bug with no repro...

**Comment by WorldLanguages** [comment] 2020-12-03 19:12
I'll suppose this is a duplicate of #932

**Closed** 2020-12-03 19:24 UTC
Labels: bug, prio-2
