### ISSUE TITLE
"Browse followers button in studios" only shows 24 followers with Add To Studio Menu in "Infinite Scrolling" is enabled

### ISSUE THREAD

**Issue by FluddTheWadder8** [ScratchAddons/ScratchAddons#3475] opened 2021-09-12 15:40 UTC
### Description

When "Add To Studio Menu" in the addon "Infinite Scrolling" is enabled, "Browse followers button in studios" will only show 24 followers.

### Repoduction steps

1. Enable "Infinite Scrolling" and its "Add to Studio Menu" option
2. Enable "Browse followers button in studios"
3. Go to a studio's Curators tab and click on "Browse followers"

### Expected behaviour

There should be an infinite scroll of your followers

### Actual behaviour

Only 24 followers are shown, with no scrollbar.

### Screenshots
![Screenshot of bug](https://u.cubeupload.com/beekay29/Screenshot2021091210.png)

### Environment

- Browser: Chrome 95.0.4631.0
- Scratch Addons version: 1.19.1
- Operating system: Chrome OS 14204.0.0

### Additional context

I'm using the development build of Chrome OS

**Comment by apple502j** [comment] 2021-09-12 15:55
Duplicate of #3238

**Closed by apple502j** 2021-09-12 15:55 UTC
Labels: type: bug, status: duplicate
