### ISSUE TITLE
Bring back camera button

### ISSUE THREAD

**Issue by WindowsUserInTheHouse** [ScratchAddons/ScratchAddons#5177] opened 2022-10-09 22:41 UTC
### Why this would be helpful/solve a problem

There _used to_ be a way to take photos from directly in Scratch. The ST may have removed this or something.

### What this addon does

The addon would re-add the camera button to the sprite/costume/backdrop tools, making it so you don't have to import photos.

**Comment by WorldLanguages** [comment] 2022-10-09 23:47
Duplicate of #4069

**Closed by WorldLanguages** 2022-10-09 23:47 UTC
Labels: type: enhancement, new addon, scope: addon
