### ISSUE TITLE
Scratch 2.0 → 3.0: /login_retry/ page is not redesigned.

### ISSUE THREAD

**Issue by Slymeball** [ScratchAddons/ScratchAddons#774] opened 2020-11-17 22:31 UTC
The scratch.mit.edu page /login/ (or /login_retry/) is not redesigned into a 3.0 page using the Scratch 2.0 → 3.0 plugin.

**To Reproduce**

1. Go to '[https://scratch.mit.edu/login](https://scratch.mit.edu/login)' or '[https://scratch.mit.edu/login_retry](https://scratch.mit.edu/login_retry)'

**Expected behavior**

The website should have an updated design with the new navbar and redesigned text fields and buttons.

**Screenshots**

![image](https://user-images.githubusercontent.com/51765267/99458057-89db1d80-28f1-11eb-8d70-33638de4c03e.png)

**Device (please complete the following information):**

- OS: Windows 10 Home x64 (Version 2004)
- Browser: Brave (Chromium-Based)
- Version:
    - Brave: 1.16.76
    - Chromium: 86.0.4240.198

**Additional context**

I guess you guys forgot about the page... Take your time on this one, it isn't as important.

**Comment by TheColaber** [comment] 2020-11-17 22:33
I think the problem is that the elements have different class names.

**Comment by GrahamSH-LLK** [comment] 2020-11-17 22:49
No, I think he's correct. I bet that it doesn't target this page.

**Comment by TheColaber** [comment] 2020-11-17 22:53
Oh, I see I thought there was a global inject that had the URL "https://scratch.mit.edu/*"

**Comment by GrahamSH-LLK** [comment] 2020-11-17 22:57
This is resolved in my above PR.

**Comment by YOYITsM3M8** [comment] 2020-11-18 15:18
hey @mxmou might also wanna redesign https://scratch.mit.edu/ip_ban_appeal/* because that isnt redesigned. (i only know this because i was ip banned for no reason)

**Comment by TheColaber** [comment] 2020-11-18 15:28
What does it look like?

**Comment by YOYITsM3M8** [comment] 2020-11-18 15:33
> What does it look like?

![image](https://user-images.githubusercontent.com/49005044/99551080-7085b000-2989-11eb-87ef-d882c772545c.png)

**Comment by mxmou** [comment] 2020-11-18 15:36
> hey @mxmou might also wanna redesign `https://scratch.mit.edu/ip_ban_appeal/*` because that isnt redesigned. (i only know this because i was ip banned for no reason)

All it contains is some text, so simply adding it to the list of 2.0-styled pages would work.

**Closed** 2020-11-20 18:14 UTC
Labels: bug

**Comment by Kevinipad** [comment] 2022-10-14 09:58
On Tue, Oct 11, 2022 at 2:39 PM Appeals <[appeals@scratch.mit.edu](mailto:appeals@scratch.mit.edu)> wrote:


Thank you for contacting us about your account.

The Scratch website is an educational resource for children and their parents, teachers and their students, and people learning about programming skills. These users deserve a welcoming, supportive, and creative community space, so when we see users who have been blocked and notified so many times, we believe they will not be able to follow our Community Guidelines in the future.

I am seeing you have continued to violate our Community Guidelines on your alternate accounts. Based on your past history on the Scratch website, your account will not be unblocked. Do not use or make any other Scratch accounts or send in any further appeals. You are welcome to use the offline editor to make projects: https://scratch.mit.edu/download

Alex
Scratch Team
