### ISSUE TITLE
Pop-up player window

### ISSUE THREAD

**Issue by ilbailba** [ScratchAddons/ScratchAddons#4232] opened 2022-02-07 15:16 UTC
### Is your request related to a problem? Please describe.

No.

### Describe the solution you'd like

A plugin that can make the project player a popup with the push of a button. The pop-up window can be made full screen, minimized and enlarged at any time. this will not only provide more space while writing code in the project, but also the window can be seen and resized wherever desired. I think it will also be useful for those who have more than one monitor. It will be controlled by a button placed on the edge of the project player. a button just like controller binding plugin. I thought this plugin would only work in the editor, but it might work on project pages as well. If the project player is made a popup, a button can be placed where the project player normally is, to make it a single window again.

### Describe alternatives you've considered

button to open popup => this button will be anywhere on the edge of the player. (top right, top left, bottom right, bottom left)

close popup button => there will be a much smaller button than the project player where the project player used to be.

(I do not write the window settings that exist in the operating system itself. (such as maximizing, minimizing, making full screen))

if the project is downloaded below it may have play, stop (and pause if using the pause plugin) buttons like a music player.

Also, if the popup is turned off, the player will automatically revert to its original state.

### Additional context

I'm not at the computer right now. if i get to the computer i will make illustrative images and post it as a comment.

**Comment by mxmou** [comment] 2022-02-07 15:19
Duplicate of #1993

**Closed by mxmou** 2022-02-07 15:19 UTC
Labels: type: enhancement, new addon, scope: addon
