### ISSUE TITLE
Clear Console automatically 

### ISSUE THREAD

**Issue by Genius398** [ScratchAddons/ScratchAddons#2810] opened 2021-06-17 04:59 UTC
### Is your request related to a problem? Please describe.
We can make a block to clear the console. More, we can set it to clear at pause, start or stop

**Comment by apple502j** [comment] 2021-06-17 05:44
Duplicate of #2795

**Comment by RedGuy12** [comment] 2021-06-17 14:49
Naw, that issue is about using a block to clear it. This is automatically clearing it on the green flag.

**Comment by Shluffy** [comment] 2021-06-17 21:31
apple is kinda right. it kindas a little and then a setting for more

**Comment by apple502j** [comment] 2021-06-17 23:09
Duplicate of #2798

**Closed by apple502j** 2021-06-17 23:09 UTC
Labels: new addon, scope: addon, type: enhancement
