### ISSUE TITLE
Messages hidden by filter box

### ISSUE THREAD

**Issue by sfederici** [ScratchAddons/ScratchAddons#2628] opened 2021-05-27 09:53 UTC
### Description

In the Scratch messaging filter, the filter selector on top covers new messages

### Reproduction steps

1.  enable the Scratch messaging filter
2. do an activity that will be notified by a Scratch message
3. go to the message page

### Expected behaviour

All messages are visible below the filter selector box

### Actual behaviour

A few new messages are hidden and are not visible. They get visible only if you disable the messaging filter addon. After a while they get visible even if you reenable the filter.

### Screenshots

Filter addon enabled:
<img width="1344" alt="Schermata 2021-05-27 alle 08 58 07" src="https://user-images.githubusercontent.com/2651868/119805482-91ebc980-bee1-11eb-8ad6-a0b8032d8f2f.png">

Filter addon disabled:
<img width="1344" alt="Schermata 2021-05-27 alle 08 57 24" src="https://user-images.githubusercontent.com/2651868/119805496-94e6ba00-bee1-11eb-86c4-aeee2ef0e5d5.png">

### Environment

- Browser: Chrome 90
- Scratch Addons version: 1.15.0
- Operating system: macOS 10.15.7

**Comment by apple502j** [comment] 2021-05-27 10:00
Duplicate of #2614

**Closed by apple502j** 2021-05-27 10:00 UTC
Labels: status: needs triage, type: bug
