### ISSUE TITLE
Add a way to see what OS someone's using

### ISSUE THREAD

**Issue by WindowsUserInTheHouse** [ScratchAddons/ScratchAddons#5244] opened 2022-10-23 20:12 UTC
### Why this would be helpful/solve a problem

This addon would be helpful because sometimes people may want to see the OS someone's using.

### What this addon does

This addon would use scratchstats to display the possible OS someone is using, after either their join date, or after their country.

**Comment by WorldLanguages** [comment] 2022-10-23 22:43
Duplicate of #5167

**Closed by WorldLanguages** 2022-10-23 22:43 UTC
Labels: type: enhancement, new addon, scope: addon
