### ISSUE TITLE
Allow renaming variables in variable manager

### ISSUE THREAD

**Issue by superscratch444tre** [ScratchAddons/ScratchAddons#1842] opened 2021-03-13 10:58 UTC
**Is your feature request related to a problem? Please describe.**

I usually want to easly **rename** my variables from the variable manager tab.

**Describe the solution you'd like**

In the variable manager, you can easly modify the value of a variable. It would be great if it was also possible to do this to **variables' and lists' names**!

**Describe alternatives you've considered**

As an alternative solution, a "**rename variable/list**" (or just "**rename**") option when **right clicking** the name of a variable/list, that will open scratch's **rename variable popup** (or **a browser message**, if you cannot do that).

**Additional context**

None yet.

**Comment by jeffalo** [comment] 2021-03-13 11:27
i am planning on addding a right click context menu for the variable manger. renaming would be in it.

**Comment by TheColaber** [comment] 2021-03-13 13:11
Duplicate of #1777

**Closed by TheColaber** 2021-03-13 13:11 UTC
Labels: priority: 3, type: enhancement
