### ISSUE TITLE
Automaticly make @username be linked to a user profile in the forums

### ISSUE THREAD

**Issue by leahcimto** [ScratchAddons/ScratchAddons#4880] opened 2022-07-22 15:56 UTC
### Is your request related to a problem? Please describe.

Slightly, when users tag people in the forums using [at-symbol]username, it doesn't make a link to their profile. This can be confusing because the behavior is different on the main site.

### Describe the solution you'd like

I think that in the forums whenever you type an [at-symbol] followed by a username, it should convert it into a link.
### Describe alternatives you've considered

I don't think there could be many alternatives to this, besides having users be linked when the post is displayed instead of it being put right into the BBCode.
### Additional context
None

**Comment by Samq64** [comment] 2022-07-22 19:13
Duplicate of #1445

**Comment by Weredime** [comment] 2022-07-22 19:19
Duplicate of #1445

**Closed** 2022-07-22 19:19 UTC
Labels: status: duplicate, type: enhancement
