### ISSUE TITLE
Searchable My Stuff page

### ISSUE THREAD

**Issue by BarionLP** [ScratchAddons/ScratchAddons#2063] opened 2021-04-03 12:04 UTC
**Describe the new addon**
The project page should be searchable.
Make sure this is compatible with the 2.0 to 3.0 addon

**Comment by mxmou** [comment] 2021-04-03 12:17
Do you mean [this page](https://scratch.mit.edu/users/griffpatch/projects/)?

**Comment by BarionLP** [comment] 2021-04-03 15:50
yes and the [personal ](https://scratch.mit.edu/mystuff/)

**Comment by mxmou** [comment] 2021-04-03 15:59
I changed the title to be more clear.

**Comment by RedGuy12** [comment] 2021-04-03 19:13
This is a duplicate.
________________________________

**Comment by mxmou** [comment] 2021-04-03 19:23
@RedGuy12 Looks like you're right. Closing as duplicate of #1573

**Closed by mxmou** 2021-04-03 19:23 UTC
Labels: new addon, scope: addon, type: enhancement
