### ISSUE TITLE
Griffpatch Search Bar and Custom Block Colors

### ISSUE THREAD

**Issue by RedGuy12** [ScratchAddons/ScratchAddons#720] opened 2020-11-11 04:01 UTC
**Describe the bug**

When I change the block colors for variable, events, and custom, the Griffpatch Search Bar doesn't update with the new colors.

**To Reproduce**

Change the colors, then click on Griffpatch's search bar.

**Expected behavior**

I think it would be nice for the colors to update.

**Comment by JeffaloBob** [comment] 2020-11-11 07:15
#669

**Comment by Hans5958** [comment] 2020-11-11 09:34
Duplicate of #666

**Closed by Hans5958** 2020-11-11 09:34 UTC
Labels: bug
