### ISSUE TITLE
Add option to switch to a 2.0-like theme

### ISSUE THREAD

**Issue by Mwalters75** [ScratchAddons/ScratchAddons#4066] opened 2022-01-16 05:02 UTC
### Is your request related to a problem? Please describe.

No, it's not related to a problem, just requesting a new addon for Scratch Addons
### Describe the solution you'd like

For people who doesn't like the Scratch 3.0 theme to have the option to switch to the 2.0 theme
### Describe alternatives you've considered

I tried toggling "Display stage on right side," "Customizable block colours," and "Customizable block shape"
### Additional context

Not any, at the moment.

**Comment by Mbrick2** [comment] 2022-01-16 16:06
requested somewhere....dont know where

**Comment by apple502j** [comment] 2022-01-17 15:23
Duplicate of #985

**Closed by apple502j** 2022-01-17 15:23 UTC
Labels: type: enhancement, new addon, scope: addon
