### ISSUE TITLE
Customizable Front Page

### ISSUE THREAD

**Issue by jaden-lol** [ScratchAddons/ScratchAddons#7694] opened 2024-08-01 03:32 UTC
### Why this would be helpful

To make the front page better or making fun of Scratch

### How this addon works

It Will add, rename, or remove something in the front page, for example, add "Projects Shared By (Scratcher), rename "Featured Projects" to "Dumpster Fire", and remove Scratch News because Scratch News sometimes useless

### Possible alternatives

Customizable Navigation Bar(?)

### Additional context

I don't know

**Comment by WorldLanguages** [comment] 2024-08-02 19:10
Duplicate of #1758

**Closed by WorldLanguages** 2024-08-02 19:10 UTC
Labels: type: enhancement, new addon, scope: addon
