### ISSUE TITLE
Add label to exact forum post count

### ISSUE THREAD

**Issue by The64thCucumber** [ScratchAddons/ScratchAddons#789] opened 2020-11-20 05:03 UTC
I have no clue if this counts as a "feature" or if I'm doing this right, or if this is a duplicate, but as of now when the "Show exact count" addon is turned on, it just shows the number, which looks very weird and out of place. Simply concatenating X with "posts" so it reads "X posts" will make it a little less jarring.

**Comment by The64thCucumber** [comment] 2020-11-20 05:07
Ah, I see. So the default text in the box wasn't some guidelines to Ctrl+A and delete, it was a form to fill out. Should I do that for something that took 2 sentences to describe?

**Comment by pufferfish101007** [comment] 2020-11-20 07:29
Duplicate of another issue somewhere, also has been fixed in a pr somewhere.

**Comment by mxmou** [comment] 2020-11-20 08:38
> Duplicate of another issue somewhere, also has been fixed in a pr somewhere.

Duplicate of #731 
Yes, it's already fixed.

**Closed by mxmou** 2020-11-20 08:38 UTC
Labels: enhancement
