### ISSUE TITLE
Variable display doesn't change color

### ISSUE THREAD

**Issue by Luke-Software1024** [ScratchAddons/ScratchAddons#6283] opened 2023-06-27 15:51 UTC
### Description

I don't like the color of variables so I turned on "Customizable block colors", but the variable display doesn't change color.

### Steps to reproduce

1. Enable "Customizable block colors".
2. Change the color of "Variables".
3. Show a variable monitor.

### Demonstration(s) and additional context

Variable monitors look like this:
![Screenshot 2023-06-27 084759](https://github.com/ScratchAddons/ScratchAddons/assets/130189698/579f2ff8-1ece-48f8-aeff-7654f199f601)
but I set them to look like this:
![Screenshot 2023-06-27 084856](https://github.com/ScratchAddons/ScratchAddons/assets/130189698/520e90a3-e495-45a0-8434-076fbdb07939)

### Environment

Browser: 
Scratch Addons version: 
Operating system:

**Comment by mxmou** [comment] 2023-06-27 16:05
Duplicate of #4033

**Closed by mxmou** 2023-06-27 16:05 UTC
Labels: type: bug, status: needs triage
