### ISSUE TITLE
Infinite Scrolling not available in all pages

### ISSUE THREAD

**Issue by JoanRiosiPla** [ScratchAddons/ScratchAddons#6419] opened 2023-07-20 16:49 UTC
### Description

The [Infinite Scrolling](https://github.com/ScratchAddons/ScratchAddons/tree/master/addons/infinite-scroll) add-on doesn't cover all cases where a "Load More" button appears.

### Steps to reproduce

1. Enable Infinite Scrolling
2. Go to the scratch main page
3. Scroll in the "What's Happening?" section (as an example)

### List of cases where it doesn't work:
- [What's Happening](https://scratch.mit.edu/)
- [Explore](https://scratch.mit.edu/explore)
- [MyStuff](https://scratch.mit.edu/mystuff/)

### Proposed Solution:
I don't know how it's implemented, but I would make it so that the extension always tries to click a "load more" button if it's near the viewport.

I made a Chrome extension a while back that does just this (very inefficient but it works):
[https://github.com/JoanRiosiPla/ScratchAutoLoadMore-Chrome-Extension/tree/main](https://github.com/JoanRiosiPla/ScratchAutoLoadMore-Chrome-Extension/tree/main)

### Environment

Browser: Chrome
Scratch Addons version: 1.34.0
Operating system: Windows 11

**Comment by mxmou** [comment] 2023-07-20 17:48
Duplicate of #3071

**Closed by mxmou** 2023-07-20 17:48 UTC
Labels: type: enhancement, scope: addon
