### ISSUE TITLE
Make 2.0 → 3.0 Comment Buttons Bigger

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#1309] opened 2021-01-13 02:03 UTC
**Buttons are too small**
The Post button under redesigned comments need more padding and I think the cancel button needs more padding and a grey colour instead of the white and blue border.

Thanks,

**Comment by mxmou** [comment] 2021-01-13 08:27
The Scratch 2.0 → 3.0 addon doesn't currently change the size of most elements. I might consider changing the appearance of buttons to better match the Scratch 3.0 design, but this isn't a bug.

**Comment by mxmou** [comment] 2021-04-24 09:15
Duplicate of #642

**Closed by mxmou** 2021-04-24 09:15 UTC
Labels: scope: addon, type: enhancement
