### ISSUE TITLE
Custom editor theme

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#1656] opened 2021-02-24 04:22 UTC
**Describe the new addon**

This would allow you to change the color scheme of the editor, similar to how the 2.0 > 3.0 addon works. (This could also simply be a checkbox added to the 2.0 > 3.0 addon titled "Apply to editor" for better consistency.)
The primary color would also affect the background color, which is a less saturated version of the default primary blue.

This could also be lumped under what is currently the "Editor dark mode" addon. This might make it easier to work around conflicts with dark themes, but it would remove the ability to have the same colors as the 2.0 > 3.0 addon.

**Comment by mxmou** [comment] 2021-02-24 07:19
Duplicate of #657

I'm working on this, it will be part of dark mode.

**Closed by mxmou** 2021-02-24 07:19 UTC
Labels: new addon, scope: addon, type: enhancement
