### ISSUE TITLE
Scratch Addons Broken on Normal Scratch

### ISSUE THREAD

**Issue by hammouda101010** [ScratchAddons/ScratchAddons#7841] opened 2024-10-03 16:10 UTC
### Description

Addon UI is Broken.

### Steps to reproduce

1. Go to Scratch Website
2. Open Editor.
3. Use Addons That Change or Add UI

### Demonstration(s) and additional context

![Screenshot 2024-10-03 120900](https://github.com/user-attachments/assets/3aae0410-d89b-4117-b48e-6f71d38a64ed)
UI is broken

### Environment

Browser: Edge 129.0.2792.65 
Scratch Addons version: 1.39.1
Operating system: Windows 11

**Comment by mxmou** [comment] 2024-10-03 16:14
Duplicate of #7805

**Comment by hammouda101010** [comment] 2024-10-03 16:31
> Duplicate of #7805

are you going to fix it or not?

**Comment by mybearworld** [comment] 2024-10-03 17:16
> > Duplicate of #7805
> 
> are you going to fix it or not?

It has been fixed at #7809

**Comment by WorldLanguages** [comment] 2024-10-03 19:15
> Duplicate of #7805

Did you forget to close this issue?

**Closed** 2024-10-03 19:15 UTC
Labels: type: bug, status: duplicate, scope: addon, scope: upstream

**Comment by hammouda101010** [comment] 2024-10-03 20:06
so why is it still broken for me?

**Comment by mybearworld** [comment] 2024-10-03 20:17
> so why is it still broken for me?

There has not been an update pushed out yet.

**Comment by CST1229** [comment] 2024-10-03 20:17
> so why is it still broken for me?

Because the next version hasn't released yet.
