### ISSUE TITLE
Feature Request: Pin Comments

### ISSUE THREAD

**Issue by xItzDiamondx** [ScratchAddons/ScratchAddons#2534] opened 2021-05-19 15:18 UTC
### Is your request related to a problem? Please describe.

Sometimes when I'm on Scratch, I see people saying "If any comments go above this, please repost."
### Describe the solution you'd like
I'd like it if you could pin comments kind of like on YouTube. If you own that project or studio or if it's your profile, you should be able to pin a comment.

### Describe alternatives you've considered
I mean, the reposting thing works, but it means you need lots of people coming to your profile to fix it.

### Additional context
None

**Comment by RedGuy12** [comment] 2021-05-19 15:20
Duplicate of #1643

**Closed by RedGuy12** 2021-05-19 15:20 UTC
Labels: status: needs triage, type: enhancement

**Comment by return-misaPuding** [comment] 2021-05-19 15:35
Duplicate of https://ocular.jeffalo.net/topic/513823 xDDD (I said this also
in the issue which this is a duplicate of (pointed out by RedGuy12)

Dne st 19. 5. 2021 17:18 uživatel Zack ***@***.***> napsal:
