### ISSUE TITLE
Custom extension webpage CSS

### ISSUE THREAD

**Issue by Secret-chest** [ScratchAddons/ScratchAddons#7379] opened 2024-04-24 05:01 UTC
There should be a facility to add custom CSS that will be used in the extension's webpages. It should be marked as experimental and not guaranteed to be stable.

In case someone breaks it, there should be a context menu item to delete this CSS.

**Comment by mxmou** [comment] 2024-04-24 07:50
Duplicate of #5469

**Closed** 2024-04-24 07:50 UTC
