### ISSUE TITLE
Notification System

### ISSUE THREAD

**Issue by Mast3rGenius** [ScratchAddons/ScratchAddons#2114] opened 2021-04-09 01:24 UTC
**Describe the bug**

If you get temporarily muted from commenting for saying something that is banned by the filter, when you get the notification that you've been unmuted, the notification will show on Scratch Addons as a number but won't actually load the message.

**To Reproduce**

1. Go to anywhere you can comment
2. Type something that gets you temporarily muted
3. Wait until the mute times out and you receive the notification

**Expected behavior**

The message either loads properly or the notification number doesn't go up.

**Device (please complete the following information):**

- OS: Windows
- Browser: Brave
- Version: Latest

**Comment by TheColaber** [comment] 2021-04-09 01:28
Duplicate of #1710

**Closed by TheColaber** 2021-04-09 01:28 UTC
Labels: status: needs triage, type: bug
