### ISSUE TITLE
apply scratch 2.0 -> 3.0 colors to the "remix tree" button

### ISSUE THREAD

**Issue by FunctionalMetatable** [ScratchAddons/ScratchAddons#2053] opened 2021-04-02 15:58 UTC
**Is your feature request related to a problem? Please describe.**

if i change the primary colors of the scratch 2.0 -> 3.0 addon, the remix tree button doesnt change colors but the other buttons do

**Describe the solution you'd like**

the buttons below the project are the same color

**Describe alternatives you've considered**

none

**Additional context**

![image](https://user-images.githubusercontent.com/67440879/113432038-99589000-93d4-11eb-84d1-06e373828c41.png)

**Comment by FunctionalMetatable** [comment] 2021-04-02 15:59
oops this is accidentally an feature request - please change it to a bug

**Comment by TheColaber** [comment] 2021-04-02 16:00
cc @WorldLanguages i think this is part of the reason why we wanted to remove the setting to change the color in the remix tree adoon.

**Comment by WorldLanguages** [comment] 2021-04-02 16:32
I'm not sure why remix tree button has a color setting, and I'm not sure either on what we should do about it :P

**Comment by mxmou** [comment] 2021-04-02 16:44
Duplicate of #1262

**Closed by mxmou** 2021-04-02 16:44 UTC
Labels: scope: addon, type: enhancement
