### ISSUE TITLE
Settings page glitches when resizing.

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#474] opened 2020-10-12 21:03 UTC
**Describe the bug**

The settings page glitches as shown by the screenshot.
![image](https://user-images.githubusercontent.com/61319150/95790093-5975e300-0ca4-11eb-9543-269770d6d0a0.png)

**To Reproduce**

Resize the settings and then scroll to the side to the right.

**Expected behavior**

It works
**Screenshots**

![image](https://user-images.githubusercontent.com/61319150/95790123-67c3ff00-0ca4-11eb-9413-fcc79afd958e.png)

**Device (please complete the following information):**

- OS: Chrome OS
- Browser: Chrome
- Version: Latest

**Additional context**

![image](https://user-images.githubusercontent.com/61319150/95790085-567af280-0ca4-11eb-98db-3c0dcf795fd4.png)

**Comment by GrahamSH-LLK** [comment] 2020-10-12 21:09
Duplicate of #189

**Comment by GrahamSH-LLK** [comment] 2020-10-12 21:10
Also, why did you use the screenshot 3 times? 😜

**Comment by Explosion-Scratch** [comment] 2020-10-12 21:14
XD sry

**Closed** 2020-10-12 21:14 UTC
Labels: bug
