### ISSUE TITLE
Custom Navbar Items only apply to root page (scratch.mit.edu)

### ISSUE THREAD

**Issue by jdev082** [ScratchAddons/ScratchAddons#4300] opened 2022-02-22 03:10 UTC
### Description
Enabled the custom navbar item feature, set some custom options, and it only applies to scratch.mit.edu and not pages like scratch.mit.edu/disuss/31
### Reproduction steps
![image](https://user-images.githubusercontent.com/92550746/155055838-3d905697-38bf-434d-890c-e27fdcdf7919.png)
![image](https://user-images.githubusercontent.com/92550746/155055876-00875cc1-f3cf-4ca3-8547-6de7a9531747.png)
![image](https://user-images.githubusercontent.com/92550746/155055908-fd69a539-cbe3-405e-97bd-c88b48d417fb.png)
Then go to scratch.mit.edu to make sure it applied
then go to a subpage, like /discuss/31.
### Expected behavior
The changes to the navbar be applied to all subpages
### Actual behavior
Only works on root page
### Environment
Operating System: Microsoft(tm) Windows 11 Professional, Insider Preview 22557.1
Web Browser: Mozilla Firefox 97.0.1, (Also occurs on Chrome 98)
Version: 1.24.3

**Comment by Chiroyce1** [comment] 2022-02-22 04:00
Works for me - SA v1.24.3, Firefox.

<img width="940" alt="image" src="https://user-images.githubusercontent.com/97374054/155060743-b53d13d9-92f6-4183-a82b-db2de77ffd72.png">

**Comment by Mbrick2** [comment] 2022-02-23 09:12
Can't reproduce 
![image](https://user-images.githubusercontent.com/90691415/155289755-57c0fabc-8dd0-42e2-9148-019e4a61d9fc.png)
OS: MacOS Big Sur
Browser: Firefox
SA: v1.24.3 stable

**Comment by JaydenDev** [comment] 2022-02-24 03:36
I will take further investigation into this bug I have reported. And double check, it might be a misunderstanding.

**Comment by JaydenDev** [comment] 2022-02-24 03:37
After further testing, it appears that this bug was simply a misunderstanding of mine. I will close the issue report.

**Closed by JaydenDev** 2022-02-24 03:37 UTC
Labels: type: bug, scope: addon

**Comment by Samq64** [comment] 2022-02-24 14:32
> After further testing, it appears that this bug was simply a misunderstanding of mine. I will close the issue report.

#4315?
