### ISSUE TITLE
Delete Extension

### ISSUE THREAD

**Issue by PlayfulMathematician** [ScratchAddons/ScratchAddons#6176] opened 2023-06-09 18:07 UTC
### Why this would be helpful

Sometimes people accidently add a extension to there code. But they want to delete that is my idea.

### How this addon works

This adds a delete button to each extension.

**Comment by Samq64** [comment] 2023-06-09 18:11
Duplicate of #5478.

**Closed by Samq64** 2023-06-09 18:11 UTC
Labels: type: enhancement, new addon, scope: addon
