### ISSUE TITLE
LET ME SWITCH MY LANGUAGEEE

### ISSUE THREAD

**Issue by LankyBox01** [ScratchAddons/ScratchAddons#3400] opened 2021-08-30 18:39 UTC
### Description

In the addons settings (chrome-extension://fbeffbjdlemaoicjdapfpikkikjoneco/webpages/settings/index.html) the language is set to romanian (for me) and i want to change it but THERE'S NO SETTINGS TO CHANGE IT WHATSOEVER

and i don't want to change the settings of my browser

### Repoduction steps

umm set ur browser to a foreign language and check chrome-extension://fbeffbjdlemaoicjdapfpikkikjoneco/webpages/settings/index.html

### Expected behaviour

![image](https://user-images.githubusercontent.com/79767244/131388067-096c79c9-50fd-4b4f-9396-8f441e6db1e5.png)

new language tab added using inspect element

### Actual behaviour

no settings to change language

### Screenshots

not applicable*

### Environment

Browser: Google Chrome 92.0.4515.159
Scratch Addons version: v1.19.1
Operating system: Windows 10 OS Version 2009 (Build 19042.1165)

### Additional context

not applicable*

**Comment by RedGuy12** [comment] 2021-08-30 18:42
duplicate of #2670

**Closed by RedGuy12** 2021-08-30 18:42 UTC
Labels: type: bug, status: needs triage
