### ISSUE TITLE
Color Picker Inputs compatibility with Opacity Slider

### ISSUE THREAD

**Issue by CubesterYT** [ScratchAddons/ScratchAddons#5321] opened 2022-11-04 22:25 UTC
### Why this would be helpful/solve a problem

Ever since the addition of the Opacity Slider, I've been searching for ways to make it better, and look for potential bugs. A way to make it better is to add compatibility with the Color Picker Inputs addon:

![image](https://user-images.githubusercontent.com/78769806/200083431-77bdb4bc-6dd2-42d8-b95f-2e3b8cd667e8.png)

As you can see in the above, all original three selections have the addon working with them, obviously, but Opacity is the only one without it. It would be very helpful for the Input addon to work with opacity slider.

### What this change does

Add support for Color Picker Input addon to work with Opacity Slider.

### Possible alternatives

I wouldn't know of any, I guess not add it?

**Comment by mxmou** [comment] 2022-11-05 07:58
Duplicate of #5313

**Closed by mxmou** 2022-11-05 07:58 UTC
Labels: type: enhancement, scope: addon
