### ISSUE TITLE
Disable Cloud Data Addon

### ISSUE THREAD

**Issue by RedLight-Scratch** [ScratchAddons/ScratchAddons#7181] opened 2024-02-18 14:53 UTC
### Why this would be helpful

-Some online multiplayer projects are better to play offline for less lag
-Some non-cloud projects actually track you by sending information about your Username, Timezone, and OS to a server

### How this addon works

There would be a toggle on the project page to enable or disable cloud variables (you could also have an option to send but not receive or receive but not send the cloud data).

**Comment by iqnite** [comment] 2024-02-18 15:51
Good idea! There are 3 scenarios in which Scratch disconnects cloud variables, we could replicate one of them to achieve the same effect:
- If the user is in the editor
- If the user is logged out
- If the user is a new scratcher

**Comment by WorldLanguages** [comment] 2024-02-18 17:02
Duplicate of #5111

**Closed by WorldLanguages** 2024-02-18 17:02 UTC
Labels: type: enhancement, new addon, scope: addon
