### ISSUE TITLE
Clearer operator block symbols

### ISSUE THREAD

**Issue by Secret-chest** [ScratchAddons/ScratchAddons#7256] opened 2024-03-09 09:57 UTC
### Why this would be helpful

The current operator block symbols are +-*/<=>. They don't line up, the asterisk is too high, and they are generally short.

### How this addon works

Change them into ＋－＊／＜＝＞. These are the fullwidth forms.

**Comment by Waakul** [comment] 2024-03-09 10:04
It's a very slight change no one needs

**Comment by Waakul** [comment] 2024-03-09 10:05
To make it clear just enable the "Customizable block text style" addon and enable the "Bold text" setting

**Comment by Samq64** [comment] 2024-03-09 14:02
Duplicate of #2645.

**Closed by Samq64** 2024-03-09 14:02 UTC
Labels: type: enhancement, new addon, scope: addon
