### ISSUE TITLE
"New feature" indicator

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#3443] opened 2021-09-07 01:37 UTC
### Is your request related to a problem? Please describe.

When an addon is updated to include a new feature that is disabled by default, it isn't included with the brand-new addons. New features shouldn't be banished from the "new" section just because they aren't increasing the addon count.

### Describe the solution you'd like

When an addon is updated with a new setting, it would be included in the "Featured new" or "Other new" section, but with a special indicator such as "Updated" or something of that nature.

![image](https://user-images.githubusercontent.com/43426138/132270695-89b24e75-5e45-4dcf-9d0f-754fba27457f.png)

Then, when the addon is expanded, the new setting would be highlighted with the existing "New!" label.

![image](https://user-images.githubusercontent.com/43426138/132271139-194e3321-daeb-467c-b32f-4e3dff79736b.png)

**Comment by TheColaber** [comment] 2021-09-07 12:58
Duplicate of #1424

**Comment by TheColaber** [comment] 2021-09-07 12:59
You can mention the New tag on settings in that issue since that's a new idea.

**Closed** 2021-09-07 12:58 UTC
Labels: type: enhancement, status: needs triage
