### ISSUE TITLE
Less black padding (editor)

### ISSUE THREAD

**Issue by PhoenixAndStuf** [ScratchAddons/ScratchAddons#990] opened 2020-12-09 16:53 UTC
**Describe the new addon.**

Pretty self-explanatory. Just makes the svg of a scratch block have less padding.

**Foreseeable bugs/inconpatibilities**

Might not work with the custom block colors addon.

**Comment by areeq0325** [comment] 2020-12-09 18:16
I'm not a member, but this looks like a duplicate of #592.

**Comment by WorldLanguages** [comment] 2020-12-09 19:04
Moving to #592

**Closed by WorldLanguages** 2020-12-09 19:04 UTC
Labels: new addon
