### ISSUE TITLE
"Data category tweaks" not showing "list" icon

### ISSUE THREAD

**Issue by ToastGoat** [ScratchAddons/ScratchAddons#7332] opened 2024-04-04 03:07 UTC
### Description

When "Data category tweaks" is enabled the icon for "lists" does not appear

### Steps to reproduce

1. Enable "Data category tweaks"
2. Open editor
3. Look between "Variables" and "My Blocks"

### Demonstration(s) and additional context

![image](https://github.com/ScratchAddons/ScratchAddons/assets/165977783/d81b803b-cc88-4513-854d-ac963eff7625)

### Environment

Browser: Firefox 124.0.2
Scratch Addons version: 1.37.0 
Operating system: Windows 10

**Comment by BroJac5246** [comment] 2024-04-04 03:24
Duplicate of #7323.

This will be fixed very soon — it's a regression from the April Fools' update.

**Closed** 2024-04-04 03:49 UTC
Labels: type: bug, status: needs triage
