### ISSUE TITLE
Shortcut block

### ISSUE THREAD

**Issue by Supernatnat11** [ScratchAddons/ScratchAddons#4026] opened 2022-01-04 07:09 UTC
### Is your request related to a problem? Please describe.

All scratch blocks can quickly become too big or too long so take up a lot of space in the editor. 

### Describe the solution you'd like

Add that when you right click on a block (loop, custom block ...) you can shrink it to better be able to store your editor.

**Comment by Supernatnat11** [comment] 2022-01-04 07:10
Please don't tell me it's already proposed

**Comment by RedGuy12** [comment] 2022-01-10 22:26
Duplicate of #1199

**Closed by RedGuy12** 2022-01-10 22:26 UTC
Labels: type: enhancement, new addon, scope: addon
