### ISSUE TITLE
Custom buttons in top bar

### ISSUE THREAD

**Issue by FluddTheWadder8** [ScratchAddons/ScratchAddons#3523] opened 2021-09-18 21:41 UTC
### Is your request related to a problem? Please describe.
Maybe there is a page that you visit frequently on Scratch and would like to access from anywhere on the website.

### Describe the solution you'd like
Add a feature to make custom buttons in the top bar of the site. This would probably be based off the Discuss button add-on.

### Describe alternatives you've considered
None

### Additional context
N/A

**Comment by Samq64** [comment] 2021-09-18 22:18
#951

**Comment by RedGuy12** [comment] 2021-09-18 22:24
Duplicate of #951

**Closed by RedGuy12** 2021-09-18 22:24 UTC
Labels: type: enhancement, new addon, scope: addon
