### ISSUE TITLE
Preview when editing a post unaffected by dark mode

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#1480] opened 2021-02-01 14:30 UTC
**Describe the bug**

When clicking the preview icon while editing a forum post, the preview is not affected by dark mode.

**To Reproduce**

1. Enable website dark mode
2. Click "Edit" below your post on the forums
3. Click the preview button
4. The preview has white background.

**Expected behavior**

It would be dark. The matches for `experimental_forums_preview.js` should include `https://scratch.mit.edu/post/*/edit/`.

**Comment by TheColaber** [comment] 2021-02-01 14:31
Dupe of #898?

**Comment by apple502j** [comment] 2021-02-01 14:32
Duplicate of #898

**Comment by TheColaber** [comment] 2021-02-01 14:33
It's an about:blank iframe: 
![image](https://user-images.githubusercontent.com/72760579/106472364-98f15680-6470-11eb-9d4e-99ddabc96cb8.png)

**Comment by mxmou** [comment] 2021-02-01 15:26
Not a duplicate, the addon currently uses an userscript to work around #898. This is just a missing match pattern.

**Comment by TheColaber** [comment] 2021-02-01 15:28
there is no pattern to match, it's an about:blank iframe

**Comment by TheColaber** [comment] 2021-02-01 15:33
Oh I think I see... well then.

**Closed** 2021-02-01 15:49 UTC
Labels: scope: addon, type: bug
