### ISSUE TITLE
Show hidden blocks in block palette

### ISSUE THREAD

**Issue by Chikorita-Lover** [ScratchAddons/ScratchAddons#5269] opened 2022-10-25 23:23 UTC
### Why this would be helpful/solve a problem

Sometimes, I want to use a hidden Scratch block (such as the While block) without modifying the project's JSON.

### What this addon does

This addon shows the functional hidden blocks in Scratch (only those that still work in Scratch 3.0, such as the While block) in the block palette (similar to what TurboWarp does by default). This also works with the developer tools that allows blocks to be added to the scripts pane by searching.

The following groups of hidden blocks can be shown in the block palette, and disabled by the user at will:
- When this Sprite Touches (1 hat)
- Counter (1 reporter, 2 stack)
- While (1 C block, enabled by default)
- For Each (1 C block, enabled by default)
- Loud? (1 Boolean)

**Comment by WorldLanguages** [comment] 2022-10-26 01:09
Duplicate of #817

**Closed by WorldLanguages** 2022-10-26 01:09 UTC
Labels: type: enhancement, new addon, scope: addon
