### ISSUE TITLE
Can barely scroll using mouse wheel

### ISSUE THREAD

**Issue by Endermaster3690** [ScratchAddons/ScratchAddons#1834] opened 2021-03-12 19:57 UTC
**Describe the bug**

I know this isn't my mouse because I can scroll in Github perfectly fine.
Anyways in the project editor i can barely use my mouse wheel to code.
I can scroll through sounds perfectly too though.
This is a big problem does anyone know why?

**To Reproduce**

No idea. Just please help.

**Expected behavior**

Cause problems making a project

**Device (please complete the following information):**

- OS: Windows 10
- Chrome browser
- Version idk

**Comment by RedGuy12** [comment] 2021-03-12 20:18
Does this happen with SA off? If no, can you share a exported settings file? If yes, post in Scratch Bugs and Glitches
________________________________
From: Endermaster3690 ***@***.***>
Sent: Friday, March 12, 2021 1:58:14 PM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] Can barely scroll using mouse wheel (#1834)


Describe the bug

I know this isn't my mouse because I can scroll in Github perfectly fine.
Anyways in the project editor i can barely use my mouse wheel to code.
I can scroll through sounds perfectly too though.
This is a big problem does anyone know why?

To Reproduce

No idea. Just please help.

Expected behavior

Cause problems making a project

Device (please complete the following information):

  *   OS: Windows 10
  *   Chrome browser
  *   Version idk

**Comment by Endermaster3690** [comment] 2021-03-12 20:25
> Does this happen with SA off? If no, can you share a exported settings file? If yes, post in Scratch Bugs and Glitches

Turned off SA I can scroll normal
Turned it back on i cant scroll
okay ill export my settings and how do i share a settings file?

**Comment by RedGuy12** [comment] 2021-03-12 20:29
Can you put the file on Google drive/onedrive/dropbox or etc?
________________________________

**Comment by Endermaster3690** [comment] 2021-03-12 20:34
> Can you put the file on Google drive/onedrive/dropbox or etc?

can i just show the the stuff that showed up when i opened it in notepad?? yes it showed stuff that seems to make sense

**Comment by RedGuy12** [comment] 2021-03-12 20:36
> > Can you put the file on Google drive/onedrive/dropbox or etc?
> 
> can i just show the the stuff that showed up when i opened it in notepad?? yes it showed stuff that seems to make sense

That would work too.

**Comment by Endermaster3690** [comment] 2021-03-12 20:39
{"core":{"lightTheme":false,"version":"1.11.0"},"addons":{"60fps":{"enabled":true,"settings":{"framerate":60}},"a11y":{"enabled":false,"settings":{"tabNav":true}},"account-settings-capitalize":{"enabled":false,"settings":{}},"animated-thumb":{"enabled":true,"settings":{"persistentThumb":false}},"better-emojis":{"enabled":false,"settings":{}},"better-featured-project":{"enabled":false,"settings":{}},"better-quoter":{"enabled":true,"settings":{}},"bitmap-copy":{"enabled":false,"settings":{}},"block-palette-icons":{"enabled":true,"settings":{}},"block-switching":{"enabled":true,"settings":{"border":true,"control":true,"data":true,"event":true,"extension":true,"looks":true,"motion":true,"noop":true,"operator":true,"sensing":true,"sound":true}},"cat-blocks":{"enabled":true,"settings":{}},"clones":{"enabled":true,"settings":{}},"cloud-games":{"enabled":true,"settings":{}},"color-picker":{"enabled":true,"settings":{}},"comments-linebreaks":{"enabled":false,"settings":{}},"confirm-actions":{"enabled":true,"settings":{"followinguser":false,"joiningstudio":false,"projectsharing":true}},"copy-message-link":{"enabled":true,"settings":{}},"curator-link":{"enabled":true,"settings":{"styleAsNormalText":true}},"dark-www":{"enabled":true,"settings":{"selectedMode":"experimental-dark"}},"data-category-tweaks":{"enabled":false,"settings":{"separateListCategory":true,"separateLocalVariables":false}},"data-category-tweaks-v2":{"enabled":false,"settings":{"moveReportersDown":false,"separateListCategory":true,"separateLocalVariables":false}},"disable-auto-save":{"enabled":false,"settings":{}},"discuss-button":{"enabled":true,"settings":{"buttonName":"Discuss","removeIdeasBtn":false}},"editor-colored-context-menus":{"enabled":true,"settings":{}},"editor-dark-mode":{"enabled":true,"settings":{"selectedMode":"dark-editor","textShadow":true}},"editor-devtools":{"enabled":true,"settings":{}},"editor-messages":{"enabled":true,"settings":{}},"editor-searchable-dropdowns":{"enabled":true,"settings":{}},"editor-stage-left":{"enabled":false,"settings":{}},"editor-stepping":{"enabled":true,"settings":{}},"editor-theme3":{"enabled":true,"settings":{"Pen-color":"#4c495f","control-color":"#e1a91a","custom-color":"#632d99","data-color":"#ee7d16","data-lists-color":"#cc5b22","events-color":"#c88330","looks-color":"#8a55d7","motion-color":"#4a6cd4","operators-color":"#5cb712","sensing-color":"#2ca5e2","sounds-color":"#bb42c3"}},"exact-count":{"enabled":true,"settings":{"forumuser":true,"studio":true,"user":true}},"feature-unshared":{"enabled":true,"settings":{}},"fix-buttons":{"enabled":true,"settings":{}},"fix-uploaded-svgs":{"enabled":true,"settings":{}},"folders":{"enabled":false,"settings":{}},"forum-quote-code-beautifier":{"enabled":false,"settings":{"bordercolor":"#28A5DA"}},"forum-search":{"enabled":true,"settings":{}},"forum-time-zones":{"enabled":false,"settings":{}},"full-signature":{"enabled":true,"settings":{"signature":true,"whathappen":true,"whatworkingon":true}},"hide-flyout":{"enabled":false,"settings":{"speed":"default","toggle":"hover"}},"image-uploader":{"enabled":true,"settings":{"project_thumbnails":false}},"infinite-scroll":{"enabled":false,"settings":{"forumScroll":true,"messageScroll":true,"profileCommentScroll":true,"projectScroll":true,"showFooter":true,"studioScroll":true}},"last-edit-tooltip":{"enabled":true,"settings":{}},"live-featured-project":{"enabled":true,"settings":{"alternativePlayer":"none","autoPlay":false,"forceAlternative":false,"showMenu":true}},"load-extensions":{"enabled":false,"settings":{"music":true,"pen":true,"text2speech":false,"translate":false,"videoSensing":true}},"longer-wiwo":{"enabled":true,"settings":{}},"mediarecorder":{"enabled":false,"settings":{}},"more-links":{"enabled":true,"settings":{}},"mouse-pos":{"enabled":true,"settings":{}},"msg-count-badge":{"enabled":true,"settings":{}},"mute-project":{"enabled":true,"settings":{}},"my-ocular":{"enabled":true,"settings":{"discuss":true,"profile":true}},"onion-skinning":{"enabled":true,"settings":{"afterTint":"#0000FF","beforeTint":"#FF0000","default":false,"layering":"front","mode":"merge","next":0,"opacity":25,"opacityStep":10,"previous":1}},"pause":{"enabled":true,"settings":{}},"progress-bar":{"enabled":true,"settings":{"height":5,"topbar":false}},"project-info":{"enabled":true,"settings":{"editorCount":true}},"project-notes-tabs":{"enabled":true,"settings":{}},"remix-tree-button":{"enabled":true,"settings":{"buttonColor":"#0fbd8c"}},"remove-sprite-confirm":{"enabled":true,"settings":{}},"resizable-comment-input":{"enabled":true,"settings":{}},"scratch-messaging":{"enabled":true,"settings":{}},"scratch-notifier":{"enabled":false,"settings":{"becomeownerstudio_notifications":false,"commentsforme_notifications":false,"commentsonmyprojects_notifications":false,"curatorinvite_notifications":false,"favoriteproject_notifications":false,"followuser_notifications":false,"forumpost_notifications":false,"loveproject_notifications":false,"mark_as_read_when_clicked":false,"notification_sound":"addons-ping","remixproject_notifications":false,"studioactivity_notifications":false}},"scratchr2":{"enabled":false,"settings":{"activeColor":"#4280d7","linkColor":"#4d97ff","primaryColor":"#4d97ff"}},"scratchstats":{"enabled":true,"settings":{}},"search-load-more-fix":{"enabled":true,"settings":{}},"search-profile":{"enabled":true,"settings":{}},"semicolon":{"enabled":false,"settings":{}},"show-bbcode":{"enabled":false,"settings":{}},"studio-tools":{"enabled":true,"settings":{"mystufftools":true}},"true-youtube-links":{"enabled":true,"settings":{}},"variable-manager":{"enabled":true,"settings":{}},"youtube-fullscreen":{"enabled":true,"settings":{}}}}

**Comment by RedGuy12** [comment] 2021-03-12 20:51
cant repo

**Comment by RedGuy12** [comment] 2021-03-12 20:51
can you show a project? where it happens

**Comment by Endermaster3690** [comment] 2021-03-12 20:52
> can you show a project? where it happens

https://scratch.mit.edu/projects/381748114/editor/

**Comment by RedGuy12** [comment] 2021-03-12 21:58
cant repo still

**Comment by WorldLanguages** [comment] 2021-03-12 21:59
@RedGuy12 Repro*, short for "reproduce"

Not adding scope tag because not sure what causes this yet
@Endermaster3690 Can you disable addons by one one, refreshing the page each time, and see when it stops happening?

**Comment by Endermaster3690** [comment] 2021-03-12 22:14
> @RedGuy12 Repro*, short for "reproduce"
> 
> Not adding scope tag because not sure what causes this yet
> @Endermaster3690 Can you disable addons by one one, refreshing the page each time, and see when it stops happening?

i will later

**Comment by Endermaster3690** [comment] 2021-03-13 00:09
no, im not doing it it is too time consuming.

**Comment by TheColaber** [comment] 2021-03-13 03:12
Wow, I was actually able to repro... seems to be editor dark mode surprisingly! That's so interesting...

**Comment by TheColaber** [comment] 2021-03-13 03:15
I can repro with just 
![image](https://user-images.githubusercontent.com/72760579/111017275-621c3380-8380-11eb-82c7-588d75fd3439.png)
cc @mxmou Was there something you've changed to this addon that caused this?

**Comment by TheColaber** [comment] 2021-03-13 03:19
Well, this is weird...

https://user-images.githubusercontent.com/72760579/111017351-01412b00-8381-11eb-8aa0-1c124359ae51.mp4


NOTE: When my cursor is offscreen, it is trying to scroll.

**Comment by mxmou** [comment] 2021-03-13 09:15
@TheColaber Can reproduce. Some dark mode versions hide workspace dots by settings the background color of the workspace to a solid color, which apparently makes scrolling impossible in Chrome (but not in Firefox).

The solution is to set `stroke: none` on the dots instead of removing them completely. I'll add the fix for this to #1805.

**Comment by mxmou** [comment] 2021-03-13 10:11
Will be fixed when #1805 is merged.

**Comment by RedGuy12** [comment] 2021-03-13 12:23
We can't help you otherwise
________________________________

**Comment by mxmou** [comment] 2021-03-13 12:29
> We can't help you otherwise

TheColaber already found the addon that causes this.

**Comment by WorldLanguages** [comment] 2021-03-13 13:22
> I'll add the fix for this to #1805.

Can we fix this in a new smaller PR for v1.11.1? That PR might take a while to get merged

**Comment by RedGuy12** [comment] 2021-03-13 14:24
> > We can't help you otherwise
> 
> TheColaber already found the addon that causes this.

Oof

My wifi turned off at night sothe email was  just

**Comment by WorldLanguages** [comment] 2021-03-13 14:27
> Can we fix this in a new smaller PR for v1.11.1? That PR might take a while to get merged

@mxmou (?) Do you want to take this?

**Comment by mxmou** [comment] 2021-03-13 14:39
@WorldLanguages I'll make a PR for this.

**Closed** 2021-03-13 15:40 UTC
Labels: feedback, priority: 3, scope: addon, type: bug
