### ISSUE TITLE
Elements on settings page appear incorrectly on a small window

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#644] opened 2020-11-04 10:18 UTC
**Describe the bug**

When the extension's settings page is resized so the window is small, the elements appear incorrectly.

**To Reproduce**

1. Open the settings page
2. Resize the window
3. Observe

**Expected behavior**

Either of these two.
1. The settings page should be responsive by resizing the elements and hide unnecessary elements.
2. The settings page should have `min-height` and `min-width` values so people can scroll and the elements would appear correctly. (not quite elegant)

**Screenshots**

![image](https://user-images.githubusercontent.com/11584103/98096759-b8530480-1ebe-11eb-8f85-e8c453627fd5.png)
![image](https://user-images.githubusercontent.com/11584103/98096797-c1dc6c80-1ebe-11eb-9c33-fa888d7962ea.png)

**Device**

Mozilla Firefox 82.0.2, SA 1.2.1

**Comment by YOYITsM3M8** [comment] 2020-11-04 12:16
Only Firefox?

**Comment by Hans5958** [comment] 2020-11-04 13:18
> 
> 
> Only Firefox?

Only **tested** in Firefox. It should be obvious about what will happen on Chrome.

**Comment by YOYITsM3M8** [comment] 2020-11-04 15:04
Ahhhhhh the horror

**Comment by GrahamSH-LLK** [comment] 2020-11-06 15:49
Duplicate of https://github.com/ScratchAddons/ScratchAddons/issues/189

**Closed** 2020-11-06 16:58 UTC
Labels: bug
