### ISSUE TITLE
Scratch Addons 2.0™

### ISSUE THREAD

**Issue by apple502j** [ScratchAddons/ScratchAddons#5001] opened 2022-08-18 02:21 UTC
There has been a discussion on Scratch Addons 2.0 recently on Discord. No, we haven't decided whether to have such releases. But I thought it'd be better to talk about that here, rather than Discord - to make it more open. 

I've assigned those who participated in the discussion to share your views. Others are also welcome, we just want opinions first.

**Comment by Secret-chest** [comment] 2022-08-18 04:51
what

**Comment by mxmou** [comment] 2022-08-18 06:16
Do we need a "Scratch Addons 2.0"? I think making design changes in smaller steps is much better.

**Comment by retronbv** [comment] 2022-08-18 12:13
When we convert to MV3 isn't that going to be SA v2?

**Comment by mxmou** [comment] 2022-08-18 12:15
> When we convert to MV3 isn't that going to be SA v2?

The issue is labeled "scope: design".

**Comment by retronbv** [comment] 2022-08-18 12:16
> > When we convert to MV3 isn't that going to be SA v2?
> 
> The issue is labeled "scope: design".

I see, my bad.

**Comment by GrahamSH-LLK** [comment] 2022-08-18 19:13
<img width="1512" alt="Screen Shot 2022-08-16 at 9 44 18 PM" src="https://user-images.githubusercontent.com/64214252/185475603-d940b223-bfb0-4f19-be51-04ac29dc50a7.png">
This is implemented

**Comment by lisa-wolfgang** [comment] 2022-08-18 20:03
> Do we need a "Scratch Addons 2.0"? I think making design changes in smaller steps is much better.

This is true for most things. However, whatever we decide on for a reworked addon discoverability system will likely require large-scale changes. Since we're also migrating the extension to MV3, it makes the most sense to optimize every new feature for each other rather than on old systems that are about to be obsolete.

**Comment by Norbiros** [comment] 2022-08-18 20:22
Some time ago I added WIP feature that adds seeAlso scope in addons, and suggestedForYou... (`seeAlso-and-suggestedForYou` branch). Maybe it could work as addon discoveralibity?

**Comment by DNin01** [comment] 2022-08-18 23:07
Maybe this could start a pattern of the version going through 3.0, 4.0, 5.0, and so on, like browsers and some other desktop apps. I think this way of versioning SA could work great, as there's no sign of discontinuing SA. Thoughts on this?

**Comment by lisa-wolfgang** [comment] 2022-08-18 23:28
We shouldn't randomly switch to a new versioning system. There would have to be an actual reason to do so, and I can't think of any.

**Comment by mxmou** [comment] 2022-08-19 06:36
> However, whatever we decide on for a reworked addon discoverability system will likely require large-scale changes.

Even large changes can usually be split into multiple smaller ones that can be made independently. The only case where that probably wouldn't make sense is if the entire settings page and popup were rewritten (to use Vue 3, components instead of iframes, ...).

> Since we're also migrating the extension to MV3, it makes the most sense to optimize every new feature for each other rather than on old systems that are about to be obsolete.

I don't think MV3 will affect webpages at all.

**Comment by Hans5958** [comment] 2022-08-19 10:15
`scope: design ` is for the UI design and such. The scope is general, specifically large changes that warrants a "2.0."

**Comment by Weredime** [comment] 2022-08-20 08:55
If SA 2.0 happens, we need build step

**Comment by WorldLanguages** [comment] 2022-08-20 15:01
> Since we're also migrating the extension to MV3, it makes the most sense to optimize every new feature for each other rather than on old systems that are about to be obsolete.

MV3 doesn't affect our frontends in any meaningful way, like mxmou said.

Realistically, these are the few important things MV3 affects: (excludes stupid stuff like `chrome.pageAction` renaming to `chrome.action`)
- We have to drop support for older browsers that don't support basic MV3 features. However, I did find some workarounds to support as many old Chrome versions as possible (Chrome 93+)
- The background page now becomes a service worker in Chrome. Docs suggest we refactor some of our background page code to account for this, but we're not completely sure if it's necessary. https://github.com/ScratchAddonsMV3/ScratchAddons/pull/1 appears to work fine and it misses many considerations suggested by Chrome docs. This needs more research.
- `chrome.*` APIs now return promises, making some of our code cleaner
- We have to use declarativeNetRequest instead of webRequestBlocking (already shipping on 1.28)
- Other changes we already had into account while still on MV2 (like avoiding the use of `setInterval` on the background page)

Still, the time taken to consider MV3 was meaningful. I ended up suggesting the Chrome extensions team [a new extension permission](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/WDHR0urVV1c/m/hpcqbya5AAAJ) and have browsed crbug.com frequently because MV3 is not very well documented.
Also, exact details on Firefox support of MV3 by the end of this year still leaves many questions.

But my point here is, MV3 isn't really connected to end-user experience. It might be slightly, but probably not enough to decide not to incrementally make changes, instead of changing all at once with a deadline that has little to do with user experience.

**Comment by Weredime** [comment] 2022-08-20 18:32
We should probably finish MV3, release on 1.x and then start work on 2.x

**Comment by Weredime** [comment] 2022-08-21 21:31
To warrant a 2.0 release, we should majorly refactor most of core, background and service workers. (and build step for easy)
For example:

- Migration to Vue 3 from Vue 1 (with build step)
- Use `webext-bridge` for cleaner IPC code
- module.js injection by chrome.scripting
- Conform to chrome mv3 standards
- and much more

**Comment by Hans5958** [comment] 2022-09-13 02:02
Closed in favor of #5103.

**Closed by Hans5958** 2022-09-13 02:02 UTC
Labels: scope: meta
