### ISSUE TITLE
Easy Block Switching

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#670] opened 2020-11-07 17:25 UTC
**Scratch 3 Is missing some key features from Scratch 2.0**

For example we need to be able to choose logical operators and conditionals with a dropdown. And one of my suggestions that is we use `oncontextmenu` on blocks and add more options. Here are some blocks that I think we should modify:

Conditionals
Operators 
Change x/y by ()
Set x/y to ()
Turn clockwise/anticlockwise () degrees
Functions Being Called - Just like variables when the contextmenu opens there should be a list of functions to choose from

**Comment by WorldLanguages** [comment] 2020-11-07 17:29
Duplicate of #593

**Comment by WorldLanguages** [comment] 2020-11-07 17:30
I see you've requested additional stuff, feel free to comment those in the other issue. But it's basically the same request

**Closed** 2020-11-07 17:29 UTC
Labels: new addon
