### ISSUE TITLE
Turbowarp player in editor (player)

### ISSUE THREAD

**Issue by retronbv** [ScratchAddons/ScratchAddons#164] opened 2020-09-02 13:26 UTC
This replaces the existing player with turbowarp by grabbing the id from url and embedding turbowarp where the normal player would be

**Link to the new addon**

[here](https://github.com/YOYITsM3M8/ScratchAddons)

**Comment by Hans5958** [comment] 2020-09-02 13:57
Make sure you search for the issues first before creating one! (#79, #150)

**Comment by YOYITsM3M8** [comment] 2020-09-03 16:47
This was deemed duplicate of #150

**Comment by Hans5958** [comment] 2021-02-20 13:02
This is actually not a duplicate, #150 refers to buttons to TurboWarp. This refers to changing the player in the first place.

**Comment by retronbv** [comment] 2021-02-20 13:22
I never expected this issue to reopen

**Comment by Hans5958** [comment] 2021-02-20 13:34
Neither does I. I lowkey remembered that someone opened it. Turns out it closed as a dupe.

**Comment by retronbv** [comment] 2021-02-20 14:42
I opened it lol

**Comment by Hans5958** [comment] 2021-02-20 16:08
> I opened it lol

Yeah I know, just edited it to clarify

**Comment by WorldLanguages** [comment] 2021-03-05 18:33
This addon is hard to get right so I'll try to make it myself or help on the dev discord so that someone can make it

**Closed** 2021-07-28 17:42 UTC
Labels: new addon, scope: addon, type: enhancement

**Comment by retronbv** [comment] 2021-07-29 04:28
finally :tada: :tada::tada::tada::tada::tada::tada::tada::tada::tada::tada::tada:
