### ISSUE TITLE
Right click option on stack in editor: convert to scratchblocks

### ISSUE THREAD

**Issue by ksdavidc** [ScratchAddons/ScratchAddons#6662] opened 2023-09-17 18:45 UTC
### Why this would be helpful

I use scratchblocks (sb) pseudocode in teaching, and sometimes convert it to images for printing worksheets, etc.

Right now I hand type the sb code, but it would be **AWESOME** if i could get the code directly from the editor for pasting into my text editor. 

### My suggestion

When you right click a stack (Duplicate, add comment, etc.) it would be nice if there were an option to copy the sb pseudocode for that stack (ultimately, for all the code in a sprite, project??? ;-) ) say below where copy block, etc are.

I imagine this might be possible to implement, since SA already has some sb related addons, so you must have a way of working with sb, but I don't have a clue of the details of how that would be done.

### Possible alternatives

Right now I hand type the sb code, but it would be **AWESOME** if I could get the code directly from the editor for pasting into my text editor. 

Sometimes I use a parse-sb3-blocks, but this has some limitations.

### Additional context

Apologies if this is a duplicate. I did a search and nothing similar seemed to come up.

**Comment by ksdavidc** [comment] 2023-09-17 18:54
And another thing: convert sb to actual code blocks??? hahahahaha well, one can dream....

**Comment by Samq64** [comment] 2023-09-18 00:56
There's already an addon to save script images: https://scratch.mit.edu/scratch-addons-extension/settings#addon-blocks2image

As for copying the scratchblocks BBCode, that's a duplicate of #2336.

> And another thing: convert sb to actual code blocks??? hahahahaha well, one can dream....

It was actually possible to backpack scratchblocks at one point and there's a suggestion for that too: #3225.

**Closed by Samq64** 2023-09-18 00:56 UTC
Labels: status: duplicate, type: enhancement, new addon, scope: addon

**Comment by ksdavidc** [comment] 2023-09-18 03:11
Thank you for looking at this. However, I think you are referring to different issues.

> There's already an addon to save script images: https://scratch.mit.edu/scratch-addons-extension/settings#addon-blocks2image
> 
Not what I want. I want text, not images. _Sometimes_ I use images, but what I really need is the text so I can edit the text directly. 

> As for copying the scratchblocks BBCode, that's a duplicate of #2336.

I understand, but that is not what I am asking. I am specifically talking about the editor and scratchblocks and not bbcode. 

a) I am not sure, but I am under the impression scratchblocks is a different repo and a thing unto itself.. I don't know much about Bbcode, but I think it recognizes sb, but is an overset of it created for a different purpose. I could be wrong...

b) Maybe I don't understand how you are suggesting bbcode could be used in my context. Are you referring to generating bbcode from images in the forums (themselves generated from text originally)? Can one do that in the scratch editor?

I want to convert my scratch project codeblocks (generated by scratch using movable codeblocks) into text directly, similarly to how it is done by [parse-sb3-blocks](https://apple502j.github.io/parse-sb3-blocks/index.html), but from within scratch itself. 

c) I was not being clear about images. What I meant was that I want to use my own instances of scratchblock.js to generate them,  as specified[ in their repo](https://github.com/scratchblocks/scratchblocks). Images, to the extent I use them, are a secondary thing, that it is often more flexible for me to generate using my own instance of scratchblocks.js.

There is a [comment in the thread you mentioned](https://github.com/ScratchAddons/ScratchAddons/issues/2336#issuecomment-1622639349) that does seem to mention sb, but that thread seems to be mostly about bbcode...I am specifically only concerned with the getting the sb code from the scratch editor, so I can get my sample project code and then present and elaborate on it via text for my students. 
> 
> > And another thing: convert sb to actual code blocks??? hahahahaha well, one can dream....
> 
> It was actually possible to backpack scratchblocks at one point and there's a suggestion for that too: #3225.

Again, just to be clear, I am talking scratch editor. Isn't that what parse-sb3-blocks is doing?

**Comment by ksdavidc** [comment] 2023-09-20 03:38
> > (a) I am not sure, but I am under the impression scratchblocks is a different repo and a thing unto itself.. I don't know much about Bbcode, but I think it recognizes sb, but is an overset of it created for a different purpose. I could be wrong...
> 
> Assuimg you talking about this:
> 
> ```
> when flag clicked
> if <touching (mouse-pointer v)> then
>     say [Hello!] for (2) seconds
> end
> ```
> 
> you're right. BBCode here just means surrounding it in `[scratchblocks][/scratchblocks]` tags. If the addon is made the tags would probably be either removed or optional.
> 

Thanks for the reply. Yeah, that's what I had in mind.

> > > > And another thing: convert sb to actual code blocks??? hahahahaha well, one can dream....
> > > 
> > > 
> > > It was actually possible to backpack scratchblocks at one point and there's a suggestion for that too: #3225.
> > 
> > 
> > Again, just to be clear, I am talking scratch editor. Isn't that what parse-sb3-blocks is doing?
> 
> I could be wrong but I think it can only convert project code into scratchblocks text, not the other way around. #3225 suggests converting scratchblocks text on the forums into working scripts and adding them to the backpack. I don't think there's a suggestion to do that from the editor though.

But, that's all I want. I want the text only (preferable without delimiter), from the editor. scratchblocks.js provides an html implementation that I can use to go the other way. For example, if I can get the text to the clipboard, I can edit, correct, and demonstrate code live in class... 

Of course, it may not be possible. I mean the parser does it, but I really don't know enough about how things are implemented to know what the obstacles or difficulty might be.

One, though not really the only, consideration that came to mind is that  parse-sb3-blocks is limited to shared projects, which I understand. I think if SA could do this, it would allow me access to my own unshared projects, yet still preserve limiting access to others' only shared projects, which I am imagining would be acceptable from a security standpoint.

Anyway, as long as what I wanted is properly understood, I can understand if for other reasons it is not planned or impractical...

**Comment by ksdavidc** [comment] 2023-09-20 10:42
> As for copying the scratchblocks BBCode, that's a duplicate of https://github.com/ScratchAddons/ScratchAddons/issues/2336.

Was closing tabs and I just reread [#2336](https://github.com/ScratchAddons/ScratchAddons/issues/2336). @Samq64 you were right, as you stated above, it is a duplicate. I am very sorry for not seeing what you meant the first time. 

At the top it goes on about bbcode not being compatible, but reading the last comment, (which I hadn't) [it suggests scratchblocks from the editor, exactly as I was suggesting](https://github.com/ScratchAddons/ScratchAddons/issues/2336#issuecomment-1622639349). I see what you were saying now. :-) mea culpa

**Comment by ksdavidc** [comment] 2023-09-20 18:32
> I'm going to change the name of the #2336 issue so that it's more clear
> Don't worry about creating duplicates, it's hard to keep track of all past issues

Time is vast and precious, as is your thoughtful kindness and my appreciation :-)
