### ISSUE TITLE
Make `editor-theme3` affect monitors

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#5936] opened 2023-04-16 19:24 UTC
Scratch will soon be adding an option to switch between different "themes" for the editor and each one changes the colors of blocks, including variable, list and reporter monitors on the stage. If you visit the [New Block Colors on Scratch Lab](https://lab.scratch.mit.edu/contrast-blocks/) and click the checkbox next to any reporter block in the blocks palette to show it on the stage as a monitor, the background color of the value displayed by it will match that of the block.

![A few reporter monitors with the high-contrast block colors for the backgrounds of displayed numbers](https://user-images.githubusercontent.com/106490990/232337037-6eaee857-c7eb-430d-9d17-63360529d80d.png)

`editor-theme3` does not have this capability. Regardless of your chosen block colors, monitors won't be affected. For example, if I customize the "variables" color, the variables blocks will be recolored but the variable monitors will still have the default orange background for the variables, so if a user has customized the color of the variable blocks to something other than a color provided by a built-in theme (once those become available), they won't be able to change the color of the monitors to match the blocks.

**Comment by WorldLanguages** [comment] 2023-04-16 21:34
Related: #3912

**Comment by mxmou** [comment] 2023-04-17 10:14
Duplicate of #4033

**Closed by mxmou** 2023-04-17 10:14 UTC
Labels: type: enhancement, scope: addon
