### ISSUE TITLE
Dragging problem with scripts when "Auto-hiding block palette" addon is enabled

### ISSUE THREAD

**Issue by sfederici** [ScratchAddons/ScratchAddons#4202] opened 2022-02-05 18:02 UTC
### Description

Cannot drag scripts to left-hand side of the script area when "Auto-hiding block palette" addon is enabled and the block palette is closed. When I do, the script automatically move in a position that won't overlap the palette when it is open.

### Reproduction steps

1. enable the "Auto-hiding block palette" addon 
2. create a script
3. close the block palette, by clicking the button of the visible category
4. drag the script to the left-hand side of the script area

### Expected behaviour

When the block palette is closed and you drag a script to the left-hand side of the script area, the script stays where it has been dragged.

### Actual behaviour

The script automatically move to the right, in order not to overlap the palette when it is open again

### Screenshots

None

### Environment

- Browser: Chrome 98.0.4758.80 (x86_64)
- Scratch Addons version: 1.24.1
- Operating system: macOS

### Additional context

None

**Comment by mxmou** [comment] 2022-02-05 18:07
Duplicate of #2766

**Closed by mxmou** 2022-02-05 18:07 UTC
Labels: type: bug, status: needs triage
