### ISSUE TITLE
Less padding on blocks addon

### ISSUE THREAD

**Issue by Secret-chest** [ScratchAddons/ScratchAddons#1122] opened 2020-12-29 07:40 UTC
I really like 2.0 blocks over 3.0 because they are 2-3 times smaller and it's easier to make long scripts. I can't just zoom out, the text is becoming unreadable. And blocks in the pallete? They don't zoom out. I would like an addon that reduces padding on ALL blocks, including those in the pallete. It will also remove the extension icon from extension blocks.

**Comment by TheColaber** [comment] 2020-12-29 15:34
Hey! Welcome to the ScratchAddons Repo! Actually, this is a duplicate of #592 sadly.

**Comment by Marc92020** [comment] 2020-12-29 15:35
I agree. The 2.0 blocks look better over the 3.0 blocks but i'm not sure how the extensions could fit. So "My Blocks" categorey would have to be "More Blocks" also why am I posting on a duplicate because I just saw while making this comment

**Comment by GrahamSH-LLK** [comment] 2020-12-29 15:37
Duplicate of #592.

**Closed by GrahamSH-LLK** 2020-12-29 15:37 UTC
Labels: new addon

**Comment by Secret-chest** [comment] 2020-12-30 14:58
> I agree. The 2.0 blocks look better over the 3.0 blocks but i'm not sure how the extensions could fit. So "My Blocks" categorey would have to be "More Blocks" also why am I posting on a duplicate because I just saw while making this comment

Oh yeah but I didn't say to move the categories. This 
would be a separate addon :)
