### ISSUE TITLE
Slider setting type

### ISSUE THREAD

**Issue by Secret-chest** [ScratchAddons/ScratchAddons#7264] opened 2024-03-12 15:03 UTC
There should be a slider setting for animation values, paddings, double-clicks and so on. This would allow providing precision while keeping it easy to understand. There should also be a way to set the value to a specific number.

**Comment by WorldLanguages** [comment] 2024-03-12 15:26
Duplicate of...?

**Comment by mxmou** [comment] 2024-03-12 15:33
Duplicate of #6319

**Closed by mxmou** 2024-03-12 15:33 UTC
Labels: status: duplicate
