### ISSUE TITLE
"Confirmations" addon: project share confirmation broke in v1.33.0

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#6219] opened 2023-06-17 18:23 UTC
### Description

![image](https://github.com/ScratchAddons/ScratchAddons/assets/17484114/7b129d72-7618-4171-8e3b-8a0fca3a977b)

### Steps to reproduce

> Confirmations addon is broken.If you share a project, it shows "Share" and you can't close it.

### Demonstration(s) and additional context

Probably caused by the addon.tab.scratchClass changes.

### Environment

Browser: reported from Chromium, Firefox is probably affected too
Scratch Addons version: 1.33.0

**Comment by mybearworld** [comment] 2023-06-17 19:34
This was meant to be fixed by #6137, wasn't it?

**Comment by mxmou** [comment] 2023-06-17 20:02
#6137 added a workaround that works when not on a project page, but it didn't fix the root cause of the bug. In this case, the addon is running on a project page, so the bug still occurs.

The problematic code (written by me, so part of this is my fault) is in `modal.js`. There are multiple calls to `addon.tab.scratchClass()` that can happen even if `confirm()` or `prompt()` is called without `{ useEditorClasses: true }`.

**Comment by WorldLanguages** [comment] 2023-06-17 20:16
Well, my initial solution for #4106 was short-sighted as I dismissed the concept of `addon.tab.*` methods that call other methods (which happens quite often).
This probably isn't a problem for future additions, but we missed the opportunity to test every addon that already uses `addon.tab.scratchClass` ether directly or indirectly. I quickly searched for all addons that ran before complete, `confirm-actions` was in that list but I forgot that addons that run in the project page could still be affected.

**Comment by kokofixcomputers** [comment] 2023-06-17 20:19
That is exactly what problem i'm having

**Comment by kokofixcomputers** [comment] 2023-06-17 20:22
I will test firefox for you

**Comment by WorldLanguages** [comment] 2023-06-17 20:23
There are also some other `addon.tab.*` methods that work unreliably when runningAtComplete=false, such as `addon.tab.scratchMessage` and possibly more.

**Comment by kokofixcomputers** [comment] 2023-06-17 20:24
Okay firefox is also affected

**Comment by kokofixcomputers** [comment] 2023-06-17 20:26
maybe it would be easier to debug by looking in at what has been changed from the last version to the latest version

**Comment by kokofixcomputers** [comment] 2023-06-17 20:29
oh boy... it really changed a lot: https://github.com/ScratchAddons/ScratchAddons/compare/v1.32.1...v1.33.0

**Comment by medlans** [comment] 2023-06-17 20:32
I tried sharing a project in the project editor, and it shows nothing/did nothing (it didn't even try to go to the project page). 
![seeinside](https://github.com/ScratchAddons/ScratchAddons/assets/124630024/45faa7d6-3677-4653-a9e8-e804996cda9a)
![Screen Shot 2023-06-17 at 2 31 11 PM](https://github.com/ScratchAddons/ScratchAddons/assets/124630024/3a0129b5-d906-4290-b77f-fbca295e53d5)

**Comment by kokofixcomputers** [comment] 2023-06-17 20:33
yes that is the problem we're discussing now here same problem for me all the 1.33.0 versions is affected including the beta ones

**Comment by DNin01** [comment] 2023-06-17 20:36
Related: #6203

**Comment by WorldLanguages** [comment] 2023-06-17 20:54
> There are multiple calls to `addon.tab.scratchClass()` that can happen even if `confirm()` or `prompt()` is called without `{ useEditorClasses: true }`.

That seems unrelated in this case. This bug also happens when trying to share inside the editor.
The root cause is that the `confirm-actions` userscript runs on `"runAtComplete": false`.
The best solution would probably mean we call `addon.tab.scratchClassReady()` inside the `addon.tab.prompt` implementation, only if necessary. I'm just goin to add scratchClassReady() to the confirmations addon directly for now.

**Closed** 2023-06-17 21:49 UTC
Labels: type: bug, scope: addon api, source: feedback, priority: 2, scope: addon, bug: regression
