### ISSUE TITLE
New Fonts

### ISSUE THREAD

**Issue by sakhiy2010** [ScratchAddons/ScratchAddons#4370] opened 2022-03-07 10:06 UTC
Those fonts are the worst. I will request this to make you because it’s very beautiful to have some new fonts.
![2713E212-1B16-4E96-BB2D-DA5398AA66B1](https://user-images.githubusercontent.com/100205903/157010522-6ff5ef8f-ef9f-42b2-983d-497a2ed0023d.png)

**Comment by apple502j** [comment] 2022-03-07 12:19
First, we do not support iPad...
Second, duplicate of #2050 and other issues

**Closed by apple502j** 2022-03-07 12:19 UTC
Labels: type: enhancement, new addon, scope: addon

**Comment by sakhiy2010** [comment] 2022-03-07 12:24
> First, we do not support iPad...
> Second, duplicate of #2050 and other issues

Ok
