### ISSUE TITLE
Copy and Paste Blocks Between Projects

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#1058] opened 2020-12-15 22:29 UTC
**I Like the Idea of Not Having to Drag My Scripts into My Backpack and Copy Scripts by Just Using Ctrl+C Ctrl+V**

The main problem is that its a waste of time and space when I drag and drop my scripts into my large backpack. I would prefer having a temporary backpack which works like a clipboard so I can copy and paste code, costumes and sounds.

**Comment by WorldLanguages** [comment] 2020-12-15 22:31
Duplicate of #1004

**Closed by WorldLanguages** 2020-12-15 22:31 UTC
Labels: enhancement
