### ISSUE TITLE
Support the system dark mode setting

### ISSUE THREAD

**Issue by Oren-Lindsey** [ScratchAddons/ScratchAddons#4186] opened 2022-02-04 22:16 UTC
### Is your request related to a problem? Please describe.
I'd like it if the dark mode feature would mirror the system setting. For example, on macos, it will automatically switch to dark mode after sunset. So it would be really nice if scratch addons could do the same

### Describe the solution you'd like
Support the [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) css media feature

### Describe alternatives you've considered
None

### Additional context
None

**Comment by apple502j** [comment] 2022-02-05 03:59
Duplicate of #4041

**Closed by apple502j** 2022-02-05 03:59 UTC
Labels: status: duplicate, type: enhancement
