### ISSUE TITLE
White text / İnvisible text on logs problem

### ISSUE THREAD

**Issue by Selman3447** [ScratchAddons/ScratchAddons#2849] opened 2021-06-20 15:23 UTC
### Description

In the new plugin "debugger", when you print a log while in the editor, the expected black text in the logs becomes white.

### Repoduction steps

1. Enter the project
2. 
![image](https://user-images.githubusercontent.com/57229667/122679288-ec332e00-d1f2-11eb-9f68-fceea1ca5088.png) 
Write this code in the puppet.

3. Run it and enter the logs section.
4. There are lines but no texts. When you hold down the left mouse button and select the line, you will see that the text will appear in the selection.

### Expected behaviour

Appearance of texts. : 
![image](https://user-images.githubusercontent.com/57229667/122679483-bb9fc400-d1f3-11eb-9b1d-16e755e447e3.png)

screenshot Taken from Opera GX

Not : Since I am Turkish, the language remained Turkish, I could not change it. 

### Actual behaviour

![image](https://user-images.githubusercontent.com/57229667/122679573-1b966a80-d1f4-11eb-8444-14e3f3cdb3c9.png)

### Screenshots

![image](https://user-images.githubusercontent.com/57229667/122679573-1b966a80-d1f4-11eb-8444-14e3f3cdb3c9.png)

![image](https://user-images.githubusercontent.com/57229667/122679600-2fda6780-d1f4-11eb-9a2e-2cc13ead07c1.png)

### Environment

- Browser:  Chrome 89
- Scratch Addons version:  v1.16.3
- Operating system:  Windows 10 Pro (20H2)

**Comment by Samq64** [comment] 2022-12-18 23:37
I can't reproduce on Chromium. This was probably fixed by #4008.

**Comment by WorldLanguages** [comment] 2022-12-19 16:10
I'm pretty certain this was fixed, since we haven't received any similar bug reports recently

**Closed by WorldLanguages** 2022-12-19 16:10 UTC
Labels: type: bug, scope: addon
