### ISSUE TITLE
Background image for the website

### ISSUE THREAD

**Issue by Genius398** [ScratchAddons/ScratchAddons#1970] opened 2021-03-25 15:37 UTC
Spoiler: This is an expansion of #1944 (not made by me)

**Describe the new addon**
This addon will allow us to upload an image and that image will be the background for Scratch.mit.edu

**Comment by retronbv** [comment] 2021-03-25 15:43
This sounds useless.

**Comment by Genius398** [comment] 2021-03-25 15:43
> This sounds useless.

Ok

**Comment by Explosion-Scratch** [comment] 2021-03-25 19:50
Wait, wait, it's a valid suggestion. I think it'd be pretty cool TBH.

**Comment by FunctionalMetatable** [comment] 2021-03-27 09:27
Dupe of #1598

**Comment by WorldLanguages** [comment] 2021-03-27 14:42
Duplicate of #1598

**Closed by WorldLanguages** 2021-03-27 14:42 UTC
Labels: new addon, scope: addon, type: enhancement
