### ISSUE TITLE
`forum-live-preview` doesn't have Scratch 3 blocks with `scratchblocks` enabled

### ISSUE THREAD

**Issue by tonyzhigit** [ScratchAddons/ScratchAddons#5607] opened 2023-01-12 10:33 UTC
### Description

`forum-live-preview` doesn't have Scratch 3 blocks even though `scratchblocks` is enabled.

### Steps to reproduce

1. Go to Scratch Discuss.
2. Create a post with Scratch blocks.

### Demonstration(s) and additional context

![image](https://user-images.githubusercontent.com/100283902/212043440-47f0835a-0200-4f60-bc9a-4f17f6b87b72.png)

### Environment

Browser: Chrome 110.0.5481.30 dev x64
Scratch Addons version: v1.30.0
Operating system: Windows 11 21H2

**Comment by mxmou** [comment] 2023-01-12 11:39
Duplicate of #4130

**Closed by mxmou** 2023-01-12 11:39 UTC
Labels: type: enhancement, scope: addon
