### ISSUE TITLE
Set X & Y to 0 when new sprite created

### ISSUE THREAD

**Issue by TecFuture** [ScratchAddons/ScratchAddons#2138] opened 2021-04-12 20:43 UTC
Personally I think its sooo annoying 
When you make a new sprite and its coordinates are not 0,0, .
So this suggestion asks for it to automatically set sprite coordinates to what you want.

This is probably simple.

**Comment by TheColaber** [comment] 2021-04-12 20:44
Duplicate of #1759

**Closed by TheColaber** 2021-04-12 20:44 UTC
Labels: status: needs triage, type: enhancement
