### ISSUE TITLE
Echo button

### ISSUE THREAD

**Issue by Hexigon102** [ScratchAddons/ScratchAddons#2946] opened 2021-07-08 09:28 UTC
### Is your request related to a problem? Please [`describe.`]
yes the problem is that on the scratch GUI has an echo button and i personally think that the scratch should have that on its main. 

### Describe the solution you'd like
i think that instead of constantly repeating the sound we should make it so that it so that it does it for you.

### Additional context

 they may be an earape button  too

**Comment by apple502j** [comment] 2021-07-08 09:33
Duplicate of #1811

**Closed by apple502j** 2021-07-08 09:33 UTC
Labels: new addon, scope: addon, type: enhancement

**Comment by Hexigon102** [comment] 2021-07-08 09:35
> Duplicate of #181

oh

**Comment by Hexigon102** [comment] 2021-07-08 09:37
> Duplicate of #1811

how do i delete it

**Comment by CST1229** [comment] 2021-07-08 09:53
> 
> 
> > Duplicate of #1811
> 
> how do i delete it

i don't think you do

**Comment by RedGuy12** [comment] 2021-07-08 17:43
You can't delete it. Just abandon it and it will be ignored.
________________________________
