### ISSUE TITLE
Project stats (number of assets, sprites, scripts)

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#594] opened 2020-10-29 03:21 UTC
**Describe the new addon**

Shows the number of assets, sprites, and/or scripts on the project page a la 2.0.

![image](https://user-images.githubusercontent.com/43426138/97521591-e0e17880-196b-11eb-864e-f941d43dd352.png)

**Comment by Hans5958** [comment] 2020-10-29 12:12
Note: not a duplicate of #492

**Comment by WorldLanguages** [comment] 2020-10-29 18:15
Note that ST members can see these counts, but normal users can't

**Comment by Hans5958** [comment] 2020-10-30 08:14
Well, even if that number is literally removed completely, it's still possible to count it.

**Closed** 2020-11-12 18:19 UTC
Labels: new addon
