### ISSUE TITLE
Addon to change Variable between "Global" and "Private"

### ISSUE THREAD

**Issue by tuankhanh7692** [ScratchAddons/ScratchAddons#3286] opened 2021-08-15 11:18 UTC
Add option to change between "For all sprites" and "For this sprite only" in Context menu when Right-click the variable.

Example:
![Screenshot 2021-08-15 181723](https://user-images.githubusercontent.com/73464690/129476647-e6ac78c4-8bbd-4ac3-9364-434251776362.png)

**Comment by pufferfish101007** [comment] 2021-08-15 12:20
Duplicate of #1469

**Closed** 2021-08-15 12:38 UTC
