### ISSUE TITLE
Add Color Swatches

### ISSUE THREAD

**Issue by Mbrick2** [ScratchAddons/ScratchAddons#4406] opened 2022-03-14 07:37 UTC
### Describe the solution you'd like

I would like color swatches to be added

### Describe alternatives you've considered

None

### Additional context

Its in a branch for the scratch-gui.

### Mockups
https://llk.github.io/scratch-gui/color-swatches/

**Comment by mxmou** [comment] 2022-03-14 10:03
Duplicate of #1807

**Closed by mxmou** 2022-03-14 10:03 UTC
Labels: type: enhancement, new addon, scope: addon
