### ISSUE TITLE
Incorrect jump when clicking message

### ISSUE THREAD

**Issue by sfederici** [ScratchAddons/ScratchAddons#1686] opened 2021-02-28 07:50 UTC
When I click a message in the website related to a comment, while I go exactly to the comment when Scratch Addons are disabled, instead I go to the correct project but to a wrong position when Scratch Addons are enabled. 

One example is link https://scratch.mit.edu/projects/492631932/#comments-191263432

**Comment by RedGuy12** [comment] 2021-02-28 12:58
Duplicate of #749
________________________________

**Closed** 2021-02-28 13:29 UTC
Labels: scope: addon, status: duplicate, type: bug
