### ISSUE TITLE
Always add plural to "paste browser/os versions" rather than only when making a new topic within BaG

### ISSUE THREAD

**Issue by ghost** [ScratchAddons/ScratchAddons#6939] opened 2023-12-08 17:27 UTC
### Why this would be helpful

Unsure whether or not to report this as a bug or just suggest it, I chose suggestion for now.
Occasionally some bugs are posted in QaS instead of BaG ([src 1](https://scratch.mit.edu/discuss/topic/728582/), [src 2](https://scratch.mit.edu/discuss/topic/727390/), list goes on) - Now, ScratchAddons makes "version" in "flash version" plural to let other users know that SA is being used, however this only occurs when you are creating a topic in Bugs and Glitches, not if you are replying, not even anywhere else.

Incase I explained it terribly:
In BaG, SA makes "version" plural.
Normal being (note that I'm using mine as an example here)
> My browser / operating system: Windows NT 10.0, Firefox 120.0, No Flash version detected

However if you have SA enabled (I made the "s" italic here just to be more noticable) :

> My browser / operating system: Windows NT 10.0, Firefox 120.0, No Flash version**s** detected

This is only for when you create a topic in Bugs and Glitches though, not when anywhere else.

### My suggestion

Always make it plural instead of only when creating a topic in Bugs and Glitches, it can help resolve things if related to one of SA's addons (eg. "Why are project stats hidden", and since bugs can be accidentally posted in any subforum, this could help reach resolutions quicker), especially if the OP deletes the OS/Browser version when making the post in BaG, since now we don't know if the user is using ScratchAddons unless they tell (vaguely due to the extension policy).

### Possible alternatives

1. Don't add this (though I guess this is an obvious one)
2. Copy over the notice from BaG to QaS or places where it would be asked about (Though in this regard it'd be better to just add it to all subforums)
3. Add an alternative sign instead of making "version" plural, however that'd be a bit weird and inconsistent.

**Comment by WorldLanguages** [comment] 2023-12-08 21:49
This might be a duplicate of #6065

**Closed as not planned** 2023-12-08 21:52 UTC
Labels: status: duplicate, type: enhancement, scope: core
