### ISSUE TITLE
Player:FullScreen

### ISSUE THREAD

**Issue by fierin** [ScratchAddons/ScratchAddons#3140] opened 2021-07-28 10:31 UTC
### Description
Add the ability to Turn on a native Full-Screen Similar to the addon linked below (in sources).

### Solution
Add a second maximize button to apply native Full-Screen.

#### Author:
 Fierin Deathbomb
#### Sources:
https://chrome.google.com/webstore/detail/scratch-fullscreen/gihphjdlkigognnhkankfjcclijhadpe

**Comment by TheColaber** [comment] 2021-07-28 13:10
This is a dupe of an issue made by @pufferfish101007, tho I can't find the issue right now.

**Comment by fierin** [comment] 2021-07-28 13:11
Oh! Thank you!

**Closed by TheColaber** 2021-07-28 13:10 UTC
Labels: new addon, scope: addon

**Comment by mxmou** [comment] 2021-07-28 14:22
> This is a dupe of an issue made by @pufferfish101007, tho I can't find the issue right now.

#587?

**Comment by fierin** [comment] 2021-07-28 15:06
yes. Thank you.

**Comment by WorldLanguages** [comment] 2021-07-28 17:39
Duplicate of #587
