### ISSUE TITLE
Collapsible Block Stacks

### ISSUE THREAD

**Issue by ErrorGamer2000** [ScratchAddons/ScratchAddons#2329] opened 2021-04-30 15:33 UTC
**Describe the new addon**

Add a little arrow in the bottom left of a hat block that, when clicked, shrinks the code stack, just like in many code editors. This will allow you to see more of your scripts and compact blocks more.

I need opinions. Is this going to be useful? Does anyone want something like this?

**Comment by TheColaber** [comment] 2021-04-30 15:35
Yup! This exsits!
![image](https://user-images.githubusercontent.com/72760579/116718551-15c89980-a9a8-11eb-9593-989321d9a896.png)
Just disabled!

**Comment by RedGuy12** [comment] 2021-04-30 15:35
Duplicate of #1199

**Closed by RedGuy12** 2021-04-30 15:35 UTC
Labels: new addon, scope: addon, type: enhancement

**Comment by ErrorGamer2000** [comment] 2021-04-30 15:37
Oooh, I see the function now. Maybe this is fixable? it is sort of broken right now.

**Comment by mxmou** [comment] 2021-04-30 15:38
> Oooh, I see the function now. Maybe this is fixable? it is sort of broken right now.

This is a Blockly feature that is not included in Scratch by default. It would probably require some changes to work properly.

**Comment by ErrorGamer2000** [comment] 2021-04-30 15:39
Probably ... I was origionally just going to use the svg's style, which would allow t=for transition effects.

**Comment by RedGuy12** [comment] 2021-04-30 15:41
Please talk in the original issue instead - #1199

**Comment by TheColaber** [comment] 2021-04-30 15:41
> This is a Blockly feature that is not included in Scratch by default. It would probably require some changes to work properly.

This function exists in scratch's blockly
https://github.com/LLK/scratch-blocks/blob/893c7e7ad5bfb416eaed75d9a1c93bdce84e36ab/core/block_svg.js#L542

**Comment by ErrorGamer2000** [comment] 2021-04-30 15:42
Let's move, I have more to say
