### ISSUE TITLE
auto disable addon

### ISSUE THREAD

**Issue by StioStudio** [ScratchAddons/ScratchAddons#5861] opened 2023-03-31 06:49 UTC
### Why this would be helpful

Makes it so that addons does not need to be turned off manuly. I thought of this because april fools addons got turned off manuly.

### My suggestion

How it would (probably) will work:
```jsonc
"disable": {
   "date": [
       {
       "day": 1,
      "moth": 04,
      "year": false //if false/undifined it is always on
      },
      {
      "day": 13,
      "moth": 6,
      "year": 2024
   ]
}
```

### Possible alternatives

I don't know

### Additional context

404

**Comment by Samq64** [comment] 2023-03-31 11:39
Duplicate of #5248.

**Comment by Samq64** [comment] 2023-03-31 11:41
Although the implementation in your issue is pretty different, so I guess this could stay open.

**Comment by StioStudio** [comment] 2023-03-31 12:13
This would do it automatically, so it is pretty different

**Comment by WorldLanguages** [comment] 2023-04-02 18:29
Related: #5431

**Closed** 2023-06-28 04:51 UTC
Labels: type: enhancement, scope: addon.json, scope: core
