### ISSUE TITLE
Modify user agent string to indicate SA users

### ISSUE THREAD

**Issue by apple502j** [ScratchAddons/ScratchAddons#1872] opened 2021-03-14 16:16 UTC
There has been several BaG topics describing Scratch Addons bug. To make it easier to track SA bugs, we can add subtle changes to the User Agent string added with globe button.

Additionally, we can use meta.agent attribute of project.json which is more obscure.

Example: `My browser / operating system: ChromeOS 13597.105.0, Chrome 88.0.4324.208, No Flash versions detected` (version -> version**s**)

**Comment by mxmou** [comment] 2021-03-14 16:44
Good idea, most people probably wouldn't notice this change but it would be easily searchable.

I don't agree with changing `meta.agent` though, I don't think anyone needs to know if a project was created using SA or not.

**Comment by apple502j** [comment] 2021-03-14 16:46
@mxmou meta.agent is more obscured, so we can put more information there.

**Comment by WorldLanguages** [comment] 2021-03-14 17:43
I'd prefer not to touch project JSON, but modifying the user agent button in the forums would be a good idea

**Comment by mxmou** [comment] 2021-03-14 18:29
> @mxmou meta.agent is more obscured, so we can put more information there.

Like the Scratch Addons version? I'm not sure if putting data like that into project files would help with identifying bugs caused by SA because most bug reports don't contain links to projects.

**Comment by apple502j** [comment] 2021-03-15 06:08
If they use SA, it's likely they used it to save all projects, so we can check latest project's meta.agent. A lot of BaG posts don't include env info.

**Comment by Hans5958** [comment] 2021-03-15 11:14
I disagree for doing this shady technique and instead prefer going one step further to warn users to not post them on the forms.

**Comment by WorldLanguages** [comment] 2021-03-15 13:51
We should consider adding a list of "known current version bugs" when a user is making a new BaG thread? We would simply maintain a .txt file for each version and list the most common bugs like "can't scroll editor" and such (and tell users a workaround to avoid the bug until a fix gets shipped)

**Comment by TheColaber** [comment] 2021-03-15 13:51
How would we update this when we find a new bug?

**Comment by mxmou** [comment] 2021-03-15 13:53
> How would we update this when we find a new bug?

Probably by hosting the list on `scratchaddons.com`.

**Comment by WorldLanguages** [comment] 2021-03-15 13:56
Yeah, I don't like force-pinging `scratchaddons.com` because of privacy concerns, but this seems like a sensible choice, since it would only happen when creating a new thread in a specific forum category.

**Comment by Hans5958** [comment] 2021-03-15 14:01
Force-pinging?

How about link to a page on the wiki? Or to another repository? Or a thread on the discussion (and to be merged with that thread of rejected ideas)

**Comment by RedGuy12** [comment] 2021-03-15 14:03
Why not a link to the issues page filled g to only those labeled "bug"?
________________________________

**Comment by Hans5958** [comment] 2021-03-15 14:06
> 
> Why not a link to the issues page filled g to only those labeled "bug"?
>

We can, but this depends of the implementation. If it's a single link, then it is fine, but if it's going to written on a page, then you will need to deal with GitHub API

**Comment by WorldLanguages** [comment] 2021-03-15 21:51
> Force-pinging?

I meant "pinging without requiring user interaction"

**Comment by Hans5958** [comment] 2021-03-19 13:20
> I meant "pinging without requiring user interaction"

@WorldLanguages 

Could you clarify?

**Comment by WorldLanguages** [comment] 2021-03-19 14:49
@Hans5958 We won't be asking the users if they want to ping scratchaddons.com to load the list of known bugs, we'll request automatically "without their permission" (no user interaction needed) when the page loads

**Comment by Hans5958** [comment] 2021-03-19 14:54
> @Hans5958 We won't be asking the users if they want to ping scratchaddons.com to load the list of known bugs, we'll request automatically "without their permission" (no user interaction needed) when the page loads

I see.

BTW, have you considered https://github.com/ScratchAddons/ScratchAddons/issues/1872#issuecomment-799444100?

**Comment by WorldLanguages** [comment] 2021-03-19 15:01
> BTW, have you considered #1872 (comment)?

Not sure people will actually click, lol

**Comment by Hans5958** [comment] 2021-03-19 15:06
> Not sure people will actually click, lol

It's not just linking the page. I'm also talking about hosting it in other places like the wiki. Like you can fetch https://raw.githubusercontent.com/wiki/ScratchAddons/ScratchAddons/Installing-Scratch-Addons.md and it gets the raw text and we can just select it

**Comment by WorldLanguages** [comment] 2021-03-19 15:07
Ohh

**Comment by easrng** [comment] 2021-03-22 13:35
We could also just put some invisible chars in.

**Comment by RedGuy12** [comment] 2021-03-22 13:36
> We could also just put some invisible chars in.

that was an idea, but wl changed his mind since invisible chars can do some odd things with djanganobb sometimes

**Comment by easrng** [comment] 2021-03-22 13:52
what if we use "ᖯrowser / operating system"? The b is a confusable and not a real b. This approach would be simpler cus we just need to edit an element and not hook anything.

**Comment by easrng** [comment] 2021-03-22 14:45
Ok this works on the forums, I just tested it.

**Comment by Hans5958** [comment] 2021-03-22 14:46
Should we conduct a poll for what's going to be changed?

**Closed** 2021-04-01 20:12 UTC
Labels: priority: 3, scope: core, type: enhancement
