### ISSUE TITLE
Validate addon manifest workflow needs to be updated

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6025] opened 2023-05-07 18:02 UTC
If I'm correct, we need to update [one of our Actions](https://github.com/ScratchAddons/validate-json-action/blob/master/action.yml) to stay up to date.

### From the [blog](https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/):

> Node 12 has been out of support since [April 2022](https://github.com/nodejs/Release/#end-of-life-releases), as a result we have started the deprecation process of Node 12 for GitHub Actions. We plan to migrate all actions to run on Node16 by Summer 2023.
> Following on from our [warning in workflows using Node 12](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/), we will start enforcing the use of Node16 rather than Node12 on the 18th of May.
> 
> What you need to do
> For Actions maintainers: Update your actions to run on Node 16 instead of Node 12 ([Actions configuration settings](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions))
> For Actions users: Update your workflows with latest versions of the actions which runs on Node 16 ([Using versions for Actions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions))

**Comment by DNin01** [comment] 2023-05-08 02:38
Pinging code owner @Hans5958

**Comment by Samq64** [comment] 2023-05-08 14:06
Resolved by #6026

**Comment by apple502j** [comment] 2023-05-08 14:47
Note, this issue did not exist at all. #6026 updated Node **from 16** (which is still LTS) to 18.

**Comment by mxmou** [comment] 2023-05-08 14:56
This issue is about the schema validation workflow, which still uses Node 12. See https://github.com/ScratchAddons/validate-json-action/blob/master/action.yml#L20

![image](https://user-images.githubusercontent.com/51849865/236857535-59863345-775a-4516-9de1-aa4ca474b32c.png)

**Comment by apple502j** [comment] 2023-05-08 15:07
This is not a bug with the action file. Closing.

**Comment by WorldLanguages** [comment] 2023-05-08 15:11
Where are we specifying Node version 12? I can't find it.
Did GitHub forget to change the default, or are we relying on third-party software that uses Node 12?

**Comment by mxmou** [comment] 2023-05-08 15:59
> Where are we specifying Node version 12? I can't find it.

In [validate-json-action/blob/master/action.yml](https://github.com/ScratchAddons/validate-json-action/blob/master/action.yml).

**Comment by DNin01** [comment] 2023-05-08 18:29
> > Where are we specifying Node version 12? I can't find it.
> 
> 
> 
> In [validate-json-action/blob/master/action.yml](https://github.com/ScratchAddons/validate-json-action/blob/master/action.yml).

I see, so that repository is where the problem lies and this repo is fine. We'll have to update that, then.

**Comment by DNin01** [comment] 2023-05-08 20:38
Should be as simple as increasing this number [here](https://github.com/ScratchAddons/validate-json-action/blob/bfac677935e59372a7aa444b2933e602b23d2269/action.yml#L20), right?
```diff
-  using: 'node12'
+  using: 'node18'
```

**Comment by DNin01** [comment] 2023-05-08 20:40
Also, if we don't do anything, GitHub will, in a week or two, automatically run it on Node 16 anyway, but changing it ourselves is probably a good practice.

**Comment by Hans5958** [comment] 2023-05-09 02:03
I have updated the image to `node-18:alpine`, so this should be fine at the moment. Perhaps I would try to rewrite the addon to a vanila one, without Docker.

https://github.com/ScratchAddons/validate-json-action/commit/bb185dc6e2d06df2768f9022e414eb2775c5b325

**Closed by Hans5958** 2023-05-09 02:03 UTC
Labels: scope: ci, scope: tech debt
