### ISSUE TITLE
Anti-Mute Prevention

### ISSUE THREAD

**Issue by DogCatPuppyLover** [ScratchAddons/ScratchAddons#2151] opened 2021-04-13 23:19 UTC
**Describe the new addon**

This addon would catch all comments which would trigger the filterbot and prevent them from being sent to the Scratch servers. To accomplish this, it would change the description of a studio that the user is a manager in (which would be specified in the addon settings) to the attempted comment, and if it throws an error, prevent the comment from being posted.

**Comment by TheColaber** [comment] 2021-04-13 23:20
Duplicate of #2104

**Closed by TheColaber** 2021-04-13 23:20 UTC
Labels: new addon, scope: addon, type: enhancement

**Comment by Secret-chest** [comment] 2021-04-14 06:11
> **Describe the new addon**
> 
> This addon would catch all comments which would trigger the filterbot and prevent them from being sent to the Scratch servers. To accomplish this, it would change the description of a studio that the user is a manager in (which would be specified in the addon settings) to the attempted comment, and if it throws an error, prevent the comment from being posted. 

@DogCatPuppyLover Nice solution!

**Comment by WorldLanguages** [comment] 2021-04-14 12:08
Yes but keep in mind we don't know how Scratch internally works, it's possible those studio description edits are still logged or end up in some type of moderation queue, defeating the purpose of the message not ever reaching Scratch mods
