### ISSUE TITLE
Extension not loading bug

### ISSUE THREAD

**Issue by Shubh-Khandelwal** [ScratchAddons/ScratchAddons#2451] opened 2021-05-09 11:53 UTC
**Describe the bug**

Sometimes when I open scratch then Scratch Addons doesn't load

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

- OS: Windows 8 (32 bit), Windows 10 (64 bit)
- Browser: Chrome
- Version:

**Additional context**

**Comment by jeffalo** [comment] 2021-05-09 12:08
you have not filled out the template. please do because we need to be able to reproduce a bug to fix it.

**Comment by mxmou** [comment] 2021-05-09 12:24
> you have not filled out the template. please do because we need to be able to reproduce a bug to fix it.

If I understand correctly, this doesn't happen predictably, so there are no reproduction steps. It happened to me before, if it does again I will check if there are any errors in the background page console.

**Comment by TheChorister** [comment] 2021-05-09 16:28
I had the same bug, and the error was:
```
Uncaught (in promise) TypeError: Cannot read property 'includes of' undefined
at index.js:926
```

I think it is because an addon forgot to add a `tags` property in their `addon.json`, because line 926 of `index.js` is: `manifest.tags.includes("easterEgg")`

**Comment by WorldLanguages** [comment] 2021-05-09 16:48
> I think it is because an addon forgot to add a `tags` property in their `addon.json`

🤔 
![image](https://user-images.githubusercontent.com/17484114/117580212-46f24980-b0cd-11eb-8374-c4b770549072.png)

**Comment by TheChorister** [comment] 2021-05-09 16:57
> > I think it is because an addon forgot to add a `tags` property in their `addon.json`
> 
> 🤔
> ![image](https://user-images.githubusercontent.com/17484114/117580212-46f24980-b0cd-11eb-8374-c4b770549072.png)

When I found the addon without a tags, and edited it (one I had been developing) so it had tags, it showed again.

**Comment by mxmou** [comment] 2021-05-09 18:10
@TheChorister If so, your issue is different - this does occasionally happen in unmodified SA.

**Comment by WorldLanguages** [comment] 2021-05-09 20:04
@mxmou Do you have any other details on which situations addons don't load? Currently they should load sooner or later, no matter if the extension just launched or not

**Comment by xItzDiamondx** [comment] 2021-05-10 16:17
Provide more details and we'll fix it.

**Comment by mxmou** [comment] 2021-05-14 18:38
This just happened to me. The error is: `Unchecked runtime.lastError: The message port closed before a response was received.`
There are no related errors in the background console.

**Comment by TheColaber** [comment] 2021-05-14 18:39
The CS is trying to send smth to the background most likely...

**Comment by WorldLanguages** [comment] 2021-05-14 21:33
> This just happened to me. The error is: `Unchecked runtime.lastError: The message port closed before a response was received.`
> There are no related errors in the background console.

I don't think that's very useful...

**Comment by apple502j** [comment] 2021-05-20 09:30
@mxmou Please provide the full traceback.

**Comment by mxmou** [comment] 2021-05-22 09:05
@apple502j There was no traceback.

**Comment by apple502j** [comment] 2021-05-22 18:51
@mxmou I don't think that message is for SA. At least on Firefox, the background page console dumps errors for all extensions installed (such as uBO, Stylus, or even Mozilla's internal ones)

We don't use ports.

**Comment by apple502j** [comment] 2021-05-22 18:52
Closing @mxmou please open a new issue with more details. Your issue is clearly not the same as OP's.

**Closed by apple502j** 2021-05-22 18:52 UTC
Labels: scope: core, status: needs info, type: bug

**Comment by mxmou** [comment] 2021-05-22 19:16
@apple502j The message was in the Scratch console. The OP says *sometimes when I open scratch then Scratch Addons doesn't load*, which is exactly what happens to me.

**Comment by WorldLanguages** [comment] 2021-05-22 19:34
> We don't use ports.

We don't, but the console error will still say that with simple sendMessage

**Comment by FunctionalMetatable** [comment] 2021-06-18 21:09
![image](https://user-images.githubusercontent.com/67440879/122616199-d94d1c00-d081-11eb-812c-9e3599d30c22.png)

**Comment by WorldLanguages** [comment] 2021-06-18 21:12
@FunctionalMetatable You probably forgot to add an addon.json in your local extension while developing an addon? If this happened in the browser store version we would have gotten 9999 complaints already

**Comment by FunctionalMetatable** [comment] 2021-06-18 21:16
> @FunctionalMetatable You probably forgot to add an addon.json in your local extension while developing an addon? If this happened in the browser store version we would have gotten 9999 complaints already

I have an addon.json in my addon. I think its just replit not pulling the changes from github (the manifest version I have on replit is v1.14.3 which is strange)

**Comment by RedGuy12** [comment] 2021-06-18 23:06
@FunctionalMetatable Are there typos in `addons/addons.json`?
