### ISSUE TITLE
"Display stage on left side" flips the right-side icons

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#2851] opened 2021-06-20 19:00 UTC
### Description

Super minor and nitpicky bug. When the "Display stage on left side" theme is enabled, icons on the right side of the stage toolbar are flipped.

### Reproduction steps

1. Enable the "Display stage on left side" addon
2. Open the Scratch editor
3. Look above the stage (enabling some other addons that add buttons to the stage will help visualize the issue)

### Expected behavior

![image](https://user-images.githubusercontent.com/43426138/122686239-b3389080-d1d5-11eb-9431-8505052adcda.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/43426138/122686264-c9dee780-d1d5-11eb-8032-2c87c1d62386.png)

### Environment

- Browser: Firefox 89
- Scratch Addons version: 1.16.3
- Operating system: Windows 10

**Comment by mxmou** [comment] 2021-06-20 19:09
The correct behavior would be flipping only the small/large stage icons.

**Comment by RedGuy12** [comment] 2021-06-20 19:22
Duplicate of #2846

**Comment by Shluffy** [comment] 2021-06-20 19:34
Dupe? I think this is that the buttons don't flip, the stage is just injected over there, as well as the backdrop tab being flipped

**Comment by lisa-wolfgang** [comment] 2021-06-20 19:38
@RedGuy12 The actual images are flipped in this issue, not the buttons themselves. Please reopen.

**Comment by RedGuy12** [comment] 2021-06-20 23:02
ohhhh

**Closed** 2022-12-28 14:56 UTC
Labels: type: bug, scope: addon
