### ISSUE TITLE
Advanced Color Picker

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#1014] opened 2020-12-12 03:38 UTC
**Hexadecimal Colors are Easier to Remember and Transport**

I wished we could edit the colour picker to add hex codes and transparency. Currently, we have to import semi-transparent images to use them with the rest of our scene. This saves space on the sprites list and code. Hex codes are also a lot easier to transport around the web and have their own way of showing semi-transparency.

Thanks, 
The Shroud Ninja

**Comment by Explosion-Scratch** [comment] 2020-12-12 14:58
Related: #311, #400

**Comment by WorldLanguages** [comment] 2020-12-12 16:11
Duplicate of #311

**Closed by WorldLanguages** 2020-12-12 16:11 UTC
Labels: new addon
