### ISSUE TITLE
Website dark mode doesn't make scrollbars dark in forum preview

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#1833] opened 2021-03-12 16:52 UTC
**Describe the bug**

Website dark mode doesn't inject `scrollbar.css` into the forum preview, so scrollbars aren't dark there.

**To Reproduce**

1. Go to a forum topic
2. Copy and paste `[code]long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text[/code]` into the reply box
3. Click the preview button (green ✅)
4. The scrollbar in the preview box isn't dark.

**Expected behavior**

The scrollbar would be dark.

**Screenshots**

![A screenshot of the bug](https://user-images.githubusercontent.com/51849865/110971804-9b8e7800-835b-11eb-9fb6-986f71a46da2.png)

**Comment by WorldLanguages** [comment] 2021-03-12 17:12
Duplicate of #898?

**Comment by pufferfish101007** [comment] 2021-10-17 12:40
This appears to be fixed now, unless it's just my browser being weird (I'm on mobile)?
![Screenshot_20211017-133442_Kiwi Browser](https://user-images.githubusercontent.com/50246616/137627456-27d93422-fd21-414f-99ea-7e4ed38d9b9f.png)
If it isn't fixed, couldn't we just add the scrollbar file to dark-www/experimental-forums-preview.js?

**Comment by TheColaber** [comment] 2021-10-17 12:49
Must be your browser
![image](https://user-images.githubusercontent.com/72760579/137627812-69fcbd10-c351-412e-8209-5b533675ab02.png)

**Closed** 2021-12-04 18:15 UTC
Labels: type: bug, scope: addon
