### ISSUE TITLE
Hide-flyout addon bug

### ISSUE THREAD

**Issue by sfederici** [ScratchAddons/ScratchAddons#7311] opened 2024-03-29 15:00 UTC
### Description

When the block palette is set to hide automatically, it leaves floating block arguments in the code area if the user clicks a block argument in the block palette

### Steps to reproduce

1. enable the hide-flyout addon
2. set the flyout so that it hides automatically
3. click whatever argument in the block palette

### Demonstration(s) and additional context

https://github.com/ScratchAddons/ScratchAddons/assets/2651868/f5c426ed-4a78-4151-b631-3dfeb6aaeade

### Environment

Browser: Firefox 124.0.1
Scratch Addons version: 1.36.0
Operating system: macOS Sonoma

**Comment by WorldLanguages** [comment] 2024-03-29 15:19
Duplicate of #7024

**Closed by WorldLanguages** 2024-03-29 15:19 UTC
Labels: type: bug, status: needs triage
