### ISSUE TITLE
`remix-tree-button` is not inline with `download-button` and `animated-thumb` enabled

### ISSUE THREAD

**Issue by OneShot-Niko** [ScratchAddons/ScratchAddons#7331] opened 2024-04-03 21:52 UTC
### Description

This is really trivial, it's just a bit annoying to have to scroll down to use the remixtree button (with the addons enabled)

### Steps to reproduce

1. enable `download-button`, `animated-thumb` and `remix-tree-button`
2. go to ~~a project page~~ the page of a project you own
3. the remixtree button shouldnt be inline with the rest and also somewhat clipping into `download-button`

### Demonstration(s) and additional context

![kép](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/baceedcd-335f-4b44-ba0d-ced167150edb)

### Environment

Browser: Firefox 124.0.1 (32 bit)
Scratch Addons version: 5b40c90
Operating system: Windows 10 (screen resolution: 1366 x 768)

**Comment by medlans** [comment] 2024-04-03 22:50
(I had to turn off that 3.0 -> 2.0 userstyle for this as well as the thing that I made) Can replicate with remix tree and download on, but only on certain projects I think:
https://scratch.mit.edu/projects/111787279/
![Downloads](https://github.com/ScratchAddons/ScratchAddons/assets/124630024/38e5447f-9865-4897-b8c4-9c5ae4ef2a94)
On this project (for me), this shows:
https://scratch.mit.edu/projects/992368228/
![ButtonsMyProject](https://github.com/ScratchAddons/ScratchAddons/assets/124630024/5b68bffa-3110-40f9-a980-dc6c42259f84)
Browser: Chrome 123
Scratch Addons version: 1.37.0
Operating system: Mac OS 11.3 Big Sur
Just so you know this looks weird to me

**Comment by OneShot-Niko** [comment] 2024-04-03 22:54
> (I had to turn off that 3.0 -> 2.0 userstyle for this as well as the thing that I made) Can replicate with remix tree and download on, but only on certain projects I think: [scratch.mit.edu/projects/111787279](https://scratch.mit.edu/projects/111787279/) ![Downloads](https://private-user-images.githubusercontent.com/124630024/319384228-38e5447f-9865-4897-b8c4-9c5ae4ef2a94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxODUwNTUsIm5iZiI6MTcxMjE4NDc1NSwicGF0aCI6Ii8xMjQ2MzAwMjQvMzE5Mzg0MjI4LTM4ZTU0NDdmLTk4NjUtNDg5Ny1iOGM0LTljNWFlNGVmMmE5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QyMjUyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMGViZGEyYzI0ZjVkZTFmZTU2NTllOGYyZGJmODc5NDYzNWQ3MjkyOGU1MjI2MTg1ZTFlYjIxNWVmNTY5MWM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u9CABa8C6eu8GLhLgOQqNuy0J9q0FY4z8i3OBQ14It0) On this project (for me), this shows: [scratch.mit.edu/projects/992368228](https://scratch.mit.edu/projects/992368228/) ![ButtonsMyProject](https://private-user-images.githubusercontent.com/124630024/319384591-5b68bffa-3110-40f9-a980-dc6c42259f84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxODUwNTUsIm5iZiI6MTcxMjE4NDc1NSwicGF0aCI6Ii8xMjQ2MzAwMjQvMzE5Mzg0NTkxLTViNjhiZmZhLTMxMTAtNDBmOS1hOTgwLWRjNmM0MjI1OWY4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QyMjUyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmM0MjJjYzZiMWUyMDc1NWIxMGFiN2U3M2FmNWQ5MmEyZjE0NGMxZjBkMmQxOThmMGRmOWFhODg0OWYyY2ZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WElfVNi4aKJl_mVkOKctB2RWoZiAr7wUN-kuKbjjvQQ) Browser: Chrome 123 Scratch Addons version: 1.37.0 Operating system: Mac OS 11.3 Big Sur Just so you know this looks weird to me

Whoops, I forgot that `animated-thumb` only loads on your own projects

~~I'm so intelligent~~

**Comment by Samq64** [comment] 2024-04-03 23:04
Duplicate of #6954.

**Closed by Samq64** 2024-04-03 23:04 UTC
Labels: type: bug, status: needs triage

**Comment by OneShot-Niko** [comment] 2024-04-03 23:07
> Duplicate of #6954.

My apologies, missed it.
