### ISSUE TITLE
goes blank

### ISSUE THREAD

**Issue by parrxtkun** [ScratchAddons/ScratchAddons#5679] opened 2023-01-31 15:03 UTC
### Description

When clicking on the extension the UI is completely blank, other than the extension name and settings button.
Settings page is also blank.

### Steps to reproduce

idk

### Demonstration(s) and additional context

![image](https://user-images.githubusercontent.com/93410491/215796138-c1da0f9b-069d-492e-b99d-fcb38fa29bc7.png)
upon clicking on extension

![image](https://user-images.githubusercontent.com/93410491/215796575-b3efc096-cbfa-4bf0-bb97-8c68408804d1.png)
settings page

### Environment

Browser: Edge (newer one i think)
Scratch Addons version: 1.30.1
Operating system: Windows 11

**Comment by parrxtkun** [comment] 2023-01-31 15:04
i have readded the extension multiple times 

still has this same bug

**Comment by parrxtkun** [comment] 2023-01-31 15:38
any help on how to fix this would be appreciated <3

**Comment by parrxtkun** [comment] 2023-01-31 15:39
also for some reason it works perfectly fine on a different browser account

**Comment by Samq64** [comment] 2023-01-31 15:45
Could you turn on the developer toggle on the on chrome://extensions, click the errors button on the Scratch Addons tile if it appears and post the errors here?

**Comment by parrxtkun** [comment] 2023-01-31 15:55
Error handling response: TypeError: Cannot read properties of undefined (reading 'addonSettings')



Unchecked runtime.lastError: IO error: .../LOCK: File currently in use. (ChromeMethodBFE: 15::LockFile::2)



Error handling response: TypeError: Cannot read properties of undefined (reading 'globalTheme')



Unchecked runtime.lastError: IO error: .../LOCK: File currently in use. (ChromeMethodBFE: 15::LockFile::2)



Error handling response: TypeError: Cannot read properties of undefined (reading 'globalTheme')



Unchecked runtime.lastError: IO error: .../LOCK: File currently in use. (ChromeMethodBFE: 15::LockFile::2)



The resource chrome-extension://fbeffbjdlemaoicjdapfpikkikjoneco/images/icons/expand.svg was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.



The resource chrome-extension://fbeffbjdlemaoicjdapfpikkikjoneco/webpages/settings/components/addon-body.html was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.



The resource chrome-extension://fbeffbjdlemaoicjdapfpikkikjoneco/webpages/settings/components/previews/editor-dark-mode.html was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.



The resource chrome-extension://fbeffbjdlemaoicjdapfpikkikjoneco/images/icons/list.svg was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.



The resource chrome-extension://fbeffbjdlemaoicjdapfpikkikjoneco/webpages/settings/components/addon-tag.html was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.



The resource chrome-extension://fbeffbjdlemaoicjdapfpikkikjoneco/images/icons/web.svg was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.



The resource chrome-extension://fbeffbjdlemaoicjdapfpikkikjoneco/images/icons/popup.svg was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.



The resource chrome-extension://fbeffbjdlemaoicjdapfpikkikjoneco/images/icons/search.svg was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.



The resource chrome-extension://fbeffbjdlemaoicjdapfpikkikjoneco/webpages/settings/components/addon-setting.html was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.



The resource chrome-extension://fbeffbjdlemaoicjdapfpikkikjoneco/webpages/settings/components/modal.html was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.



The resource chrome-extension://fbeffbjdlemaoicjdapfpikkikjoneco/webpages/settings/components/picker-component.html was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.



The resource chrome-extension://fbeffbjdlemaoicjdapfpikkikjoneco/webpages/settings/components/previews/palette.html was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.



The resource chrome-extension://fbeffbjdlemaoicjdapfpikkikjoneco/webpages/settings/components/addon-group-header.html was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.



The resource chrome-extension://fbeffbjdlemaoicjdapfpikkikjoneco/images/icons/brush.svg was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.



The resource chrome-extension://fbeffbjdlemaoicjdapfpikkikjoneco/webpages/settings/components/reset-dropdown.html was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.



The resource chrome-extension://fbeffbjdlemaoicjdapfpikkikjoneco/images/icons/switch.svg was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.



The resource chrome-extension://fbeffbjdlemaoicjdapfpikkikjoneco/images/icons/puzzle.svg was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.



The resource chrome-extension://fbeffbjdlemaoicjdapfpikkikjoneco/webpages/settings/components/category-selector.html was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.


I can post context of needed.

**Comment by Samq64** [comment] 2023-01-31 17:29
Running `chrome.storage.sync.clear()` in the console should fix it, but you'll lose all your settings.

**Comment by DNin01** [comment] 2023-01-31 19:46
Duplicate of #5289

**Comment by DNin01** [comment] 2023-01-31 19:47
You can also try restarting your browser (and/or your computer) - that's what some others have suggested. For the other people this has happened to, this issue also seemed to go away on its own.

**Comment by parrxtkun** [comment] 2023-01-31 21:56
ok ill check that thread

**Comment by WorldLanguages** [comment] 2023-02-01 22:18
> Duplicate of #5289

We don't really know if the root cause is the same.

**Comment by WorldLanguages** [comment] 2023-02-01 22:19
@parrxtkun Did restarting your browser work? Try typing `chrome://restart` into the address bar, and press enter (this will also work on Edge)

**Comment by DNin01** [comment] 2023-02-01 22:45
> > Duplicate of #5289
> 
> 
> 
> We don't really know if the root cause is the same.

In both of these issues, a "LOCK file currently in use" error, or a similar error, appeared, so that's why I thought they might be the same problem.

**Comment by WorldLanguages** [comment] 2023-02-02 22:59
@DNin01 Oh okay, good catch

**Comment by WorldLanguages** [comment] 2023-08-27 23:15
We will track this in #5306

**Closed by WorldLanguages** 2023-08-27 23:15 UTC
Labels: type: bug, status: duplicate, status: needs info, scope: webpages, scope: core
