### ISSUE TITLE
Hiding Users

### ISSUE THREAD

**Issue by Dreadboy302** [ScratchAddons/ScratchAddons#7046] opened 2024-01-04 23:46 UTC
### Why this would be helpful

i have been always getting annoyed by someone that is a threat to the defender's community. Sometimes i want them to not be seen from my sight. if only i can hide that user away from me

### How this addon works

Hides users from your account. This addon adds a "Hide Users list" only seen in the addon you enabled (Hide users addon) you can reset the list by reactivating it or just click he reset list. but this wont make their profile hidden to you.
getting messages from the user you hidden will not be there, includes comments, projects, and studio curators. But if you want to see their comments, projects, etc. you will have a list of activity you want to see from the user(s) you hidden

### Possible alternatives

you would also have the option to make the user you hidden not see your account, either if its projects, comments, etc

### Additional context

For Context: i wanna add this addon because of a scratch user named ConekatFriends keeps filling up my messages with constant love and favors and remixes and refollows. it is unbelievable that she hasn't been banned yet, trust me she terrorized the defender's community and stole artwork

**Comment by CST1229** [comment] 2024-01-05 00:40
Quick reminder that if someone is breaking the Scratch rules, you should report the rule-breaking comments/projects/etc. Or use [Contact Us](https://scratch.mit.edu/contact-us) for other stuff.
> **Help keep the site friendly.**
> It’s important to keep your creations and conversations friendly and appropriate for all ages. If you think something on Scratch is mean, insulting, too violent, or otherwise disruptive to the community, click “Report” to let us know about it. Please use the “Report” button rather than engaging in fights, spreading rumors about other people’s behavior, or otherwise responding to any inappropriate content. The Scratch Team will look at your report and take the appropriate action.

**Comment by DNin01** [comment] 2024-01-05 00:40
Duplicate of #3810

**Comment by DNin01** [comment] 2024-01-05 00:49
One difference between this and #3810 is that #3810 also mentions hiding projects and studios (supposedly from search results?) of certain users, but it's a pretty small difference and probably makes sense here anyway. I'll close this, but if there's a reason for this issue to be tracked separately, let me know.

Nevertheless, I'm not sure if this is within our scope, although the other issue has been open for a couple years.

**Closed by DNin01** 2024-01-05 00:49 UTC
Labels: status: duplicate, type: enhancement, new addon, scope: addon

**Comment by Dreadboy302** [comment] 2024-01-05 00:50
> Quick reminder that if someone is breaking the Scratch rules, you should report the rule-breaking comments/projects/etc. Or use [Contact Us](https://scratch.mit.edu/contact-us) for other stuff.
> 
> > **Help keep the site friendly.**
> > It’s important to keep your creations and conversations friendly and appropriate for all ages. If you think something on Scratch is mean, insulting, too violent, or otherwise disruptive to the community, click “Report” to let us know about it. Please use the “Report” button rather than engaging in fights, spreading rumors about other people’s behavior, or otherwise responding to any inappropriate content. The Scratch Team will look at your report and take the appropriate action.

My Reply: i did report Conekatfriends but she hasn't been banned yet for almost 1 year

**Comment by OneShot-Niko** [comment] 2024-01-05 07:24
I honestly believe that if SA does implement blocking, then people who use SA will just use this feature instead of reporting to properly deal with the user and they just go scott-free, which is also why this is rejected on Scratch.

Though that's probably just me I guess

> I did report (user) but she hasn't been banned yet for almost 1 year

If you used a contact us ticket, you are fine to resend if 1 month passes.

**Comment by DNin01** [comment] 2024-01-05 23:21
> I honestly believe that if SA does implement blocking, then people who use SA will just use this feature instead of reporting to properly deal with the user and they just go scott-free, which is also why this is rejected on Scratch.

Yeah, I understand how that could be a problem. Maybe if we make this, it could only offer the option to "block" someone after a report or two, or as part of the report process.

**Comment by Secret-chest** [comment] 2024-01-06 07:23
> Yeah, I understand how that could be a problem. Maybe if we make this, it could only offer the option to "block" someone after a report or two, or as part of the report process.

Or just remind users to report when blocking - there may be users which post allowed comments, but which you may not like.
