### ISSUE TITLE
Enable/disable clicking on sprites on stage from selecting them.

### ISSUE THREAD

**Issue by Joeclinton1** [ScratchAddons/ScratchAddons#2709] opened 2021-06-07 19:25 UTC
### Is your request related to a problem? Please describe.

Alot of my projects involve clicking and dragging sprites to move them around. However if I do that not in full screen it changes the focus to that sprite which is frustrating when I need to test it by moving the sprite but always have to return the focus to the original sprite afterwards. It also drags it in the editor, which i'd like to override with my own dragging.

### Describe the solution you'd like

I'd like for a button in the addon which you could enable/disable "draggable in editor", which would be in the addons menu.

### Describe alternatives you've considered

Going full screen is one alternative but not really a solution, as it still wastes time, when i'm making lots of iterative changes.
Currently I make it so that you can click near the sprite and move it rather than actually clicking

### Additional context

I was considering how to actually implement this, and it's not trivial. You want to disable the dragging/change focus event but you don't want to disable the onclick event entirely or mouse sensing wouldn't work.
Additionally you'd need to get access to the event listeners of a canvas object and i'm not sure how possible that is.

Alteratively we could modify the scratch code itself. The code we need to change is in either of these I think:

- Rendered Sprite code: https://github.com/LLK/scratch-vm/blob/f405e59d01a8f9c0e3e986fb5276667a8a3c7d40/src/sprites/rendered-target.js

- Mouse code: https://github.com/LLK/scratch-vm/blob/f405e59d01a8f9c0e3e986fb5276667a8a3c7d40/src/io/mouse.js

- Stage GUI code: https://github.com/LLK/scratch-gui/blob/6300e4b819c3bf1a77b613517469d6e631604ab1/src/containers/stage.jsx

Thank you to anyone willing to help. If you don't have time but you know how to solve it tell me and I'll try implementing it.

**Comment by mxmou** [comment] 2021-06-08 06:07
Duplicate of #569?

**Comment by TheColaber** [comment] 2021-06-08 11:13
Hmm not entirely sure, since I thought jeffalos' issue was to add a button to toggle sprite drag mode like in scratch2... I could be wrong tho...

**Comment by RedGuy12** [comment] 2021-06-08 11:32
Maybe ctrl+click?
________________________________
From: Joe Clinton ***@***.***>
Sent: Monday, June 7, 2021 2:25:31 PM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] Enable/disable clicking on sprites on stage from selecting them. (#2709)


Is your request related to a problem? Please describe.

Alot of my projects involve clicking and dragging sprites to move them around. However if I do that not in full screen it changes the focus to that sprite which is frustrating when I need to test it by moving the sprite but always have to return the focus to the original sprite afterwards. It also drags it in the editor, which i'd like to override with my own dragging.

Describe the solution you'd like

I'd like for a button in the addon which you could enable/disable "draggable in editor", which would be in the addons menu.

Describe alternatives you've considered

Going full screen is one alternative but not really a solution, as it still wastes time, when i'm making lots of iterative changes.
Currently I make it so that you can click near the sprite and move it rather than actually clicking

Additional context

I was considering how to actually implement this, and it's not trivial. You want to disable the dragging/change focus event but you don't want to disable the onclick event entirely or mouse sensing wouldn't work.

Additionally you'd need to get access to the event listeners of a canvas object and i'm not sure how possible that is.

Thank you to anyone willing to help. If you don't have time but you know how to solve it tell me and I'll try implementing it.

**Comment by Joeclinton1** [comment] 2021-06-08 12:30
> Duplicate of #569?

I think it's not a duplicate. The main thing I want is the ability to disable the focus being given aways to the sprite after dragging or clicking it.

**Comment by lisa-wolfgang** [comment] 2021-06-09 00:58
> Maybe ctrl+click?

That would make sense provided that we already have a ctrl+click addon for scripts, so it would be an easy association to make for users with that addon enabled.

**Comment by Joeclinton1** [comment] 2021-06-14 00:17
After some research I found the selected sprite is called the "editing target".  Which is a prop of the vm object!
The specific location where the vm.editingTarget value is changed is [here](https://github.com/LLK/scratch-vm/blob/d01f04bd3e1ad2596624dff24d6a30990a58a198/src/virtual-machine.js) in the function setEditingTarget()

### What causes setEditingTarget() to be called?

All the key functions are called from the [stage component](https://github.com/LLK/scratch-gui/blob/6300e4b819c3bf1a77b613517469d6e631604ab1/src/containers/stage.jsx)

There are two ways in which a sprite can be selected.

- By dragging it
- By double clicking it
Note: Clicking a sprite will not select it.

We should target both of these.

**Double clicking**

Double clicking is binded unsurprisingly to the onDoubleClick event of the canvas.
After double clicking the target id of the sprite at the mouse pos is found and then `vm.setEditingTarget` is called on it.
This event doesn't do anything other than select the sprite so we can fully disable the canvas event.

**Dragging**
Dragging is binded to a timeout function with a 400ms delay called from onMouseDown, or from onMouseMove if mouse is also down. Upon dragging the onStartDrag function is called. This calls `vm.startDrag(targetId`), which in turn calls `vm.setEditingTarget`. However this chain of events is disabled by changing the prop useEditorDragStyle to False.

### How to implement the addon

With our new knowledge of how selecting sprites work we have two options that I can think of.

1. On click of the stage canvas, wait till the editing target has been changed then change it back to the original using setEditingTarget()
   - To get access to the vm we can use the already implemented trap with  `const vm = addon.tab.traps.vm;`  
2. Unbind the double click event from canvas, and set the stage components useEditorDragStyle prop to False or modify the vm.startDrag function.
   - Unbinding the double click event is easy.
   - I have tried to figure out how to change the useEditorDragStyle prop but I don't know how you'd do it.
   - We could also rebind the vm.startDrag() function to one which doesn't have setEditingTarget()
3. We could wrap setEditingTarget() in a function which returns if the mouse is down.

What do you guys think is the best solution?

**Comment by apple502j** [comment] 2021-06-14 02:27
Any of them would work. Just make sure any updates that cause React to re-render something doesn't cause bugs.

**Comment by Joeclinton1** [comment] 2021-06-14 19:00
> Any of them would work. Just make sure any updates that cause React to re-render something doesn't cause bugs.

Alright, well I'll get to work making the addon and if it works, i'll submit the PR. 

As for the UI, for now i'll make a toggle switch which disables selecting sprites in the stage. If you guys want something else UI wise then please submit a PR with those changes. Unfortunately my time is limited so I'm going to try to do the minimal amount to achieve the desired result I need for my projects.

**Closed** 2021-07-05 15:33 UTC
Labels: new addon, scope: addon, type: enhancement
