### ISSUE TITLE
Ctrl-click to run scripts -> Double-click to run scripts

### ISSUE THREAD

**Issue by Secret-chest** [ScratchAddons/ScratchAddons#6198] opened 2023-06-12 18:10 UTC
### Why this would be helpful

It is easier than having to hold down a key, but prevents accidentally running scripts

### My suggestion

Add an option to the Ctrl-click to run scripts addon that makes it run scripts on double-click instead.

### Additional context

Scratch < 1.4 used this behaviour

**Comment by DNin01** [comment] 2023-06-12 18:22
Duplicate of #3958

**Closed** 2023-06-12 19:48 UTC
Labels: status: duplicate, type: enhancement, scope: addon, scope: user experience
