### ISSUE TITLE
Suggestion: Open in TurboWarp button in project page

### ISSUE THREAD

**Issue by Mr-Anonymous75** [ScratchAddons/ScratchAddons#2488] opened 2021-05-14 01:02 UTC
**Is your feature request related to a problem? Please describe.**
Every time I want to view a project in TurboWarp, I have to go into the address bar and replace "scratch.mit.edu/projects" with "turbowarp.org". And I use TurboWarp _a lot_.

**Describe the solution you'd like**
It would be great if there was a button on project pages that opened the project in TurboWarp. What I'm imagining is putting it next to the see inside button. 

**Describe alternatives you've considered**
Maybe put the button with the add to studio, copy link, and remix tree ones? Or make it a link in the notes like TurboWarp has for the open in Scratch link, or in the instructions. What about at the bottom of the page?

**Comment by apple502j** [comment] 2021-05-14 04:04
Duplicate of #164

**Closed by apple502j** 2021-05-14 04:04 UTC
Labels: status: needs triage, type: enhancement

**Comment by Mr-Anonymous75** [comment] 2021-05-14 04:48
> Duplicate of #164

Hmm... That issue gave me another idea - maybe, instead of putting a link to the TurboWarp website, embed the TurboWarp player, and put the advanced options available for TurboWarp somewhere on the project player itself! Let's see if I can learn some JS and make the feature myself 😉
