### ISSUE TITLE
Have projects move slower addon

### ISSUE THREAD

**Issue by Shluffy** [ScratchAddons/ScratchAddons#2778] opened 2021-06-14 18:01 UTC
### Is your request related to a problem? Please describe.

projects can only run at 30-240 fps using the 60fps addon. You can't make it run slower

### Describe the solution you'd like

A new addon like this

### Describe alternatives you've considered

remove the minimum for the 60fps addon

### Additional context

can this be done by just changing the min to 1, max to 29, and change the default?

**Comment by Genius398** [comment] 2021-06-15 06:21
Maybe duplicate of #2760 ?

**Comment by Shluffy** [comment] 2021-06-15 11:24
> Maybe duplicate of #2760 ?

maybe the slow-mo part. Although if this solution works we can solve that slow-mo part. I can't test it though

**Comment by Genius398** [comment] 2021-06-15 12:59
> > Maybe duplicate of #2760 ?
> 
> maybe the slow-mo part. Although if this solution works we can solve that slow-mo part. I can't test it though

The code/solution for reducing fps is correct. We just need someone to do it

**Comment by Shluffy** [comment] 2021-06-15 13:20
> > > Maybe duplicate of #2760 ?
> > 
> > 
> > maybe the slow-mo part. Although if this solution works we can solve that slow-mo part. I can't test it though
> 
> The code/solution for reducing fps is correct. We just need someone to do it

if it is just messing with the addon.json file I could do that. I can't test it though

**Comment by Genius398** [comment] 2021-06-15 13:20
yeah

**Comment by Genius398** [comment] 2021-06-15 13:21
but can you unpack the extension

**Comment by Shluffy** [comment] 2021-06-15 13:25
can you test [this](https://github.com/Shluffy/ScratchAddons/tree/blah
)

**Comment by Genius398** [comment] 2021-06-15 13:31
ok

**Comment by Genius398** [comment] 2021-06-15 14:09
It's great

**Comment by Genius398** [comment] 2021-06-15 14:10
Please put the `addon.json ` file into the 60fps folder

**Comment by Genius398** [comment] 2021-06-15 14:10
The testing is great

**Comment by Shluffy** [comment] 2021-06-15 14:37
@Genius398 I changed the name because it would be custom fps. I will open a pr and see if they want that to be changed

**Comment by Genius398** [comment] 2021-06-15 14:40
ok

**Comment by RedGuy12** [comment] 2021-06-15 14:58
Duplicate of #2760

**Closed by RedGuy12** 2021-06-15 14:58 UTC
Labels: scope: addon, type: enhancement

**Comment by Shluffy** [comment] 2021-06-15 15:05
@RedGuy12 not dupe. This is to change the manifest to allow custom fps, while that is to rename the addon

**Comment by RedGuy12** [comment] 2021-06-15 15:07
No, read the linked issue
________________________________

**Comment by Shluffy** [comment] 2021-06-15 15:08
ah, okay
