### ISSUE TITLE
Make the scratch logo in the editor direct to the homepage when i right click and open in new tab

### ISSUE THREAD

**Issue by 6543ozne** [ScratchAddons/ScratchAddons#4557] opened 2022-05-12 02:26 UTC
### Is your request related to a problem? Please describe.

When I want to go to the homepage from scratch, but want to continue editing my project I always try to right-click the Scratch logo in the left corner (in image below)

![image](https://user-images.githubusercontent.com/105403431/167979683-bc89a0c3-9bfa-4a33-8ce2-5dc67b4115e1.png)

 and click "open in new tab"

![image](https://user-images.githubusercontent.com/105403431/167979714-368b21d8-7ee1-4bc7-9571-5df88880348f.png)

but I always get directed to the image link of the logo, which is:
https://scratch.mit.edu/static/assets/1e9652bec24bcaacf5285be19746a750.svg

### Describe the solution you'd like

I think an addon that can redirect me to the homepage instead of the image link would be great

### Describe alternatives you've considered

None

**Comment by Chiroyce1** [comment] 2022-05-12 04:02
Pretty simple solution
```js
let newLink = document.createElement('a');
let logo = document.querySelector('img');

newLink.href = '/';

logo.parentElement.appendChild(newLink);
newLink.appendChild(logo);
```

**Comment by mxmou** [comment] 2022-05-12 04:50
Duplicate of #3737

**Closed by mxmou** 2022-05-12 04:50 UTC
Labels: status: duplicate, type: enhancement, new addon, scope: addon
