### ISSUE TITLE
April fools tab

### ISSUE THREAD

**Issue by jack-oid** [ScratchAddons/ScratchAddons#7033] opened 2024-01-02 17:30 UTC
### Why this would be helpful

this wouldn't really be helpful it would just be cool.

### How this addon works

be able to use the April fools features any time of the year.

### Possible alternatives

the cat block was an April fools feature and now is an addon.

### Additional context

credit to TheSTEAMist over on YouTube  for https://www.youtube.com/watch?v=jqDoH4iFc0I

**Comment by OneShot-Niko** [comment] 2024-01-02 18:01
> #Possible alternatives
the cat block was an April fools feature and now is an addon.

This is already the case though?

It's also listed as easter egg if you enter the konami code onto the fullscreen settings page, including dango rain.
I dont know how this is an alternstive since this is the case already.

**Comment by Joeclinton1** [comment] 2024-01-02 20:47
These are the kind of issues that should be closed quickly to avoid clutter

**Comment by BroJac5246** [comment] 2024-01-02 21:05
> These are the kind of issues that should be closed quickly to avoid clutter

All legitimate suggestions deserve to be discussed, this one included. If it's found that a suggestion shouldn't be added then it can be closed — otherwise we're just throwing away ideas that may benefit the extension.

**Comment by Samq64** [comment] 2024-01-02 21:39
Cat blocks and the semicolon glitch are already addons (See #1423) and the modes menu is a duplicate of #5129. I don't think there's an issue for the search Easter eggs though.

> So you're suggesting adding a separate tab for the Easter Egg addons? I'd like to see them become easier to find, but an entire tab might be too obvious.

I think this is for all the 2022 website April Fools jokes, at least that's what the video is for.

**Closed by Samq64** 2024-01-02 21:39 UTC
Labels: type: enhancement, new addon, scope: addon

**Comment by WorldLanguages** [comment] 2024-01-03 03:24
I think this is a duplicate of #5129
