### ISSUE TITLE
Adjustable editor fields

### ISSUE THREAD

**Issue by ilbailba** [ScratchAddons/ScratchAddons#4308] opened 2022-02-22 15:27 UTC
### Is your request related to a problem? Please describe.

As you know, **scratch editor** has **only two window layouts**. **large** player layout and **small** player layout. but **scratch** doesn't allow other layouts. therefore, users who want a special **editor layout** cannot **adjust** the sections in the editor as they wish.

### Describe the solution you'd like

this plugin allows to **adjust** the areas covered by all the _areas/panels_ on the **specified scratch page** with a **mouse drag** or with a **value entered**. In this way, different work areas can be created. **custom window layouts** can be exported or imported as a **json** file, _for example_.

### Describe alternatives you've considered

**mouse drag** => allows to adjust the area of ​​the windows. if the mouse hovers over an adjustable window _(like the cursor when hovering the mouse over the edges of windows in Windows)_ a cursor will appear. _(This can be changed to "enter value" if the window sizes are set on the scratch addons page, not on scratch's own page.)_

**revert to default** => **set** the windows footprint by **default**.

**add windows** _(maybe)_ => _(if it's possible)_ allows you to create multiple windows. actually all windows in the same category show the same things. only their positions and numbers are different. _(category eg = code area, player area, puppet area, costume area, etc.)_

**import/export settings** => allows you to _download_ and _import_ the **adjustments** made as a file, _for example_ the **scratch addons' import/export settings feature**.

### Additional context

If you've never used Unity, see how it's in the documentation [here](https://docs.unity3d.com/Manual/CustomizingYourWorkspace.html).

but do not misunderstand. I'm talking about a **simplified** version of the system in **Unity**. but it would be nice if a window system could be made like in **Unity**.

_Also, I am writing this post from my **phone**. that's why I couldn't benefit from the visuals and had to explain a bit superficially.
And sorry for my English._

**Thanks**.

**Comment by Samq64** [comment] 2022-02-22 15:43
Duplicate of #2217?

**Comment by ilbailba** [comment] 2022-02-22 15:47
> Duplicate of #2217?

umm.. yes. I guess it's the same. I'm sorry I didn't notice.

**Comment by mxmou** [comment] 2022-02-22 19:07
Duplicate of #2217

**Closed by mxmou** 2022-02-22 19:07 UTC
Labels: type: enhancement, new addon, scope: addon
