### ISSUE TITLE
"Please sign in" message showing even when signed in

### ISSUE THREAD

**Issue by richmailYT** [ScratchAddons/ScratchAddons#943] opened 2020-12-04 16:05 UTC
**Describe the bug**

it says to sigh in but im already sighed in

**To Reproduce**

yeah, i dont know, i think it happens only to some poeple
**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
<img width="1435" alt="Screen Shot 2020-12-04 at 11 04 13 AM" src="https://user-images.githubusercontent.com/73596193/101186047-99ac6e80-3620-11eb-8e2d-43b899f43192.png">

- OS: [macOS]
- Browser [chrome]
- Version [big sur 1.1, 87.0.4280.88]
<img width="385" alt="Screen Shot 2020-12-04 at 11 03 39 AM" src="https://user-images.githubusercontent.com/73596193/101186039-97e2ab00-3620-11eb-8528-845fb0847c79.png">

**Additional context**

**Comment by apple502j** [comment] 2020-12-04 16:09
Duplicate of #784

**Comment by WorldLanguages** [comment] 2020-12-04 17:31
> Duplicate of #784

Maybe.

**Comment by PhoenixAndStuf** [comment] 2020-12-04 20:42
Title error: Singh is supposed to be spelt Sign

**Comment by TheColaber** [comment] 2020-12-04 23:21
Try doing this @richmailYT:
> 1. Right click the scratch addons icon in the extensions bar
> 2. Click "manage extensions"
> 3. Make sure these all four are checked:
>    ![image](https://user-images.githubusercontent.com/17484114/99267611-eca1bb80-2802-11eb-97ca-fd95fb8cd2db.png)

**Comment by thecoder876** [comment] 2020-12-20 16:30
Hey, this has been fixed already.

**Closed** 2020-12-20 18:24 UTC
Labels: bug
