### ISSUE TITLE
[Question] What does this addon do?

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#258] opened 2020-09-10 16:20 UTC
What does the "Move your cat" addon do?
![image](https://user-images.githubusercontent.com/61319150/92761855-adb13e80-f357-11ea-87dc-2a4e5bb182c8.png)

**Comment by BoomerScratch** [comment] 2020-09-10 16:22
Duplicate of #149

**Closed by BoomerScratch** 2020-09-10 16:22 UTC
Labels: question
