### ISSUE TITLE
(More) Experimental Extra key options

### ISSUE THREAD

**Issue by SpryzenRYTonScratch** [ScratchAddons/ScratchAddons#6173] opened 2023-06-09 04:35 UTC
### Why this would be helpful

This would help have accessibility to other and more keys on the keyboard. Plus if you're going to make an add-on adding more key options on the key pressed block, why not add the rest of the keyboard (with multiple exceptions because it could be attached to a feature like for me, the f6-8 keys being the volume buttons but those are just another options) 

### How this addon works

Literally just adds more keys. I was thinking like the control (ctrl), function (fn), caps lock, print screen (prt sc), insert, delete (not the same as backspace). and tab keys would work out the best because I believe they're on most modern keyboards, and they're functions don't work during the scratch project (I mean it works out if you just tap it, shortcut commands are the real problem and the caps lock doesn't do much other than capiltilizating letters soooooo).

Two more things to note, I was also thinking about the page up and down (pg up and dn) and home keys, but I experimented and their functions work if the scratch project isn't in Fullscreen. 

### Possible alternatives

I don't believe that there is any add-on besides this, so I can't merge, and this is just adding to the extra key options add-on honestly.

### Additional context

There are multiple different keyboard layouts so there's bound to be some bugs and other stuff.

---------------------------------------------------------------------------------------------------------------------------------------------

I'm @SpryzenRYT on scratch.mit.edu, please CONSIDER (cough @BroJac5246) giving me a follow because I enjoy coding on Scratch frequently so come check what I'm doing 😄

**Comment by Secret-chest** [comment] 2023-06-09 04:47
The addon already adds all keys Scratch can support.

**Comment by CST1229** [comment] 2023-06-09 12:42
The modifier keys are all literally ignored by Scratch, you can't sense them. (However, [TurboWarp](https://turbowarp.org)'s version of the addon does have a "TurboWarp keys" option that adds those keys, as it can sense them).

**Comment by mxmou** [comment] 2023-06-09 12:50
Duplicate of #1802

**Closed by mxmou** 2023-06-09 12:50 UTC
Labels: type: enhancement, new addon, scope: addon
