### ISSUE TITLE
Themes don't apply when opening pages in new tab in Firefox

### ISSUE THREAD

**Issue by Lurux** [ScratchAddons/ScratchAddons#971] opened 2020-12-07 15:54 UTC
**Describe the bug**

Hi, I noticed the themes don't apply when opening a Scratch page in a new tab in Firefox (for example, using middle click).
*After further investigation, it appears this happens if the tab isn't selected when the page loads.*

**To Reproduce**

1. Activate a custom theme in the addon settings (for example, the "website dark theme" is very noticeable)
2. Go to any Scratch page (for example, the homepage)
3. Open a link in a new tab (for example, middle click the "my stuff" icon)
4. Wait a few seconds and switch to the other tab. The theme didn't apply.

**Expected behavior**

The page should be themed accordingly to the theme settings.

**Device (please complete the following information):**

- OS: Linux Mint :penguin:
- Browser: Firefox 83.0

**Comment by WorldLanguages** [comment] 2020-12-07 21:21
Thanks for the bug report, thankfully this has been reported already and fixed. It will arrive to the web stores soon (this week). Duplicate of #932

**Closed by WorldLanguages** 2020-12-07 21:21 UTC
Labels: bug

**Comment by Lurux** [comment] 2020-12-07 23:05
@WorldLanguages Oh sorry my bad - I tried to check for duplicates before opening the issue, but it seems like I didn't serach right :sweat_smile:
