### ISSUE TITLE
Fix Streched Studio Images

### ISSUE THREAD

**Issue by Mel0n7** [ScratchAddons/ScratchAddons#5497] opened 2022-12-28 04:35 UTC
### Why this would be helpful

When a studio image is shown anywhere but the actuall studio the image will be stretched out
![Screenshot 2022-12-27 233206](https://user-images.githubusercontent.com/99061680/209757759-1b197d2f-cf5d-4038-97f6-7ed1cf52cf60.png)
Using this addon would make it not streched out
![Screenshot 2022-12-27 233143](https://user-images.githubusercontent.com/99061680/209757851-985e3739-824c-40c8-b522-b6665a61a0e8.png)

### How this addon works

Change the width of the studio images to make it not streched out

**Comment by Secret-chest** [comment] 2022-12-28 06:24
The studio image aspect ratio is 17:10

**Comment by CST1229** [comment] 2022-12-28 08:23
> The studio image aspect ratio is 17:10

There is no one studio image aspect ratio (it's inconsistent) (however, the default studio image has an aspect ratio of 1.345291486:1).

**Comment by mxmou** [comment] 2022-12-28 13:13
People often upload images with a 4:3 aspect ratio as studio thumbnails, which doesn't good look anywhere on the site.

**Comment by Samq64** [comment] 2022-12-28 14:50
Related:  #3944

**Comment by WorldLanguages** [comment] 2022-12-28 16:17
> Related: #3944

Isn't this an exact duplicate of that?

**Comment by Samq64** [comment] 2022-12-28 16:21
> Isn't this an exact duplicate of that?
I guess you're right.

**Closed** 2022-12-28 16:21 UTC
Labels: type: enhancement, new addon, scope: addon
