### ISSUE TITLE
website dark mode & customizable colors addon sometimes doesn't load on the forums down page

### ISSUE THREAD

**Issue by ghost** [ScratchAddons/ScratchAddons#6887] opened 2023-11-25 14:33 UTC
### Description

This is a pretty minor bug that I don't seen an issue of, occasionally the custom website colors addon never loads on the forums outage page (requires a refresh until it does load sometime).
This doesn't occur while on the forums, but it does occur on the down page (If I recall correctly, [this should work if the forums come back](https://scratch.mit.edu/discuss/500))

### Steps to reproduce

1. Enable the website dark mode & customizable colors addon
2. Change the settings if you haven't to a highly noticable degree (eg. dark mode preset)
3. try to view the forums while they are down and refresh page if the addon loads, it'll fail to load occasionally.

### Demonstration(s) and additional context

Occurs on Vivaldi (95% chromium), Firefox & Edge.
![firefox](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/21a23734-0ba9-43e5-83ee-11b32b8eee45)
![vivaldi](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/6cb4ef65-53cb-46a0-9da1-25403cb4d540)
![edge](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/10aa58b6-fe0b-4a26-be1c-4af49e855577)
This is also not caused by other extensions either.

### Environment

Browser: Firefox 120.0 (32 bit)
Scratch Addons version: v1.35.1
Operating system: Windows 10

**Comment by mybearworld** [comment] 2023-11-25 14:40
Duplicate of #6675

**Closed as completed** 2023-11-25 14:41 UTC
Labels: type: bug, status: duplicate, scope: addon, scope: core
