### ISSUE TITLE
Shadow and transparency.

### ISSUE THREAD

**Issue by ApplikationFree** [ScratchAddons/ScratchAddons#2640] opened 2021-05-30 13:30 UTC
Scratch addons would be even cooler with a transparency and shadow management. This makes it possible to create transparent sprite without having gone through a vector editor. For shading the SVG format supports them, so it would have been possible to add them to the scratch editor. 
example of using shadow here : https://scratch.mit.edu/projects/516647789/
just touch the logo and a shadow appears.

**Comment by WorldLanguages** [comment] 2021-05-30 15:24
Duplicate of #2129

**Closed by WorldLanguages** 2021-05-30 15:24 UTC

**Comment by WorldLanguages** [comment] 2021-05-30 15:25
It's a duplicate (the transparency management part) unless shadows are a real SVG feature? (instead of other objects that take the place of shadows) Not sure how that is

**Comment by mxmou** [comment] 2021-05-30 19:47
@WorldLanguages Shadows can be made using SVG filters: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feDropShadow
