### ISSUE TITLE
Turbo mode text makes stage bigger and overlaps with zoom controls

### ISSUE THREAD

**Issue by fgclue** [ScratchAddons/ScratchAddons#5341] opened 2022-11-10 17:28 UTC
### Description

While trying to make a project, I tried starting it with turbo mode (to see if the clones show up instantly), and while doing that, I discovered that if you use the mouse position and clone counter plugin together, and a project with at least 1 clone if you open it in the editor with turbo mode on, the stage overlaps the zoom icon.

![image](https://user-images.githubusercontent.com/87581499/201163028-595a62fa-107b-4305-b4ec-b707f43ffa1c.png)

### Steps to reproduce

1. Turn on the mouse position and clone counter addon
2. Open a project with clones in the editor
3. Turn on turbo mode

### Demonstration(s) and additional context

![image](https://user-images.githubusercontent.com/87581499/201163864-1765495b-97e9-4071-a308-1353781d630b.png)

### Environment

Browser: 107.0.5304.92 64-bits
Scratch Addons version: 1.29.0
Operating system: Chrome OS

**Comment by mxmou** [comment] 2022-11-10 17:51
Duplicate of #3030

**Closed by mxmou** 2022-11-10 17:51 UTC
Labels: type: bug, status: needs triage
