### ISSUE TITLE
Change the color of the extension UI

### ISSUE THREAD

**Issue by Chameleon-Coder** [ScratchAddons/ScratchAddons#7370] opened 2024-04-21 23:23 UTC
### Why this would be helpful

This feature would be good for people who don't like Scratch Addons Orange. If they wanna make the extension popup use Scratch Haddocks Blue, let them!

### My suggestion

Add an option to change the UI color, with presets like Scratch Addons Orange and Scratch Haddocks Blue.

**Comment by DNin01** [comment] 2024-04-21 23:54
Well, we could think about adding themes to the settings page...

It's not a priority though - many people don't interact with the settings page or extension popup every day, and most people interact with Scratch much more than they do with Scratch Addons. But should it be added, it would make SA that much more fun.

**Comment by DNin01** [comment] 2024-04-21 23:56
High contrast themes could also be considered to improve the accessibility.

**Comment by BroJac5246** [comment] 2024-04-22 02:37
This could also suggest themes based on your Website dark mode and customizable colors settings.

**Comment by Samq64** [comment] 2024-04-24 00:36
Duplicate of #4617.

**Closed by Samq64** 2024-04-24 00:36 UTC
Labels: type: enhancement, scope: design, scope: webpages

**Comment by Secret-chest** [comment] 2024-04-24 04:57
> This could also suggest themes based on your Website dark mode and customizable colors settings.

Or just adopt them, having only presets doesn't make sense.
