### ISSUE TITLE
addon.messaging API

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#1671] opened 2021-02-26 16:10 UTC
Maybe not that exact name but this would allow communication through:
persistent <> userscripts
persistent <> popup

userscripts <> userscripts
popup <> popup
persistent <> persistent
userscripts <> popup

**Comment by RedGuy12** [comment] 2021-02-26 16:12
isn't this the global object?
________________________________

**Comment by WorldLanguages** [comment] 2021-02-26 18:32
> isn't this the global object?

Well, it could be if we used Comlink internally to sync them between contexts. But as of now, `global` is only shared between userscripts in the same tab, and all persistent scripts, separately.

**Comment by RedGuy12** [comment] 2021-03-01 15:40
is it's not the global object, then isn't it a duplicate of #1653?

**Comment by retronbv** [comment] 2021-03-01 15:41
This is a messaging API.... not a storage API

**Comment by WorldLanguages** [comment] 2021-03-01 15:43
This was originally #15 and then the concept of messaging got lost when it got moved into another issue again lol

**Comment by ErrorGamer2000** [comment] 2021-06-23 22:04
I have started work on it...

**Comment by apple502j** [comment] 2022-02-21 14:46
Closing.

Persistent scripts do not exist anymore, and it's unlikely someone has multiple popup pages open. The only real usage would be userscript to userscript or userscript to popup, but none of the current (and proposed) popups need this functionality. For userscripts just make a new file and ESM-export an event target or even a function itself.

**Closed by apple502j** 2022-02-21 14:46 UTC
Labels: type: enhancement, scope: addon api, scope: addon
