### ISSUE TITLE
"Ask () and wait" Text does not appear in dark modes

### ISSUE THREAD

**Issue by TriforceMayhem** [ScratchAddons/ScratchAddons#2507] opened 2021-05-16 03:02 UTC
**Describe the bug**

In the custom dark colors, for some reason setting the "Accent Background" to any somewhat dark color will hide any text in the "Ask () and wait" block.

**To Reproduce**

Change the "Accent Background" color in the custom dark colors section to anything around or below about #AAAAAA, and run a project that uses the "Ask () and wait" block, the text should be gone.

**Expected behavior**

The text above the answer box should be visible.

**Screenshots**

![image_2021-05-15_220029](https://user-images.githubusercontent.com/34255537/118384080-f72de980-b5c8-11eb-8aad-47174f9320c1.png)
![image_2021-05-15_220102](https://user-images.githubusercontent.com/34255537/118384093-0ad95000-b5c9-11eb-964d-5f72d6bc479c.png)

**Device (please complete the following information):**

- OS: Windows 10
- Browser: Opera GX
- Version: 75.0.3969.259

**Additional context**

Only started to occur after color customization became a thing.
Edit; The text actually appears to turn white instead of just disappearing, which blends in with the white question box.

**Comment by apple502j** [comment] 2021-05-16 05:48
Duplicate of #2433

**Closed by apple502j** 2021-05-16 05:48 UTC
Labels: status: needs triage, type: bug
