### ISSUE TITLE
Ability to revert back to old studios.

### ISSUE THREAD

**Issue by Scratchfangs** [ScratchAddons/ScratchAddons#2953] opened 2021-07-08 16:57 UTC
I made a suggestion for this, but it's unlikely that it would be added: https://scratch.mit.edu/discuss/topic/527643/

I'm asking for this to be added to SA, since imo, it looks like dog poop.

**Comment by Scratchfangs** [comment] 2021-07-08 16:57
I know some people may like it, but it's optional.

**Comment by TheColaber** [comment] 2021-07-08 16:58
Duplicate of #2947

**Comment by TheColaber** [comment] 2021-07-08 16:59
In the future, please use the issue template and read the notice at the top.

**Closed by TheColaber** 2021-07-08 16:59 UTC
Labels: new addon, scope: addon, type: enhancement
