### ISSUE TITLE
Hold the middle mouse button and drag to pan the costume editor canvas

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#7293] opened 2024-03-23 18:36 UTC
### Why this would be helpful

It's a faster way to move around.

### My suggestion

Pushing down on and holding the middle mouse button (the scroll wheel) and moving the mouse would drag the canvas in the costume editor. Like this:

https://github.com/ScratchAddons/ScratchAddons/assets/106490990/2a03c37b-d851-4207-864b-01162e3d5574

### Possible alternatives

A right mouse button drag could also be used, but watch out - Microsoft Edge's Mouse Gesture feature also responds to right click drags.

### Additional context

TurboWarp has this: https://github.com/TurboWarp/scratch-paint/blob/cf0ca19c959e07d41bee078c2a6eb4ecfcdf77ce/src/containers/scrollable-canvas.jsx#L50-L82

**Comment by Samq64** [comment] 2024-03-23 18:49
Duplicate of #5596

**Closed by Samq64** 2024-03-23 18:49 UTC
Labels: type: enhancement, new addon, scope: addon, scope: from turbowarp
