### ISSUE TITLE
enable fullscreen on cloud-games

### ISSUE THREAD

**Issue by Oren-Lindsey** [ScratchAddons/ScratchAddons#4448] opened 2022-03-30 14:54 UTC
### Is your request related to a problem? Please describe.
The messages popup has fullscreen. So i don't see any reason why there shouldn't be fullscreen for the cloud games popup.

### Describe the solution you'd like
Add fullscreen for the cloud games popup. All that would have to be added is the popout button, so it would be pretty easy. ~~I don't understand vue very much but I'll try to make a pr for this.~~ Made the pr: #4449

### Describe alternatives you've considered
Don't have fullscreen for the cloud games popup

### Additional context

<img width="398" alt="Screen Shot 2022-03-30 at 10 44 00 AM" src="https://user-images.githubusercontent.com/67929847/160862518-b66b5211-4b18-4ec2-bb51-e3f1d7be40ab.png">

**Comment by WorldLanguages** [comment] 2022-04-05 22:48
The PR is perfect but I'm not sure if the feature makes much sense.
Honestly, cloud-games as a whole is outdated and it's only in Scratch Addons because of griffpatch.

**Comment by Oren-Lindsey** [comment] 2022-04-05 23:08
I think it would be a lot better if you could change which studio it was, not just griffpatch's games. It is possible, all you have to do is add in a way to change [this](https://github.com/ScratchAddons/ScratchAddons/blob/b99a2ae3835a84636523c068e83743b83fb2aafa/popups/cloud-games/popup.js#L3) variable

**Comment by Chiroyce1** [comment] 2022-04-06 03:49
> I think it would be a lot better if you could change which studio it was, not just griffpatch's games. It is possible, all you have to do is add in a way to change [this](https://github.com/ScratchAddons/ScratchAddons/blob/b99a2ae3835a84636523c068e83743b83fb2aafa/popups/cloud-games/popup.js#L3) variable

The thing is, all of griffpatch's projects uses the same type of encoding, anyone else's project might have different methods to encode the username, so it'd be extremely difficult to adapt to this. One way is to just check if decoding the values with griffpatch's method produces a valid username, which means that it uses the same encoding. But all of that is just even more API requests and IMO isn't worth it..

**Comment by CST1229** [comment] 2022-04-06 04:15
> The thing is, all of griffpatch's projects uses the same type of encoding, anyone else's project might have different methods to encode the username, so it'd be extremely difficult to adapt to this. One way is to just check if decoding the values with griffpatch's method produces a valid username, which means that it uses the same encoding. But all of that is just even more API requests and IMO isn't worth it..

The cloud-games player list uses the last cloud variables updated, so it works with any project.

**Comment by Chiroyce1** [comment] 2022-04-06 06:27
> The cloud-games player list uses the cloud logs, so it works with any project.

Oops lol I forgot about that 😅

**Comment by mxmou** [comment] 2022-04-06 06:36
> Honestly, cloud-games as a whole is outdated and it's only in Scratch Addons because of griffpatch.

In its current state it would be more useful as a standalone website like scratchstats. As a Scratch Addons feature, it would be better if it was empty by default (no griffpatch projects) and allowed adding any project (not using a studio because studios are public).

**Comment by Oren-Lindsey** [comment] 2022-04-06 12:28
> > Honestly, cloud-games as a whole is outdated and it's only in Scratch Addons because of griffpatch.
> 
> In its current state it would be more useful as a standalone website like scratchstats. As a Scratch Addons feature, it would be better if it was empty by default (no griffpatch projects) and allowed adding any project (not using a studio because studios are public).

Even better, you could choose a studio OR add individual projects

**Comment by Secret-chest** [comment] 2022-04-06 15:53
> > > Honestly, cloud-games as a whole is outdated and it's only in Scratch Addons because of griffpatch.
> > 
> > In its current state it would be more useful as a standalone website like scratchstats. As a Scratch Addons feature, it would be better if it was empty by default (no griffpatch projects) and allowed adding any project (not using a studio because studios are public).
> 
> Even better, you could choose a studio OR add individual projects

Yes but there should be a warning next to the add studio button saying that the name must not contain "Scratch Addons"

**Comment by Oren-Lindsey** [comment] 2022-04-08 15:39
oops I accidentallly put in a commit that I didn't mean to. Please ignore [this commit](https://github.com/ScratchAddons/ScratchAddons/pull/4449/commits/91c45201f6829883d84b5cf2b10f8260b0d47080)

_Originally posted by @Oren-Lindsey in https://github.com/ScratchAddons/ScratchAddons/issues/4449#issuecomment-1093016110_

**Comment by Oren-Lindsey** [comment] 2022-04-08 15:41
> oops I accidentallly put in a commit that I didn't mean to. Please ignore [this commit](https://github.com/ScratchAddons/ScratchAddons/pull/4449/commits/91c45201f6829883d84b5cf2b10f8260b0d47080)
> 
> _Originally posted by @Oren-Lindsey in [#4449 (comment)](https://github.com/ScratchAddons/ScratchAddons/pull/4449#issuecomment-1093016110)_

ok I reverted it

**Comment by WorldLanguages** [comment] 2022-04-08 23:20
> As a Scratch Addons feature, it would be better if it was empty by default (no griffpatch projects)

I disagree, I think it should have at least 1 project by default so users can see what the addon does.

**Comment by Oren-Lindsey** [comment] 2022-04-09 14:03
> > As a Scratch Addons feature, it would be better if it was empty by default (no griffpatch projects)
> 
> I disagree, I think it should have at least 1 project by default so users can see what the addon does.

maybe a splash screen that explains how it works

**Comment by Norbiros** [comment] 2022-04-09 16:58
Or maybe presets like in row settings?
You can change/add/remove/load new values. We need to add some features to row setting, but I think it could work good.

**Comment by apple502j** [comment] 2022-04-12 16:19
Duplicate of #3368
Also this is getting kinda off-topic

**Closed by apple502j** 2022-04-12 16:19 UTC
Labels: type: enhancement, scope: webpages

**Comment by Oren-Lindsey** [comment] 2022-07-21 14:50
Ok now that you can add custom games can you do this as well
