### ISSUE TITLE
Sprite Folders addon wont work.

### ISSUE THREAD

**Issue by ItsGraphax** [ScratchAddons/ScratchAddons#7931] opened 2024-11-10 14:02 UTC
### Description

So I've made a project and manually put buttons//abc for every sprite as name to get them into folders, but on my laptop this feature dosent work properly.

### Steps to reproduce

Sorry I don't know how to reproduce

### Demonstration(s) and additional context

![image](https://github.com/user-attachments/assets/2fe177c2-7203-4aa8-99f1-85bfab9bbdcb)

### Environment

Browser: Chrome
Scratch Addons version: 1.39.1
Operating system: Windows 11

**Comment by Samq64** [comment] 2024-11-10 15:55
Duplicate of #7927. This has already been fixed, we're just waiting to the extension stores approve the update.

**Closed by Samq64** 2024-11-10 15:55 UTC
Labels: type: bug, status: needs triage
