### ISSUE TITLE
BUG - Text areas

### ISSUE THREAD

**Issue by Medericoder** [ScratchAddons/ScratchAddons#3964] opened 2021-12-20 19:11 UTC
https://user-images.githubusercontent.com/80577386/146819891-2d847b5d-2b78-4d22-a483-5c122fc9d568.mp4

**Comment by DogCatPuppyLover** [comment] 2021-12-20 20:20
Is this related to Scratch Addons? This looks like it's a bug in TurboWarp Desktop.

**Comment by Medericoder** [comment] 2021-12-20 20:40
> Is this related to Scratch Addons? This looks like it's a bug in TurboWarp Desktop.

![image](https://user-images.githubusercontent.com/80577386/146829898-4b820ada-e3dc-4084-9627-0c3fe085322e.png)

**Comment by Medericoder** [comment] 2021-12-20 20:43
> Is this related to Scratch Addons? This looks like it's a bug in TurboWarp Desktop.

When I post in "TurboWarp" issues, everybody say me "Nooooo it's Scratch Addons", and when I post in "Scratch Addons" issues, everybody say me "Nooooo it's TurboWarp", so please! Choose! 😩

**Comment by WorldLanguages** [comment] 2021-12-20 22:27
@Medericoder it probably is a scratch addons issue. Anyway, you could have tried to reproduce in vanilla Scratch with Scratch Addons and then it would be clear where the problem is

**Comment by Medericoder** [comment] 2021-12-21 09:32
@WorldLanguages Deal! Good idea!

**Comment by TheColaber** [comment] 2021-12-21 15:12
#3691

**Comment by mxmou** [comment] 2022-12-28 15:58
Fixed by #3961.

**Closed by mxmou** 2022-12-28 15:58 UTC
Labels: type: bug, scope: addon
