### ISSUE TITLE
editor-theme3 does not change some colors in block definition modal

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#5818] opened 2023-03-18 21:33 UTC
### Why this would be helpful

> The other day, I set "Scratch 3.0 improved version" in "Customize block color", and I like it very much. However, some colors remain as they were on the definition block creation screen, so I would like to ask for corrections.

(Google Translate)

### My suggestion

The user is expecting these 3 images to reflect their block color choice:

![image](https://user-images.githubusercontent.com/17484114/226141215-2ece3007-1d0f-468c-9bc4-81acce53681c.png)

### Possible alternatives

This could be considered a wontfix since these are images, not blocks

### Additional context

Feedback was received after v1.31.0 update

**Comment by mxmou** [comment] 2023-03-19 08:20
Duplicate of #4036

**Closed by mxmou** 2023-03-19 08:20 UTC
Labels: type: enhancement, source: feedback, scope: addon
