### ISSUE TITLE
"Addon" blocks category translation bug

### ISSUE THREAD

**Issue by Medericoder** [ScratchAddons/ScratchAddons#3397] opened 2021-08-30 09:36 UTC
All is explained in the title and in the video.

https://user-images.githubusercontent.com/80577386/131319239-b1e792f1-d06f-493f-87f9-a4f064115fdc.mov

**Comment by CST1229** [comment] 2021-08-30 09:58
Remember that the Addons block category name is a TurboWarp thing, and it's called Debugger in Scratch Addons.

**Comment by apple502j** [comment] 2021-08-30 10:52
Language changes apply after a reload (or in case of TurboWarp Desktop, closing and re-opening). Not frequent enough that we should add support, imo.

**Closed by apple502j** 2021-08-30 10:52 UTC
Labels: type: bug, status: needs triage

**Comment by apple502j** [comment] 2021-08-30 10:54
It seems like that block isn't translated yet, but that's not a bug either.
