### ISSUE TITLE
Addon Message-Passing API

### ISSUE THREAD

**Issue by ErrorGamer2000** [ScratchAddons/ScratchAddons#2864] opened 2021-06-23 19:48 UTC
As I have noted before, there is currently no way to communicate between a content script and a persistent script. I am currently building an API to allow this, modeled after chrome's message passing API.

The API will of course be accessible in both content scripts and persistent scripts.

Features implemented

- [x] `sendMessage`
```js
...
addon.messages.sendMessage({greeting: "hello"}, function(response) {
  console.log(response.farewell);
});
...
}
```
- Parameters
  - `response` - The response message from the listener.

- [x] `onMessage`
```js
function listener(message, sender, sendResponse) {
  if (message.greeting === "hello") {
    sendResponse({farewell: "goodbye"});
  }
}
addon.messages.onMessage.addListener(listener);

let hasListener = addon.messages.onMessage.hasListener(listener);
//true

addon.messages.onMessage.removeListener(listener);
```
- Parameters
  - `message`- The message sent with `sendMessage`
  - `sender` - An object describing the sender addon
    - `sender.id` and `sender.addonId` - The ID of the addon that sent the message. Addons should NOT receive messages from a different addon, so this is not really necessary.
    - `sender.url` - The url of the page the addon sent the message from.
  - `sendResponse` - Send a response to the sender addon.

- [ ] `connect`
```js
let port = addon.messages.connect({name: "knockknock"});
port.postMessage({joke: "Knock knock"});
port.onMessage.addListener(function(msg) {
  if (msg.question === "Who's there?")
    port.postMessage({answer: "Madame"});
  else if (msg.question === "Madame who?")
    port.postMessage({answer: "Madame... Bovary"});
});
```
- [ ] `onConnect`
```js
addon.messages.onConnect.addListener(function(port) {
  console.assert(port.name === "knockknock");
  port.onMessage.addListener(function(msg) {
    if (msg.joke === "Knock knock")
      port.postMessage({question: "Who's there?"});
    else if (msg.answer === "Madame")
      port.postMessage({question: "Madame who?"});
    else if (msg.answer === "Madame... Bovary")
      port.postMessage({question: "I don't get it."});
  });
});
```

Any comments? I will be publishing a branch on my fork when I finish working out the bugs in the first two features...

> Examples taken from the chrome developer docs and adapted.

**Comment by ErrorGamer2000** [comment] 2021-06-23 19:49
Should it be `addon.messaging` instead of `addon.messages`?

**Comment by RedGuy12** [comment] 2021-06-23 21:16
duplicate of #1671

**Closed by RedGuy12** 2021-06-23 21:16 UTC
Labels: status: needs triage
