### ISSUE TITLE
Project Information Panel in Scratch

### ISSUE THREAD

**Issue by games-coder** [ScratchAddons/ScratchAddons#7022] opened 2023-12-31 08:45 UTC
### Why this would be helpful

In order to view project details in Scratch, we initially need to delve into it, but this process can be excessively lengthy. Instead, if there were a project information panel, we could swiftly achieve this by simply hovering the mouse cursor over it.

### How this addon works

You can run it by hovering your mouse cursor over a project.

### Possible alternatives

Tampermonkey code:
[message (1).txt](https://github.com/ScratchAddons/ScratchAddons/files/13800649/message.1.txt)

### Additional context

![Ekran görüntüsü 2023-12-31 113227](https://github.com/ScratchAddons/ScratchAddons/assets/133994118/11761291-8cd9-4b79-9da3-744d29e7cbf2)

**Comment by mybearworld** [comment] 2023-12-31 08:54
Related: #2271

**Comment by WorldLanguages** [comment] 2024-01-03 03:07
I'm going to say this is a duplicate of #2271 but which focuses on projects.



> Tampermonkey code:
> [message (1).txt](https://github.com/ScratchAddons/ScratchAddons/files/13800649/message.1.txt)

Cool, thanks for sharing! You may want to take a look at PR #4089.

**Closed by WorldLanguages** 2024-01-03 03:07 UTC
Labels: type: enhancement, new addon, scope: addon
