### ISSUE TITLE
Change addon settings from userscript

### ISSUE THREAD

**Issue by iqnite** [ScratchAddons/ScratchAddons#5943] opened 2023-04-18 11:12 UTC
### Why this would be helpful

Addon developers could add buttons and menu options to quickly toggle settings from the Scratch page, without having to open the settings. Examples are "Disable auto-saving" and the dark costume editor background setting of "Editor dark mode".

### My suggestion

Extend the API to change addon settings from the userscript.
If this is already implemented, then please add the toggles!

**Comment by Samq64** [comment] 2023-04-18 13:02
Duplicate of #1950

**Comment by Samq64** [comment] 2023-04-18 13:03
There's also a PR open already: #5460

**Closed** 2023-04-18 14:36 UTC
Labels: status: duplicate, type: enhancement, scope: addon api, status: needs triage
