### ISSUE TITLE
custom blocks custom colors

### ISSUE THREAD

**Issue by piw-piw** [ScratchAddons/ScratchAddons#4508] opened 2022-04-16 22:07 UTC
Set custom color for any custom block.
Something like that:
![image](https://user-images.githubusercontent.com/76477070/163692555-ec2ac9ee-a668-4a90-8616-957d08aab3f7.png)
! In addon with block comments:
![image](https://user-images.githubusercontent.com/76477070/163692763-14ee0ed3-7cbd-44b4-a809-353f817f45b0.png)

**Comment by RedGuy12** [comment] 2022-04-16 23:56
Duplicate of #1706

**Closed by RedGuy12** 2022-04-16 23:56 UTC
Labels: type: enhancement, new addon, scope: addon

**Comment by WorldLanguages** [comment] 2022-04-17 14:24
@RedGuy12 Are you sure it's the exact same suggestion?

**Comment by piw-piw** [comment] 2022-05-09 19:18
It's custom color, not category color.
