### ISSUE TITLE
Dark mode messes up reporting a class profile

### ISSUE THREAD

**Issue by Oren-Lindsey** [ScratchAddons/ScratchAddons#4245] opened 2022-02-08 23:43 UTC
### Description
If you have the customizable dark mode addon on (these pictures are on the default settings), and try to report a class, it will not make the report form dark, but it will make the text dark.

### Reproduction steps

1. Go to a class page like [this](https://scratch.mit.edu/classes/523115/)
2. Turn on Website dark mode and customizable colors
3. Click the report button

### Expected behavior
The background-color of the div should be the same as other elements of the page

### Actual behavior
It's not

### Screenshots
<img width="960" alt="Screen Shot 2022-02-08 at 6 36 54 PM" src="https://user-images.githubusercontent.com/67929847/153094224-3274ea9e-ff59-430b-9c0c-07a134b545a7.png">
<img width="1424" alt="Screen Shot 2022-02-08 at 6 33 54 PM" src="https://user-images.githubusercontent.com/67929847/153094234-4646d11a-4208-492b-90fc-157114a71639.png">

### Environment
Browser: Chrome 97
SA Version: 1.24.1
OS: MacOS

- Browser: 
- Scratch Addons version: 
- Operating system: 

### Additional context
I tested and adding `background-color: ...;` to the style of the div and the textarea fixes it, so it should be simple to fix this

**Comment by Dhuls-Scratch** [comment] 2022-02-09 04:50
Duplicate of #4113

**Closed** 2022-02-09 08:05 UTC
Labels: type: bug, scope: addon
