### ISSUE TITLE
Preview Project extension messes around with tabbed instructions extension

### ISSUE THREAD

**Issue by thatkusari** [ScratchAddons/ScratchAddons#6851] opened 2023-11-10 09:01 UTC
### Description

When I'm on the homepage of my project, I have 2 extensions, the tabbed instructions and credits and the other one that previews it. When i flip the switch 2 times it should go back to the tabbed instructions.
What actually happens is when you flip the toggle 2 times it doesn't retain the tabbed instructions and it goes back to plain boring old non-tabbed instructions.

### Steps to reproduce

1. Enable Projects notes tabs and Preview project instructions and notes
2. go to a project you own
3. flip the toggle from the Preview instructions extension 2 times
4. it undoes the project notes tabs extension

### Demonstration(s) and additional context

https://github.com/ScratchAddons/ScratchAddons/assets/121749159/676b4e82-f5d2-44d4-ac0d-401ccbd85011

### Environment

Browser: Opera GX, Version: IDK
Scratch Addons version: 1.35.1
Operating system: Windows 11

**Comment by mxmou** [comment] 2023-11-10 13:48
Duplicate of #6698

**Closed by mxmou** 2023-11-10 13:48 UTC
Labels: type: bug, scope: addon
