### ISSUE TITLE
Suggestions for what a TurboWarp addon could look like

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#588] opened 2020-10-29 02:43 UTC
**Describe the new addon**

Removes Scratch's native project player and replaces it with the TurboWarp player.
(Not sure if this is rejected or not, no topic mentioning the idea had a definitive answer.)

If that is not feasible, bring back the addon that injected a link to TurboWarp, or just outright redirect all project page visits to TurboWarp.

**Link to the new addon**

[TurboWarp's GitHub repository](https://github.com/TurboWarp)

**Comment by YOYITsM3M8** [comment] 2020-10-29 11:14
I tried to do this. It got rejected

**Comment by WorldLanguages** [comment] 2020-10-29 13:59
Yeah, it's hard to replace the player properly. Many simple JS approaches had flaws.

**Comment by Explosion-Scratch** [comment] 2020-10-29 17:10
Yeah. Maybe 'open in Turbowarp/forkphorus' would be better.

**Comment by MiniCoder11** [comment] 2020-10-30 05:04
I have a script that adds a native-looking "Open in TurboWarp" button to the editor and project pages from my own addon-loader extension I happened to be developing before this one popped up. It does use `.insertBefore()` though and I'm not sure that it is up to standards.

**Comment by YOYITsM3M8** [comment] 2020-10-30 10:08
i converted my personal userscript
![Screenshot 2020-10-30 at 6 07 11 AM](https://user-images.githubusercontent.com/49005044/97692526-43bf3680-1a76-11eb-870b-8db1b58d8157.png)

**Comment by MiniCoder11** [comment] 2020-11-02 22:20
You could also link the green flag button to refresh the TurboWarp embed so that it always stay current whenever you edit the project. The only downfall to this approach is that on slower internet connections or with larger projects, you may have to wait a few seconds before playing the project.

**Comment by WorldLanguages** [comment] 2020-11-02 22:33
> You could also link the green flag button to refresh the TurboWarp embed so that it always stay current whenever you edit the project.

If, and only if, the project just saved

**Comment by MiniCoder11** [comment] 2020-11-03 18:20
> If, and only if, the project just saved

Yes, that would be quite important. I could throw together something that replaces the player and factors in whether any modifiers are enabled (turbo mode, 60 FPS mode, etc.)

Another important thing: we would always have to load the project with the "TurboWarp Stuck Checker" because we don't want the stage to crash the entire editor if some error that Scratch normally skips over is present in the scripts (although I just tried a few of the things that used to crash TurboWarp without the "stuck checker" and it seems to run unaffected by most of those errors now).

**Comment by Hans5958** [comment] 2021-02-21 04:05
Duplicate of #164, we'll see.

**Closed by Hans5958** 2021-02-21 04:05 UTC
Labels: new addon, scope: addon, type: enhancement

**Comment by ScoutBearYT** [comment] 2023-12-18 05:36
I'd like there to be an option to _**Skew**_ stuff in the costume panel!!!
![skew-demo](https://github.com/ScratchAddons/ScratchAddons/assets/108796775/0cf8d920-3b5d-4c7e-b9e8-5cc49a670ebd)

**Comment by WorldLanguages** [comment] 2023-12-20 20:09
@ScoutBearYT Please be patient. It might take some time for TurboWarp to obtain all up-to-date addons.
