### ISSUE TITLE
"More links" creates a link for any word with ellipsis next to it

### ISSUE THREAD

**Issue by insanityplays** [ScratchAddons/ScratchAddons#1443] opened 2021-01-28 10:13 UTC
This bug can only be experienced by turning on "More links"

How to reproduce:

1. Go to any page with commenting (not the forums)
2. Create a comment with an ellipsis next to it.
4. You can see that it creates a link, even though ii's not supposed to.

OS: Google Chrome OS Version 87.0.4280.152 (Official Build) (64-bit)
Browser: Google Chrome Version 87.0.4280.152

**Comment by apple502j** [comment] 2021-01-28 10:29
Duplicate of #1415

**Closed by apple502j** 2021-01-28 10:29 UTC
Labels: status: duplicate, type: bug

**Comment by WorldLanguages** [comment] 2021-01-28 16:28
@apple502j Be nicer with someone's first issue :P
