### ISSUE TITLE
`editor-theme3`: Change monitor color to corresponding category color

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#6689] opened 2023-09-23 20:30 UTC
### Why this would be helpful

Monitor colors reflect the colors of their category. However, `editor-theme3` doesn't change this. 

### My suggestion

Change the monitor colors with `editor-theme3`.

### Additional context

Specifically, the high contrast mode changes the colors. `editor-theme3` also disables this high contrast mode, which means with `editor-theme3` active, there is no way to switch these colors. So, it would be good if `editor-theme3` handled this.

![Some monitors with Scratch's regular colors](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/9e6c1727-a5c9-4832-bdbc-82d2ef43fc56)
![Some monitors with Scratch's high contrast colors](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/2f8b4a7c-42f9-41de-bc38-f6f52f230c66)

**Comment by Samq64** [comment] 2023-09-23 20:52
Duplicate of #4033

**Closed by Samq64** 2023-09-23 20:52 UTC
Labels: type: enhancement, status: needs triage

**Comment by WorldLanguages** [comment] 2023-09-24 18:14
> Specifically, the high contrast mode changes the colors. `editor-theme3` also disables this high contrast mode, which means with `editor-theme3` active, there is no way to switch these colors.

Related: this is very similar to the situation of the zoom controls. #6175
