### ISSUE TITLE
zooming in and then out in the editor makes auto-hide zoom controls break

### ISSUE THREAD

**Issue by jeffalo** [ScratchAddons/ScratchAddons#2248] opened 2021-04-21 15:37 UTC
**Describe the bug**

zooming in and then out in the editor makes auto-hidden zoom controls impossible to use

**To Reproduce**

(enable the zoom thing to these settings)
![image](https://user-images.githubusercontent.com/40470736/115581899-b7752a00-a2c8-11eb-95ad-5427a64ec601.png)

1. Open a project edit page
2. Open the scratch full screen mode
3. Use browser zoom to zoom in
4. Reset browser zoom to 100%
5. Exit full screen mode
6. Try to hover over zoom controls

**Expected behavior**

Auto-hide zoom controls option should handle browser zoom better

**Screenshots**

https://user-images.githubusercontent.com/40470736/115581338-36b62e00-a2c8-11eb-944f-67f55f51c8b8.mp4

**Device (please complete the following information):**

- OS: window 10 20h2
- Browser chrome 89.0.4389.128 
- Version master latest a0126e3023fe4d37ac99982c686bb1b910ce3b52

**Comment by RedGuy12** [comment] 2021-04-21 15:39
Can’t repro on edge.

**Comment by GarboMuffin** [comment] 2021-04-21 15:58
I believe this is caused by a Scratch bug where the workspace doesn't resize properly. Turn off Scratch Addons and do the same thing and the controls will still be in the wrong spot.

![image](https://user-images.githubusercontent.com/33787854/115584240-3f8b0d80-a290-11eb-8125-28a38cc2a5b9.png)

The addon could probably do some dirty things to work around this

**Comment by jeffalo** [comment] 2021-04-21 17:55
can we PR to fix this upstream?

**Comment by RedGuy12** [comment] 2021-04-23 02:15
> can we PR to fix this upstream?

You mean in the LLK repo?

**Comment by WorldLanguages** [comment] 2021-04-23 12:48
> You mean in the LLK repo?

Yeah, technically not "upstream" but he meant that

**Comment by mxmou** [comment] 2022-12-27 13:40
Closing because this is a Scratch bug.

**Closed by mxmou** 2022-12-27 13:40 UTC
Labels: type: bug, priority: 3, scope: addon

**Comment by WorldLanguages** [comment] 2022-12-27 23:13
@mxmou Even tho the root cause is a vanilla Scratch bug, isn't our addon preventing the user to zoom in/out completely? The vanilla Scratch bug is not our fault, but it still lets you zoom in/out.
Not sure if I understand this 2 year old issue properly.

**Comment by mxmou** [comment] 2022-12-28 08:04
> @mxmou Even tho the root cause is a vanilla Scratch bug, isn't our addon preventing the user to zoom in/out completely? The vanilla Scratch bug is not our fault, but vanilla Scratch still lets you zoom in/out. Not sure if I understand this 2 year old issue properly.

The addon isn't preventing the user from using the zoom buttons. The buttons are in the wrong place and the addon doesn't change that.
