### ISSUE TITLE
convert dark-www to presets

### ISSUE THREAD

**Issue by FunctionalMetatable** [ScratchAddons/ScratchAddons#2252] opened 2021-04-21 18:22 UTC
**Is your feature request related to a problem? Please describe.**

As `editor-dark-mode` has now converted to presets, wouldn't it be better if that this addon was presets as well?

**Describe the solution you'd like**

convert dark-www to presets

**Describe alternatives you've considered**

`null`

**Comment by TheColaber** [comment] 2021-04-21 18:24
Related: #645 (but not dupe?)

**Comment by mxmou** [comment] 2021-04-21 18:29
#645 is very similar to this. Closing as duplicate.

**Closed by mxmou** 2021-04-21 18:29 UTC
Labels: scope: addon, type: enhancement

**Comment by TheColaber** [comment] 2021-04-21 18:30
Duplicate of #645
