### ISSUE TITLE
Copy to backpack on Scratchblocks in the forums addon

### ISSUE THREAD

**Issue by UniqueName12345** [ScratchAddons/ScratchAddons#5332] opened 2022-11-07 05:33 UTC
### Why this would be helpful/solve a problem

The "Copy to Backpack" button was on the scratch forums, but it got removed for no reason. It was useful not just to get hacked blocks (although, that's a major part of it), but for making long scripts easier.

### What this addon does

This addon adds a button to copy the following script to the backpack.

**Comment by mxmou** [comment] 2022-11-07 12:13
Duplicate of #3225

**Closed by mxmou** 2022-11-07 12:13 UTC
Labels: status: duplicate, type: enhancement, new addon, scope: addon
