### ISSUE TITLE
Global custom blocks

### ISSUE THREAD

**Issue by sfederici** [ScratchAddons/ScratchAddons#3268] opened 2021-08-09 18:33 UTC
### Is your request related to a problem? Please describe.

Custom blocks in Scratch 3 are pretty useless if you have many sprites that could potentially use them (unless you already have a perfect idea of what blocks must be part of the definition) indeed every time you want/need to update a custom block definition: 
- you have to update the custom block definition in all the sprites that use it
- if you drag the new block definition to another sprite where the custom block is already defined, you get two custom blocks with the same name but the definition used in the sprite is always the old one, regardless of custom block you use

### Describe the solution you'd like

1. Allow the user to define both local and global custom blocks
2. when you update the definition of a global block, this is automatically updated in all sprites 
3. dragging a custom block to another sprite has no effect if the custom blocks already exists in the destination sprite

### Describe alternatives you've considered

None

### Additional context

None

**Comment by TheColaber** [comment] 2021-08-09 18:35
Duplicate of #1267

**Closed by TheColaber** 2021-08-09 18:35 UTC
Labels: type: enhancement, new addon, scope: addon

**Comment by sfederici** [comment] 2021-08-09 19:01
I'm not sure that this is a duplicate of #1267. The referred proposal was a bit weird. Mine is in line with advances Scratch clones likes Snap https://snap.berkeley.edu/snap/snap.html. Why has this proposal of mine been closed?

**Comment by TheColaber** [comment] 2021-08-09 19:06
The only difference between this issue and #1267 is that this issue directly states that the custom block being global/local as a setting. Other than that, the only way to globalize blocks is the way you said above:
> when you update the definition of a global block, this is automatically updated in all sprites

it has to automatically add the custom block to all sprites, and update the custom block for all sprites too. I'm not sure if there is any other way to do that.

**Comment by sfederici** [comment] 2021-08-09 19:09
Why is updating a custom block definition in all sprites that share the same global custom block considered unacceptable?

**Comment by TheColaber** [comment] 2021-08-09 19:14
I meant that #1267 states the same way you want to globalize custom blocks. I didn't mean it was unaccepted.

**Comment by sfederici** [comment] 2021-08-10 08:14
As I like mine better :-) can you add a reference to this alternative proposal in #1267?

**Comment by TheColaber** [comment] 2021-08-15 00:31
You can mention it in the issue, so whoever decides to implement it will see it.
