### ISSUE TITLE
mediarecorder "record" button doesn't always show

### ISSUE THREAD

**Issue by Unkrown6YT** [ScratchAddons/ScratchAddons#6295] opened 2023-06-28 17:18 UTC
### Description

When I have Project Video recorder enabled, If I disable Block Count and I refresh, Record button is gone

### Steps to reproduce

1. Disable Block Count when you have Project video recorder
2. Refresh the page
3. Done

### Environment

Browser: Chrome
Scratch Addons version: v1.33.1
Operating system: Windows 11

**Comment by medlans** [comment] 2023-06-28 18:33
Is block count the one in the editor or the project page?

**Comment by WorldLanguages** [comment] 2023-06-28 18:35
Probably the editor one

**Comment by WorldLanguages** [comment] 2023-07-02 15:53
I'm not really sure if this was a bug of its own, or if it was caused by the "hide tutorials button" addon

**Comment by WorldLanguages** [comment] 2023-07-02 22:51
Can't reproduce in Chromium, master branch. I'll assume this was fixed by #6323

Tested these four cases:
- mediarecorder enabled, hide tutorials disabled, block count disabled
- mediarecorder enabled, hide tutorials enabled, block count disabled
- mediarecorder enabled, hide tutorials disabled, block count enabled
- mediarecorder enabled, hide tutorials enabled, block count enabled

**Closed by WorldLanguages** 2023-07-02 22:51 UTC
Labels: type: bug, scope: addon
