### ISSUE TITLE
Make "Followers" bar on Curators tab in the Scratch galleries

### ISSUE THREAD

**Issue by US-Systems** [ScratchAddons/ScratchAddons#2966] opened 2021-07-09 17:07 UTC
Hi everyone! I'm the Scratcher @US-Systems and I'm asking you to make a Scratch Addons that shows the "Followers" bar on Curators tab in Scratch galleries. This is an important function of the galleries recently and unfairly removed by Scratch Team. Can you please remake this function on Scratch Addons? Thanks!

**Comment by CST1229** [comment] 2021-07-09 17:08
"galleries" is a 1.x term. Did you mean studios?

**Comment by apple502j** [comment] 2021-07-09 17:08
Duplicate of #2940

**Closed by apple502j** 2021-07-09 17:08 UTC
Labels: status: needs triage, type: enhancement
