### ISSUE TITLE
Suggested Addon: Make Variable Local/Global

### ISSUE THREAD

**Issue by MiniCoder11** [ScratchAddons/ScratchAddons#1774] opened 2021-03-10 07:25 UTC
**Describe the new addon**

Even with the DevTools addon for swapping every variable in a sprite, it is a hassle to convert large batches of variables from a script you've just dragged from your backpack to being local ones if they aren't needed throughout the rest of your project. I'd like to suggest that an addon be made to make a global variable local or vice versa.

An option could be added under the "Swap variables in sprite" option when you right click on a variable which, when clicked, would switch the variable to being either local or global depending on what state it is already in.

The way this addon could work:
1. Start with a variable (let's call this one "x").
2. When it is selected to be swapped, append "--variable_swap--" to the name to prevent two variables having the same name and conflicting.
3. Create a new variable with the old variables name ("x") and make it either local or global depending on the status of the "x--variable_swap--" variable.
4. Use existing code for the swap addon to swap all "x--variable_swap--" variables to the new "x" ones.
5. Copy the old "x--variable_swap--" variable's value to the new "x" variable.
5. Delete the "x--variable_swap--" variable.

The only two problems that could take place would be if there was a local variable in another sprite with the same name as the local one you are currently trying to make global, or if another sprite has scripts that use a public variable you are trying to make local. Both of these problems can be avoided by running a check before attempting to set the variables and if one of these issues occurs, show a warning saying that there are conflicts and so the variable cannot be changed.

I'd like to hear everyone's thoughts about this suggestion.

**Link to the new addon**

No link available.

**Comment by TheColaber** [comment] 2021-03-10 12:56
Duplicate of #1469

**Closed by TheColaber** 2021-03-10 12:56 UTC
Labels: new addon, scope: addon, type: enhancement
