### ISSUE TITLE
Ability to hide "Projects Loved by Scratchers I'm Following"

### ISSUE THREAD

**Issue by Scratchfangs** [ScratchAddons/ScratchAddons#1981] opened 2021-03-28 12:34 UTC
A few of the people I am following are liking/favoriting very cringy/stupid things and it's being added to "Projects Loved by Scratchers I'm Following". Why not just unfollow them? Well, I did F4F a few months ago and they are still very active. They visit my profile often so they will know when I unfollow them. What if there was a new addon to disable "Projects Loved by Scratchers I'm Following"?

**Comment by mxmou** [comment] 2021-03-28 14:15
Maybe hide any row on the front page?

**Comment by RedGuy12** [comment] 2021-03-28 20:54
> Maybe hide any row on the front page?

see #1758 for that

**Comment by WorldLanguages** [comment] 2021-03-28 22:57
Duplicate of #1758

**Closed by WorldLanguages** 2021-03-28 22:57 UTC
Labels: new addon, scope: addon, type: enhancement
