### ISSUE TITLE
Transparent Variable and Different Ask Style

### ISSUE THREAD

**Issue by ghost** [ScratchAddons/ScratchAddons#1680] opened 2021-02-27 16:09 UTC
**Transparent Variable and different ask style**

I am requesting you guys to create a addon that will change the variable font and style without that orange markings which is annoying sometimes. Also the ask can also change the theme to the choosen style or font.

**Comment by RedGuy12** [comment] 2021-02-27 16:13
What styles would be available?
________________________________

**Comment by Barthdry** [comment] 2021-02-27 16:23
Like changing the font to different fonts. So that they can blend into the project.

**Comment by RedGuy12** [comment] 2021-02-27 16:24
Duplicate of #1646

**Comment by Barthdry** [comment] 2021-02-27 16:30
Ok so it is a duplicate then i'll close it

**Comment by mxmou** [comment] 2021-02-27 16:55
Not a duplicate, #1646 is about changing the font of the whole website. This seems to be about an addon that would let you customize the orange color of variables.

**Comment by WorldLanguages** [comment] 2021-02-27 17:03
@mxmou You could add this to preset based "editor dark mode"

**Comment by mxmou** [comment] 2021-02-27 17:49
> @mxmou You could add this to preset based "editor dark mode"

I don't want to add too many customizable colors.
![Too many color settings](https://user-images.githubusercontent.com/51849865/109395376-52d2ca00-792c-11eb-8d2c-7d540ebca9ba.png)

**Comment by WorldLanguages** [comment] 2021-02-27 18:53
Lol that's a lot

**Comment by Explosion-Scratch** [comment] 2021-02-27 18:56
~~50 shades of grey~~

**Closed** 2024-08-18 20:36 UTC
Labels: type: enhancement, new addon, scope: addon
