### ISSUE TITLE
guys i need help again

### ISSUE THREAD

**Issue by the-gunned-noob** [ScratchAddons/ScratchAddons#6228] opened 2023-06-18 17:17 UTC
ok now this is ridiculous first yesterday i couldnt discard comments and couldnt make custom blocks NOW I CANT SHARE and yes i turned off scratch addons to check if it was bc scratch and nope, its bc scratch addons, i swear to god if they keep making addons automatically turn on that ruin stuff im gonna freak

also this time ima check my emails
![bruha](https://github.com/ScratchAddons/ScratchAddons/assets/133821602/790e498b-fe6b-432a-83d5-90e1fd15506d)
![bruhb](https://github.com/ScratchAddons/ScratchAddons/assets/133821602/e33a7688-50d2-42de-a7d4-39bcf54a33c5)
![bruhc](https://github.com/ScratchAddons/ScratchAddons/assets/133821602/3f2e686e-a9cc-46fc-9c7f-f434665ac5b7)

**Comment by medlans** [comment] 2023-06-18 17:25
Update to v1.33.1 when possible, the bugs are fixed now and it was caused by the Confirmations/Customizable block colors extensions. They're working on a fix for the latter so the color changes can still be used.

**Comment by CST1229** [comment] 2023-06-18 17:58
Duplicates of #6219 and #6212. Those were already fixed, please update to 1.33.1.

**Closed by CST1229** 2023-06-18 17:58 UTC
Labels: status: needs triage

**Comment by WorldLanguages** [comment] 2023-06-18 18:12
> if they keep making addons automatically turn on that ruin stuff im gonna freak

Note that we didn't enable any addons automatically. We accidentally broke some features which you opted-into in the past. Sorry!
