### ISSUE TITLE
translate the add-on to different language

### ISSUE THREAD

**Issue by scratchusernamemrtbts** [ScratchAddons/ScratchAddons#739] opened 2020-11-12 12:43 UTC
**Is your feature request related to a problem? Please describe.**
when my friend use my computer to play scratch and he can't understand some English I have to translate it to him
**Describe the solution you'd like**
let someone translate the add-on
**Describe alternatives you've considered**
make a webpage to call for translator in ScratchAddons.com website
**Additional context**
I can help translate to Thai

**Comment by Hans5958** [comment] 2020-11-12 12:49
Duplicate of #480. On the other hand, it's quite a surprise that @apple502j just went up and try to implement it.

**Closed by Hans5958** 2020-11-12 12:49 UTC
Labels: enhancement
