### ISSUE TITLE
Customizable Block Shape: Flat hat blocks

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#7560] opened 2024-06-20 04:25 UTC
#5879 started implementing this, but it got messed up.
The idea is something like this:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/72760579/8f690076-9a0f-4a41-a57e-6f59c23b592a)

**Comment by OneShot-Niko** [comment] 2024-06-20 09:47
Duplicate of #5886

**Comment by TheColaber** [comment] 2024-06-20 11:09
true, they weren't linked, didnt see that

**Closed** 2024-06-20 11:09 UTC
Labels: type: enhancement, scope: addon
