### ISSUE TITLE
Collapsing code blocks

### ISSUE THREAD

**Issue by ProgrammingParadox** [ScratchAddons/ScratchAddons#4394] opened 2022-03-12 00:43 UTC
### Is your request related to a problem? Please describe.
My scratch code is very hard to navigate.

### Describe the solution you'd like
I'd love it if there was a way to collapse code blocks in an if or forever statement like one would do in a favorite code editor.

**Comment by mxmou** [comment] 2022-03-12 15:11
Duplicate of #1199

**Closed by mxmou** 2022-03-12 15:11 UTC
Labels: type: enhancement, new addon, scope: addon
