### ISSUE TITLE
Default to turbowarp player

### ISSUE THREAD

**Issue by dormieriancitizen** [ScratchAddons/ScratchAddons#6072] opened 2023-05-18 18:41 UTC
### Why this would be helpful

Sometimes, especially on slow WiFi, it's somewhat annoying to load the project in, finally, then have to click of the turbowarp player to make it run with any semblance of speed. 

### My suggestion

It would be nice to have a setting in the TurboWarp button, replace player, to load turbowarp by default.

**Comment by Samq64** [comment] 2023-05-18 19:04
Duplicate of #5480

**Closed by Samq64** 2023-05-18 19:04 UTC
Labels: type: enhancement, status: needs triage
