### ISSUE TITLE
disable-stage-drag-select: cannot drag sprites set to draggable

### ISSUE THREAD

**Issue by Secret-chest** [ScratchAddons/ScratchAddons#6896] opened 2023-11-27 09:12 UTC
### Description

Using `set drag mode [draggable v]` on a sprite makes it draggable even in the project page. However, in the editor, when this addon is enabled, even these sprites aren't draggable

### Steps to reproduce

1. Enable "Non-draggable sprites in editor"
2. Open a project
3. Make a sprite
4. Set the sprite to draggable using `set drag mode [draggable v]` on it
5. Try to drag the sprite in the stage or in editor fullscreen
6. It isn't draggable

### Environment

Browser: Chromium 112 (because it is ungoogled)
Scratch Addons version: stable 1.35.1
Operating system: Linux Mint 21.2, Kernel 5.15, Cinnamon 5.8.4

**Comment by WorldLanguages** [comment] 2023-11-27 15:01
Cannot reproduce the bug

**Comment by WorldLanguages** [comment] 2023-11-27 15:46
@Secret-chest Can you share the status of your addon's settings? (this addon has one boolean setting)

**Comment by DNin01** [comment] 2023-11-27 20:39
I can't seem to reproduce the problem you described. Note that your browser is 7 major versions behind the latest Chrome release, Chrome 119, just in case that would cause any issues. Could you provide some more details to help us diagnose?
- Any chance there are errors in the console?
- What addons have you enabled, or does this still happen with _only_ `disable-stage-drag-select` enabled?
- Are there specific projects this is or is not happening on?

**Comment by Secret-chest** [comment] 2023-11-27 20:46
NOT while it is stopped!

**Comment by DNin01** [comment] 2023-11-27 23:14
> NOT while it is stopped!

So you are able to drag sprites while the project is stopped, but not while it's running?

Have you checked that there are any errors in the console when this happens?

**Comment by DNin01** [comment] 2023-11-29 19:15
@Secret-chest Would really appreciate some more information as described above. Errors in console, addons you have enabled, etc.

**Comment by WorldLanguages** [comment] 2023-11-29 23:35
Yeah, send that setting file. Pastebin is your friend.

**Comment by DNin01** [comment] 2023-11-29 23:45
Or, feel free to share it in a [secret gist](https://gist.github.com) if you would prefer GitHub technology.

If you just want to share your enabled addons, I also made a [script](https://gist.github.com/DNin01/37f9f81404dcdfffd22aefabd9dd4e84) that makes it easy.

**Comment by Secret-chest** [comment] 2023-11-30 13:44
Sure I will, when I have the time.

**Comment by DNin01** [comment] 2024-12-02 00:08
Closing until further information is provided.

**Closed by DNin01** 2024-12-02 00:08 UTC
Labels: type: bug, status: needs info, scope: addon
