### ISSUE TITLE
add opacity/transparency to color selector

### ISSUE THREAD

**Issue by Marc92020** [ScratchAddons/ScratchAddons#3556] opened 2021-09-25 21:49 UTC
### Is your request related to a problem? Please describe.
i have to go to turbowarp whenever i wanna make stuff transparent

### Describe the solution you'd like

a opacity option on the color menu
### Describe alternatives you've considered
none

### Additional context
if your confused on what i mean:
![Screenshot 2021-09-25 5 47 38 PM](https://user-images.githubusercontent.com/75702334/134786766-31061254-8028-4783-b134-b0db7324b3a5.png)

**Comment by WorldLanguages** [comment] 2021-09-25 23:21
Duplicate of #2129

**Closed by WorldLanguages** 2021-09-25 23:21 UTC
Labels: type: enhancement, new addon, scope: addon
