### ISSUE TITLE
Don't Autoplay Projects

### ISSUE THREAD

**Issue by Mbrick2** [ScratchAddons/ScratchAddons#3588] opened 2021-10-01 04:09 UTC
### Is your request related to a problem? Please describe.
When you open a large project on scratch it can become **_very_** glitchy on some computers and you cant view the notes and credits and the addons do not load until later.

### Describe the solution you'd like
An addon that when you open a project page the project doesn't automatically start loading. 

### Describe alternatives you've considered

None

### Additional context

![Scratch](https://user-images.githubusercontent.com/90691415/135563841-c29f1bf3-9f1d-4fe4-9d47-45cbef22e3e6.png)

Bad mockup by me

**Comment by Dhuls-Scratch** [comment] 2021-10-01 04:10
Duplicate of #3566

**Closed** 2021-10-01 05:11 UTC
Labels: type: enhancement, new addon, scope: addon
