### ISSUE TITLE
"Welcome to Scratch" message does not show up

### ISSUE THREAD

**Issue by KadenDavis** [ScratchAddons/ScratchAddons#6659] opened 2023-09-16 00:31 UTC
### Description

When you receive a message from the Scratch team, you will get a change of the Scratch Addons extension logo, but you won't get a notification and it won't show up on Scratch Addons. 
It was the "Welcome to Scratch" message. 

### Steps to reproduce

1.Create a new account
2. Wait for welcome message
3. Click on Scratch Addons, nothing will appear

### Environment

Browser: 
Scratch Addons version: 
Operating system:

**Comment by WorldLanguages** [comment] 2023-09-16 02:57
Hi! Note that the "welcome to Scratch" message is not a "message from the Scratch Team", it's just a type of message we don't support.

**Comment by WorldLanguages** [comment] 2023-09-16 02:58
Duplicate of https://github.com/ScratchAddons/ScratchAddons/issues/2853#issuecomment-865967460

**Closed by WorldLanguages** 2023-09-16 02:57 UTC
Labels: type: bug, status: duplicate, scope: addon
