### ISSUE TITLE
Comment previews

### ISSUE THREAD

**Issue by Mr-Anonymous75** [ScratchAddons/ScratchAddons#3436] opened 2021-09-06 04:42 UTC
## Problem

Quite often, I need to know how my comment will look after being posted. 

I don't know if `https://scratch.mit.edu/` will be highlighted as a link or `https://scratch.mit.edu/.`. (the latter has a period at it's end)
I don't know if `@QuexizT` will be used as a mention or `@QuexizT,`.

This is very annoying.

## Ideal solution

There should be a preview shown for your comment.
It would also be great if there was a toggle to show linebreaks, if the user had the insert linebreaks addon turned on.

## Alternative solutions

Just show the preview.

**Comment by Secret-chest** [comment] 2021-09-06 05:00
1. Don't use
# for issues.
## use this instead
2. Who would need that? There are only like scratch.mit.edu links, emojis and mentions.

**Comment by Secret-chest** [comment] 2021-09-06 05:01
### or much better this

**Comment by Mr-Anonymous75** [comment] 2021-09-06 05:46
> 1. Don't use
> 
> # for issues.
> ## use this instead

Well, fine, I guess.

> ### or much better this

Nope, I'm not doing that.

**Comment by apple502j** [comment] 2021-09-06 10:48
Duplicate of #1677

**Closed by apple502j** 2021-09-06 10:48 UTC
Labels: type: enhancement, new addon, scope: addon
