### ISSUE TITLE
[FIX 1.9.2]: Scratch Addons broken in Spanish and other languages

### ISSUE THREAD

**Issue by Exlectruz** [ScratchAddons/ScratchAddons#1575] opened 2021-02-14 21:19 UTC
**Describe the bug**

It used to work wonderfully. All the addons fit together, and I never had a problem until now.

Literally, ALL addons don't work. Tried going to the SA settings area to disable and re-enable addons, but it won't let me go. It just stays in a gray color as you will see in the screenshot.

**To Reproduce:**

None. Just started today without a reason.

**Expected behavior**

As I said, everything worked perfectly before. When I realized that the addons were not working and the configuration page was broken, I looked at the SA version to see if they had changed anything:

![image](https://user-images.githubusercontent.com/79061511/107889206-b7833300-6eef-11eb-962a-951eaacebaae.png)

The last time I saw the scratch addons version (I look at it several times a day) it was at version **1.9.1**. I'm sure that version corrupted Scratch Addons in my browser. Please try to make a patch by fixing this, SA was completely useless to me...

**Screenshots**

![image](https://user-images.githubusercontent.com/79061511/107888879-fadca200-6eed-11eb-8d10-33a84ee0a138.png)
![image](https://user-images.githubusercontent.com/79061511/107888943-7fc7bb80-6eee-11eb-88b5-b6b3a42c0121.png)
![image](https://user-images.githubusercontent.com/79061511/107889398-12695a00-6ef1-11eb-96f3-e53f84004ae5.png)

**Device:**

- OS: [Lenovo Windows 10]
- Browser [Brave]
- Version 
![image](https://user-images.githubusercontent.com/79061511/107888895-2b244080-6eee-11eb-87a0-9a77d278c8c7.png)

**Additional context**

Sad :(

**Comment by CuriousG2** [comment] 2021-02-14 22:28
I can't reproduce this on brave.  Have you tried reinstalling the extension?

**Comment by WorldLanguages** [comment] 2021-02-14 23:16
@Exlectruz Looks like a bug with the localization system, can only be reproduced with certain browser languages (happens with Spanish but not Portuguese). We'll release a new version with a fix soon. For now you can change your browser's UI to English and it should work again. Saludos desde Argentina :)

**Comment by WorldLanguages** [comment] 2021-02-15 00:37
Fixed by v1.9.3 commit 2670ba5daa4aa58d7591d13575cde9c1b1496270
Should be in extension stores by tomorrow
Only Spanish was affected

**Closed by WorldLanguages** 2021-02-15 00:37 UTC
Labels: scope: core, type: bug

**Comment by Exlectruz** [comment] 2021-02-15 00:50
> @Exlectruz Looks like a bug with the localization system, can only be reproduced with certain browser languages (happens with Spanish but not Portuguese). We'll release a new version with a fix soon. For now you can change your browser's UI to English and it should work again. Saludos desde Argentina :)

Gracias :D
