### ISSUE TITLE
Block Isn't Showing Under the Background

### ISSUE THREAD

**Issue by 22yeetz22** [ScratchAddons/ScratchAddons#2139] opened 2021-04-12 21:25 UTC
**Describe the bug**

The block will not show under the black background of the sprites.

**To Reproduce**

1. Set the mode to Experimental Dark
2. Go to the editor.
3. Make 2 sprites.
4. Drag a random block into the workspace.
5. Try to drag the block into another sprite.
6. See the error.

**Expected behavior**

The block to show over the black background.

**Screenshots**

![Screenshot 2021-04-12 162248 glitch](https://user-images.githubusercontent.com/74276537/114464461-68821300-9bab-11eb-84ea-5c5be36c0342.png)

**Device (please complete the following information):**

- Browser: Google Chrom

**Additional context**

**Comment by TheColaber** [comment] 2021-04-12 21:27
Can repro but not from Editor Dark... finding addon...

**Comment by mxmou** [comment] 2021-04-13 06:05
Duplicate of #2015

**Closed by mxmou** 2021-04-13 06:05 UTC
Labels: scope: addon, type: bug
