### ISSUE TITLE
Subfolders

### ISSUE THREAD

**Issue by InTheProcess** [ScratchAddons/ScratchAddons#5568] opened 2023-01-08 00:16 UTC
### Why this would be helpful

This would be helpful because it will allow for better organization of projects.

### My suggestion

I want the ability to add subfolders with the addon "Sprite folders".

**Comment by UtterDonkey** [comment] 2023-01-08 08:21
Could you please give an example project where this would be useful? (I just want to see if there are any projects that actually have that many sprites that this would be needed.)

**Comment by WorldLanguages** [comment] 2023-01-08 16:13
Folders inside folders is probably excessive

**Comment by CST1229** [comment] 2023-01-08 16:20
> Folders inside folders is probably excessive

It might not be so excessive if you have many sprites and many folders (that could have further grouping).

**Comment by InTheProcess** [comment] 2023-01-08 17:10
I feel like having the option is important especially for large projects.  For example:  let's say I have multiple scenes in my game.  In the game scene, I have many entities, items, and buttons.  This will be hard to navigate.

Having the option to have sub folders allows for further organization.  Even if it is excessive, at least it is there for people who really need it.

**Comment by illogicalapple** [comment] 2023-01-11 02:17
> Could you please give an example project where this would be useful? (I just want to see if there are any projects that actually have that many sprites that this would be needed.)

You would never really "need" it, but it's always nice to be able to organize things better.

**Comment by InTheProcess** [comment] 2023-01-12 00:39
Before you look into this project, just let me outline a few things of why this is a very important change:
1. It promotes good programming practices
2. Gives users better flexibility to design the project the way they want
3. Makes it easier for people to remix
4. Significantly better organization
5. Makes projects easier to manage and regulate

Allowing for subfolders I believe will be a change for the better.
Here is the link to download the Scratch project example:
[https://file.io/mw79ZmNA9jEY](url)

This project is just a demo to get the point across, nothing more; this is a bare bones project.  Keep in mind inexperienced Scratchers will probably use more sprites for a similar game due to their lack of knowledge.

**Comment by CST1229** [comment] 2023-01-17 15:16
Also, I think this is probably the most suggested rejected suggestion (that isn't incompatible).

**Comment by WorldLanguages** [comment] 2023-01-17 19:59
I would say this is impractical, not rejected.
The addon code would get more complicated and the UI would need to consider folders within folders.

**Comment by InTheProcess** [comment] 2023-01-17 20:03
Perhaps if this feature was implemented, a file hierarchy would be a good solution to the UI design part of the addon.

**Comment by InTheProcess** [comment] 2023-01-18 02:45
> I would say this is impractical, not rejected.
> 
> The addon code would get more complicated and the UI would need to consider folders within folders.

Could you explain to me the impracticality of this matter?

**Comment by WorldLanguages** [comment] 2023-01-18 18:30
By impractical, I just mean it will need a bit more effort than the average new feature, because there are many details that need to be polished before shipping the feature.

**Comment by InTheProcess** [comment] 2023-01-18 19:06
> By impractical, I just mean it will need a bit more effort than the average new feature, because there are many details that need to be polished before shipping the feature.

I see what you mean.  I totally agree this will take a lot of work.  Maybe implementing the feature would be easy, but polishing and designing it to the point where it can be published is going to be hard.

**Comment by InTheProcess** [comment] 2023-01-29 20:45
So are we doing this?> I feel like having the option is important especially for large projects.  For example:  let's say I have multiple scenes in my game.  In the game scene, I have many entities, items, and buttons.  This will be hard to navigate.
> 
> Having the option to have sub folders allows for further organization.  Even if it is excessive, at least it is there for people who really need it.

**Comment by Tacodiva** [comment] 2023-12-04 22:39
This issue is a duplicate of #3648

**Comment by WorldLanguages** [comment] 2023-12-05 16:20
Duplicate of #3648

**Closed by WorldLanguages** 2023-12-05 16:20 UTC
Labels: type: enhancement, scope: addon
