### ISSUE TITLE
TurboWarp mode

### ISSUE THREAD

**Issue by iqnite** [ScratchAddons/ScratchAddons#2713] opened 2021-06-08 13:19 UTC
### Is your request related to a problem? Please describe.

Some Scratch projects are slow and laggy

### Describe the solution you'd like

TurboWarp is a Scratch mod that compiles projects to JavaScript to make them run really fast. It also has extra features, like "Infinite clones" and "High Quality Pen". A feature that 

### Describe alternatives you've considered

I could load the projects in TurboWarp.org, but it would be better if there was one directly in Scratch

### Additional context

[Link to TurboWarp](http://TurboWarp.org)

**Comment by Shluffy** [comment] 2021-06-08 13:29
Turbowarp is not affiliated with scratch. Try @scratchaddons.

**Comment by Shluffy** [comment] 2021-06-08 13:29
duplicate of #164. Please use the search bar to try to find duplicates. And #2682 will solve this

**Comment by WorldLanguages** [comment] 2021-06-08 15:21
Duplicate of #164

**Closed by WorldLanguages** 2021-06-08 15:21 UTC
Labels: new addon, scope: addon, type: enhancement
