### ISSUE TITLE
A precision value for the "integer" setting

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#6021] opened 2023-05-07 12:24 UTC
### Why this would be helpful

For #6020, this would allow customizing the increasing with numbers less than one.

### My suggestion

My suggestion would be to have a setting for `integer` called `step`, where the creator could enter any number, not just integers, e.g. also a step of `.1`. This wouldn't be an integer anymore, but that's not that bad (it could be renamed to `number` if it's really necessary).

### Possible alternatives

- We could also add a new type entirely called `float`, but a step setting would be more versatile.

**Comment by mxmou** [comment] 2023-05-07 12:33
Duplicate of #3860

**Comment by mybearworld** [comment] 2023-05-07 12:59
I'm not sure - WorldLanguages said in https://github.com/ScratchAddons/ScratchAddons/pull/3880#issuecomment-986080723:

> I now notice I never said it explicitly, but we'd still want to allow non multiples as valid values. The stepping would simply be for up/down controls.

Which wouldn't work with having decimals also work.

**Comment by WorldLanguages** [comment] 2023-05-09 18:37
> For #6020, this would allow customizing the increasing with numbers less than one.

That's a specific case where it would make sense to support decimals, I believe. In most other cases, we can "scale" the settings to an integer but not in this case.

**Closed** 2023-10-12 05:27 UTC
Labels: type: enhancement, scope: addon.json, scope: webpages
