### ISSUE TITLE
Changing the padding to 2.0 blocks and back left-aligns text in rounded reporters and input boxes.

### ISSUE THREAD

**Issue by DroneBetter** [ScratchAddons/ScratchAddons#2115] opened 2021-04-09 11:12 UTC
This only seems to happen if the text is thinner than the box/reporter's minimum width, when it should be centre-aligned, otherwise it behaves as usual.

**Screenshot**
<img width="796" alt="image" src="https://user-images.githubusercontent.com/58664547/114171606-095e9d00-9924-11eb-8656-5d0e353609ec.png">
The m variables are fine, but the v ones and 2's are left-aligned.

**Comment by mxmou** [comment] 2021-04-09 11:23
Duplicate of #2033

**Closed by mxmou** 2021-04-09 11:23 UTC
Labels: scope: addon, status: duplicate, type: bug
