### ISSUE TITLE
Animated featured project thumbnails go into error

### ISSUE THREAD

**Issue by PhoenixAndStuf** [ScratchAddons/ScratchAddons#864] opened 2020-11-26 22:52 UTC
When your on a profile, animated thumbnails for featured projects bug out. (Currently unsure which addon is causing this)

The thumbnail turns into a "Oops! Our server is 'scratch' ing it's head"

@SerifAnimates' and @ScruffyAnimates' profiles have animated featured projects.

1. Go to one of the profiles listed above
2. Let the thumbnail play for a bit
3. See the error (only if the addon that's causing the problem is enabled. Currently investigating which one is causing it.)

It should say "Oops! Our server is 'scratch' ing it's head" where the animated thumbnail is supposed to be.

Unfortunately I can't get any screenshots (maybe I'll update this report)

- OS: Windows 10
- Browser: Microsoft Edge
- Version: Don't know, as I said, I might update this report later)

Notes: Originally thought this had to do with the 2.0 to 3.0 addon, though it's probably something else. If anyone could tell me, that would be great.

Also, after some thinking, it probably **has to be an unshared-featured project.**

Thanks for your help guys, so far I'm loving the extension and can't wait for new features!!

**Comment by GrahamSH-LLK** [comment] 2020-11-26 23:21
This shouldn't happen. 2.0 to 3.0 is entirely css, it couldn't have an impact on errors like that.

**Comment by PhoenixAndStuf** [comment] 2020-11-26 23:42
> This shouldn't happen. 2.0 to 3.0 is entirely css, it couldn't have an impact on errors like that.

I may be wrong about 2.0 to 3.0 being the cause. I might investigate later and send screenshots.(tomorrow is my estimate)

**Comment by TheColaber** [comment] 2020-11-27 01:00
> The thumbnail turns into a "Oops! Our server is 'scratch' ing it's head"

Hmm, I'm guessing this is the live featured project addon... Do you have that enabled? Also, what addons do you have enabled. Send Screenshots and I'm guessing maybe one of the setting requests for the extension were disabled.

**Comment by PhoenixAndStuf** [comment] 2020-11-27 02:39
> > The thumbnail turns into a "Oops! Our server is 'scratch' ing it's head"
> 
> Hmm, I'm guessing this is the live featured project addon... Do you have that enabled? Also, what addons do you have enabled. Send Screenshots and I'm guessing maybe one of the setting requests for the extension were disabled.

Screenshots should be in tomorrow! Sorry for the delay, it's Thanksgiving and all of that.

**Comment by mxmou** [comment] 2020-11-27 10:23
This is caused by the live featured project addon. Should it be changed to not load the project if it's unshared?

**Comment by Hans5958** [comment] 2020-11-27 10:26
Sorry for the late, late reply. This has been fixed on #707, and the fix will be launched on the next version.

**Closed by Hans5958** 2020-11-27 10:26 UTC
Labels: bug
