### ISSUE TITLE
[Scratch Notifier] Manager Notification bug

### ISSUE THREAD

**Issue by YOYITsM3M8** [ScratchAddons/ScratchAddons#712] opened 2020-11-10 18:34 UTC
**Describe the bug**
Promoted to manager in Studio says "Unknown message content"
**To Reproduce**
Get a notification for promoted to manager

**Expected behavior**

__ promoted you to manager in ___

**Screenshots**
N/A
**Device (please complete the following information):**

- OS: chrome os
- Browser: chrome
- Version newest?

**Additional context**
N/A

**Comment by mxmou** [comment] 2020-11-10 18:47
Duplicate of #676

**Closed by mxmou** 2020-11-10 18:47 UTC
