### ISSUE TITLE
Forum Search - Scratchblocks error

### ISSUE THREAD

**Issue by FunctionalMetatable** [ScratchAddons/ScratchAddons#1962] opened 2021-03-24 17:54 UTC
**Describe the bug**

When you search something in the forum search, and you're on a topic with scratchblocks on it, the scratchblocks on the page (not the search part) become invalidated and the scratchblocks text get squished together.

**To Reproduce**

1. Go to a random topic which has scratchblocks, for example, i used [this](https://scratch.mit.edu/discuss/topic/271015/).
2. Search something on the **Forum Search**
3. Scroll down to see the scratchblocks on the **forum posts** and you see invalidated blocks, but the scratchblocks in the search query is fine.
**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/67440879/112360178-ef894d00-8cc9-11eb-8c08-6639cecbd62b.png)
![image](https://user-images.githubusercontent.com/67440879/112360263-05970d80-8cca-11eb-80a4-2e753232ce23.png)

**Device (please complete the following information):**

- OS: Windows 10
- Browser Microsoft Edge Chromium
- Version 89.0.774.57

**Comment by GrahamSH-LLK** [comment] 2021-03-25 13:11
This is caused by Forum Search running scratchblocks a second time, and scratchblocks breaks when running over pre-generated blocks.

**Comment by FunctionalMetatable** [comment] 2021-03-25 16:19
Before searching, can't you guys remove the scratchblocks and again add them in before you add the scratchblocks script?

**Comment by GrahamSH-LLK** [comment] 2021-03-25 16:34
No, but this can still be fixed. If it was that easy, we'd have a 2.0 -> 3.0 scratchblocks addon.

**Comment by CST1229** [comment] 2021-07-19 17:52
I think this could be fixed by iterating through each scratchblocks element in the search results via `document.querySelectorAll(".forum-search-list pre.blocks")` before calling `scratchblocks.renderMatching()` then setting their class to something else like `blocks-search`. Then just call `scratchblocks.renderMatching()` on that instead of `pre.blocks`.

**Comment by ErrorGamer2000** [comment] 2021-07-19 19:40
> I think this could be fixed by iterating through each scratchblocks element in the search results via document.querySelectorAll(".forum-search-list pre.blocks") before calling scratchblocks.renderMatching() then setting their class to something else like blocks-search.

You know what, that might work, if the divs are renamed BEFORE the `renderMatching` function is called...I should look into that.

**Comment by CST1229** [comment] 2021-07-19 19:43
> > I think this could be fixed by iterating through each scratchblocks element in the search results via document.querySelectorAll(".forum-search-list pre.blocks") before calling scratchblocks.renderMatching() then setting their class to something else like blocks-search.
> 
> You know what, that might work, if the divs are renamed BEFORE the `renderMatching` function is called...I should look into that.

This issue's creator already made a PR and it just uses `.forum-search-list pre.blocks` in `scratchblocks.renderMatching()` instead of renaming anything.

**Comment by ErrorGamer2000** [comment] 2021-07-19 22:18
I meant for a scratchblocks 2.0 => 3.0 addon.

**Closed** 2021-07-21 21:08 UTC
Labels: scope: addon, type: bug

**Comment by GrahamSH-LLK** [comment] 2021-07-22 14:45
> > I think this could be fixed by iterating through each scratchblocks element in the search results via document.querySelectorAll(".forum-search-list pre.blocks") before calling scratchblocks.renderMatching() then setting their class to something else like blocks-search.
> 
> You know what, that might work, if the divs are renamed BEFORE the `renderMatching` function is called...I should look into that.

It's not that simple, consistently running before scratchblocks is run is really hard

**Comment by FunctionalMetatable** [comment] 2021-07-22 14:54
> > > I think this could be fixed by iterating through each scratchblocks element in the search results via document.querySelectorAll(".forum-search-list pre.blocks") before calling scratchblocks.renderMatching() then setting their class to something else like blocks-search.
> > 
> > 
> > You know what, that might work, if the divs are renamed BEFORE the `renderMatching` function is called...I should look into that.
> 
> It's not that simple, consistently running before scratchblocks is run is really hard

i got it once working, but it changed the manifest.json so i didnt pr (i dont want to do big big changes)

**Comment by RedGuy12** [comment] 2021-07-22 15:39
Same



________________________________
