### ISSUE TITLE
Cat Blocks

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#610] opened 2020-10-30 22:09 UTC
**Describe the new addon**

Brings back the awesomeness of the hat blocks cat blocks...

**Link to the new addon**

I don't have this yet, but this is helpful: https://llk.github.io/scratch-gui/hotfix/totally-normal-2020/ I think all we need to do is switch all the SVGs, check for new hat blocks created, and add the tiny things when you hover over the block...

**Comment by lisa-wolfgang** [comment] 2020-10-31 17:59
> One of the easter egg addons could be loading the April Fools' 2020 editor.

That's nearly impossible. Reproducing it? That's feasible. I've already coded something that brings back the semicolon glitch.

_Originally posted by @GrahamSH-LLK in https://github.com/ScratchAddons/ScratchAddons/issues/508#issuecomment-718158874_

**Comment by TheColaber** [comment] 2020-10-31 18:10
Yeah, I kinda tried and kinda just gave up... I'll try another time. I know it's not impossible tho.

**Comment by Hans5958** [comment] 2020-11-03 00:40
Duplicate of #143

**Closed by Hans5958** 2020-11-03 00:40 UTC
Labels: new addon
