### ISSUE TITLE
find-bar sometimes doesn't find messages in other sprites

### ISSUE THREAD

**Issue by sfederici** [ScratchAddons/ScratchAddons#3584] opened 2021-09-29 19:35 UTC
Scratch 2 had a cool function that allowed to find which sprite(s) was sending/receiving a given message. Instead the Search function in ScratchAddons allows you to find what scripts are sending/receiving a given message in the same sprite, but doesn't allow you to find which sprites/scripts are sending/receiving a message if they are not in the same sprite.

**Comment by Samq64** [comment] 2021-11-24 22:17
This was probbably fixed by #2474.

**Comment by sfederici** [comment] 2021-11-25 07:58
I can confirm that this bug has not been fixed. Just try the first example I have submitted, that is if I look for "event fine intro" in sprite "Titolo" (first sprite) I get 1/1, but the event is received by the sprite "Aereo" too (fourth sprite). The addon still works as described, that is in the wrong way.
     Il mercoledì 24 novembre 2021, 23:18:10 CET, Samq64 ***@***.***> ha scritto:  
 
 


This was probbably fixed by #2474.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Samq64** [comment] 2021-11-25 12:27
I found this issue by searching `no:label` and forgot to look at the date.

**Comment by sfederici** [comment] 2021-11-25 13:31
> The link leads to a 404 page.

Sorry, I had forgot to share the project. Try again now

**Comment by Samq64** [comment] 2021-11-25 13:53
> > The link leads to a 404 page.
> 
> Sorry, I had forgot to share the project. Try again now

I can reproduce. It's strange, because I've never had that problem before.

**Closed** 2024-06-27 16:50 UTC
Labels: type: bug, scope: addon
