### ISSUE TITLE
Hide Tutorials button doesn't hide tutorial button in new editor

### ISSUE THREAD

**Issue by EliteNinja2084** [ScratchAddons/ScratchAddons#6307] opened 2023-06-29 04:38 UTC
Hide Tutorials button Addon doesnt hide the tutorials button in the editor nav bar.

### Steps to reproduce

1. Open the Addon settings
2. Enable **Hide Tutorials button**
3. Open Scratch's Online Editor
4. Look at the nav bar - The Tutorial Button is still there!

### Demonstration(s) and additional context

![image](https://github.com/ScratchAddons/ScratchAddons/assets/138089723/cee1140a-174c-4a57-b10d-7f4d305c0349)

### Environment

Browser:  Opera GX
Scratch Addons version:  1.33.2
Operating system:  Windows 11
Scratch Version: 3.0 Online Editor

**Comment by EliteNinja2084** [comment] 2023-06-29 05:40
Idk how to add labels.

**Comment by WorldLanguages** [comment] 2023-06-29 16:19
Duplicate of #6293

**Closed by WorldLanguages** 2023-06-29 16:19 UTC
Labels: type: bug, scope: addon
