### ISSUE TITLE
An addon that lets the user choose editor fonts

### ISSUE THREAD

**Issue by penguinmoose** [ScratchAddons/ScratchAddons#5122] opened 2022-09-22 02:44 UTC
### Why this would be helpful/solve a problem

Sometimes I want to change the font of certain parts of the editor such as variable values or blocks. This can improve readability.

### What this addon does

This addon lets the user change the font per part of the editor, such as shown variable values, reporter block previews, blocks, etc. With the current sans serif font across all of the editor, some things can become very hard to read such as long variable values. The user can change the font through the extension.

The options will definitely include monospace, and also maybe some other display fonts. Or it can be the preset fonts, like `sans-serif`, `serif`, `monospace`, `cursive`, etc.

Ability to control font size would also be nice.

### Possible alternatives

- **Ability to control spacing and size, etc too.**
- Fonts can be changed within the editor.
- Only hovering over a certain piece of text changes the font - font is default otherwise.

**Comment by apple502j** [comment] 2022-09-27 11:54
Duplicate of #1646

**Closed by apple502j** 2022-09-27 11:54 UTC
Labels: type: enhancement, new addon, scope: addon
