### ISSUE TITLE
If there is customization for editor colors, why don't we just do it for dark mode on the website

### ISSUE THREAD

**Issue by silvxrcat** [ScratchAddons/ScratchAddons#2255] opened 2021-04-21 21:32 UTC
**Is your feature request related to a problem? Please describe.**

Ah, the new update. It's a good one, but considering the fact that the editor gets customization for colors, why not do it for the rest of the website?

**Describe the solution you'd like**

In the "Dark Mode" menu, you can customize the colors and how things appear, such as dialog boxes or the containers in the front page, and the navbar color.

**Describe alternatives you've considered**

Using Tampermonkey is a better way to customize it, but for scratchers who don't know that much on real code, it might be confusing.

**Additional context**

off topic:

I have a editor preset (called Finery, an edit of 3.Darker)

```json
"editor-dark-mode": {
  "enabled":true,
  "settings": {"accent":"#151515","activeTab":"#202020","border":"#ff7b2600","categoryMenu":"#202020","darkComments":true,"darkScrollbars":true,"dots":false,"fullscreen":"#000000","input":"#202020","menuBar":"#111111ff","page":"#111111ff","palette":"#151515ff","primary":"#ff7b26ff","selectedMode":"experimental-dark","selector":"#202020","selector2":"#202020","selectorSelection":"#111111","stageHeader":"#000000","tab":"#151515","textShadow":false,"workspace":"#151515ff"}
}
```

**Comment by WorldLanguages** [comment] 2021-04-21 21:48
> Ah, the new update. It's a good one, but considering the fact that the editor gets customization for colors, why not do it for the rest of the website?

Duplicate of #645

> off topic:
\
I have a editor preset (called Finery, an edit of 3.Darker)

Cool! See #2232, we can't add everyone's colors as a preset but we might add a dedicated "editor themes" category to the settings page where everyone can submit their own, and have screenshots for all of them.

**Comment by WorldLanguages** [comment] 2021-04-21 21:48
Dupliacte of #645

**Comment by WorldLanguages** [comment] 2021-04-21 21:49
Duplicate of #645

**Closed** 2021-04-21 21:49 UTC
Labels: scope: addon, status: duplicate, type: enhancement
