### ISSUE TITLE
Ability to Upload Fonts to Editor

### ISSUE THREAD

**Issue by Scratchfangs** [ScratchAddons/ScratchAddons#2050] opened 2021-04-02 14:09 UTC
I think you should be able to add more fonts. There could be a button under all the fonts that says "upload new font". And once you upload the font, it would be saved to your storage for use in different projects. Why can't you just use Google Drawings or something? When you try editing that in Scratch, it would go back to default Sans Serif.

![image](https://user-images.githubusercontent.com/71499307/113422918-85dd0300-939b-11eb-8835-4aab9dadbe14.png)

**Comment by apple502j** [comment] 2021-04-02 14:15
We don't have storage to store uploaded fonts, rejected.

**Comment by Scratchfangs** [comment] 2021-04-02 14:17
> We don't have storage to store uploaded fonts, rejected.

I said that it could be saved to the computer storage.

**Comment by mxmou** [comment] 2021-04-02 14:18
> > We don't have storage to store uploaded fonts, rejected.
> 
> I said that it could be saved to the computer storage.

Other users would not see it.

**Comment by TheColaber** [comment] 2021-04-02 14:29
You can store a link to the font in the svg? I think I've done this with Sora before...

**Comment by mxmou** [comment] 2021-04-02 14:35
@TheColaber This is only possible with fonts that are available online, not with uploaded fonts.

**Comment by TheColaber** [comment] 2021-04-02 14:37
True, so why not do that? Why not use some API or something, so the user can input "Sora" and returns a URL to it's styles

**Comment by Hans5958** [comment] 2021-04-02 14:38
Reopening. Classic Apple closing stuff for reading only a portion of the text. Alternatives may exist in various form.

**Comment by Hans5958** [comment] 2021-04-02 14:39
> @TheColaber This is only possible with fonts that are available online, not with uploaded fonts.

Well, he said "the link," not "the file".

I don't know, is it possible to embed fonts to `.svg`s?

**Comment by WorldLanguages** [comment] 2021-04-02 15:30
We could provide more fonts by converting SVG text into path (but somehow storing metadata that will still allow the user to edit the path as if it was text)

**Comment by TheColaber** [comment] 2021-04-02 15:32
> We could provide more fonts by converting SVG text into path (but somehow storing metadata that will still allow the user to edit the path as if it was text)

In that case, there might as well be a scratch tool website to do this. Enter text, choose point, download svg. Then import to scratch

**Comment by Scratchfangs** [comment] 2021-04-02 15:43
Downloading is a little too much, I have more than 100 files just from doing that from Google Drawings

**Comment by CubeyTheCube** [comment] 2021-04-03 05:01
> > > We don't have storage to store uploaded fonts, rejected.
> > 
> > 
> > I said that it could be saved to the computer storage.
> 
> Other users would not see it.

I think this person wants it to be stored locally for personal use. Maybe the backpack can be abused so it can saved through the account.

**Comment by Secret-chest** [comment] 2021-04-03 06:29
Solution: use Google Fonts. A list of google fonts, like the google docs one.

**Comment by Secret-chest** [comment] 2021-04-05 06:10
For the Google Fonts suggestion, my idea is:
When you click the font dropdown, you see a button labeled More Fonts (above or under the normal ones). When you click that button, you see a search box, a Pinned Fonts list, and, below that, the list of all the Google fonts.

**Comment by RedGuy12** [comment] 2021-04-05 13:01
@Secret-chest there are waaaaaay too many google fonts for that to work.

**Comment by Secret-chest** [comment] 2021-04-05 15:09
> @Secret-chest there are waaaaaay too many google fonts for that to work.

@RedGuy12 It will only link to the font when you actually choose it

**Comment by SheepTester** [comment] 2021-04-06 00:04
Re Google Docs, I believe their TTF files are in [google/fonts](https://github.com/google/fonts). They don't need to be included as part of the extension files; instead, perhaps they could be fetched when used, ideally from fonts.googleapis.com

To convert to SVG, one could use [opentype.js](https://opentype.js.org/); it only supports OTF and TTF formats, so a different library is needed to decompress WOFF/WOFF2 files.

AFAIK, Scratch already allows any arbitrary font family value in SVGs, and presumably if the font isn't supported, it reverts to a fallback
![image](https://user-images.githubusercontent.com/22133785/113640477-5d216b80-9630-11eb-8f71-10a2026b4dc3.png)
We could just load a font selected by a user (either by uploading or from Google Fonts) but remind the user to convert their text to a path or it won't show the same for other people. (This matches the behaviour of some vector editors like Adobe Illustrator, I think)

**Comment by CubeyTheCube** [comment] 2021-04-06 05:08
> Re Google Docs, I believe their TTF files are in [google/fonts](https://github.com/google/fonts). They don't need to be included as part of the extension files; instead, perhaps they could be fetched when used, ideally from fonts.googleapis.com
> 
> To convert to SVG, one could use [opentype.js](https://opentype.js.org/); it only supports OTF and TTF formats, so a different library is needed to decompress WOFF/WOFF2 files.
> 
> AFAIK, Scratch already allows any arbitrary font family value in SVGs, and presumably if the font isn't supported, it reverts to a fallback
> ![image](https://user-images.githubusercontent.com/22133785/113640477-5d216b80-9630-11eb-8f71-10a2026b4dc3.png)
> We could just load a font selected by a user (either by uploading or from Google Fonts) but remind the user to convert their text to a path or it won't show the same for other people. (This matches the behaviour of some vector editors like Adobe Illustrator, I think)

Will the option to import fonts also be included?

**Comment by SheepTester** [comment] 2021-04-06 06:16
I'm only suggesting how this could be implemented, but I have no plans on actually implementing this

It should be possible to import fonts of a select few file formats; it would have the same issue as with Google Fonts where it won't work for others if they don't have Scratch Addons (until converted to an SVG path, which would be hard to edit as text unless, as W_L suggested, we kept track of the text paths in some metadata). Another concern might be that we won't have access to the font file on reload; it could be saved in the browser, which would be a bit redundant, or we could just have users reupload the font when they return to editing, displaying the fallback in the meantime

(though I suppose another option would be to upload fonts to Scratch's asset servers :eyes:)

**Comment by jeffalo** [comment] 2021-04-06 14:32
don't svgs have the ability to import fonts and stuff from a url? we could upload some nice fonts to assets.scratch.mit.edu and then automatically import them for the user

**Comment by SheepTester** [comment] 2021-04-06 17:34
> don't svgs have the ability to import fonts and stuff from a url? we could upload some nice fonts to assets.scratch.mit.edu and then automatically import them for the user

IIRC if rendered as an embedded image as opposed to opened standalone in a new tab, SVGs won't fetch external resources. The assets server might also not return the correct MIME type for the font files, which might anger the browser

It's not out of the ordinary to have to manually and explicitly irreversibly convert text to a path IMO

**Comment by xItzDiamondx** [comment] 2021-04-12 18:35
It would be better if we included some fonts, and then possibly as we update, add more fonts?

**Comment by Secret-chest** [comment] 2021-04-13 05:54
> don't svgs have the ability to import fonts and stuff from a url? we could upload some nice fonts to assets.scratch.mit.edu and then automatically import them for the user

@jeffalo you will only add Sora

**Comment by Secret-chest** [comment] 2021-04-13 05:55
Okay, we cloud use only the most popular Google fonts:
- Roboto
- Lato
- Montserrat
- Source Sans Pro
- Noto Sans is already included
- Roboto Mono (we need a monospaced font)

**Comment by xItzDiamondx** [comment] 2021-04-14 12:34
Good idea.

**Comment by Scratchfangs** [comment] 2021-04-25 21:37
Bump?

**Comment by TheColaber** [comment] 2021-04-25 22:08
> Bump?

This is not the scratch forums. Bumping doesn't actually do anything. Someone will attempt to make this an addon, or you can.

**Comment by ErrorGamer2000** [comment] 2021-04-30 14:59
> > We could provide more fonts by converting SVG text into path (but somehow storing metadata that will still allow the user to edit the path as if it was text)
> 
> In that case, there might as well be a scratch tool website to do this. Enter text, choose point, download svg. Then import to scratch

I use [this](https://danmarshall.github.io/google-font-to-svg-path/) to get the path I need, then copy and paste it into an empty .txt file and change the extension . . . maybe base the code off of this and allow a drag n' drop for a ttf file instead of saving the link? This is beyond my skillset, but I was thinking maybe make a little popup or use prompt to get the text, then insert it into the svg?

**Comment by TheColaber** [comment] 2021-06-10 21:47
It's been suggested to add back the "Scratch" font, [which is apparently already loaded into scratch but just isn't an option.](https://scratch.mit.edu/projects/238672765/)

**Comment by mxmou** [comment] 2021-06-11 07:35
@TheColaber See LLK/scratch-render-fonts#23

**Comment by wgyt** [comment] 2021-06-22 16:38
isn't this a dupe of #1646

**Comment by mxmou** [comment] 2021-06-22 17:50
@wgyt #1646 is for changing the font in which the website is displayed, not adding more fonts to the paint editor.

**Comment by wgyt** [comment] 2021-06-22 17:54
> @wgyt #1646 is for changing the font in which the website is displayed, not adding more fonts to the paint editor.

my bad

**Comment by Rendangbike** [comment] 2022-01-19 02:17
I saw that my suggestion was a duplicate of this one so I'm just going to put my mockups in here.

![Mockup](https://assets.scratch.mit.edu/get_image/.%2E/9b496298fe976f917ab4369effb0c9c4.png "Mockup")
![Mockup](https://assets.scratch.mit.edu/get_image/.%2E/9556f2c18245d0e915928238214606c9.png "Mockup")

**Comment by CST1229** [comment] 2022-01-19 06:54
I think I already posted this before somewhere but `"Helvetica Neue", "Helvetica", Arial, sans-serif` (Scratch website font) and `"Serif"` (WITH quotation marks; fixed serif font) would be a good place to start.

**Comment by RIMOPA** [comment] 2022-07-24 02:13
Is there no way to detect system fonts?

**Comment by mxmou** [comment] 2022-07-24 06:25
> Is there no way to detect and use system fonts?

People that don't have the same fonts installed won't see them.

**Comment by apple502j** [comment] 2022-09-27 11:54
Rejected. No more reconsideration.

**Closed by apple502j** 2022-09-27 11:54 UTC
Labels: type: enhancement, new addon, scope: addon

**Comment by Secret-chest** [comment] 2022-09-27 14:36
> Rejected. No more reconsideration.

wait why? no explanation? what about google fonts? @apple502j

**Comment by mxmou** [comment] 2022-09-27 14:40
@Secret-chest Embedding fonts in a SVG or hoping that the user has them on their device is not practical. Using external resources in a Scratch SVG is not possible.
