### ISSUE TITLE
follower graph bug

### ISSUE THREAD

**Issue by Riptide-Scratch** [ScratchAddons/ScratchAddons#2028] opened 2021-03-30 23:22 UTC
ok so idk if this is supposed to happen
![buuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuug](https://user-images.githubusercontent.com/70417080/113068906-1afdb300-9174-11eb-9ac0-340b42a13ef0.jpg)
[scratchers profile](https://scratch.mit.edu/users/epicm_pikachu/)

**Comment by RedGuy12** [comment] 2021-03-30 23:24
I can't repo, but I believe this was fixed by #2016

**Comment by mxmou** [comment] 2021-03-31 06:38
Duplicate of #2005

**Comment by mxmou** [comment] 2021-03-31 06:38
@RedGuy12 Yes, this will be fixed in the next version.

**Closed by mxmou** 2021-03-31 06:38 UTC
Labels: scope: addon, status: duplicate, type: bug
