### ISSUE TITLE
New Addon - Project Fullscreen

### ISSUE THREAD

**Issue by e-coders** [ScratchAddons/ScratchAddons#3553] opened 2021-09-25 17:29 UTC
New Addon - Project Fullscreen
I've made it, I hope that it may also works, but I want to merge commit. please merge pull request.
For Source Code - "e-coders-official/ScratchAddons/addons/project-fullscreen" there I've added.

**Comment by e-coders** [comment] 2021-09-25 17:30
https://github.com/E-Coders-Official/ScratchAddons

**Comment by e-coders** [comment] 2021-09-25 17:39
https://github.com/ScratchAddons/ScratchAddons/pull/3554

**Comment by e-coders** [comment] 2021-09-25 17:39
https://github.com/ScratchAddons/ScratchAddons/pull/3554

**Comment by e-coders** [comment] 2021-09-25 17:39
https://github.com/ScratchAddons/ScratchAddons/pull/3554

**Comment by e-coders** [comment] 2021-09-25 17:40
https://github.com/ScratchAddons/ScratchAddons/pull/3554

**Comment by e-coders** [comment] 2021-09-25 17:40
https://github.com/ScratchAddons/ScratchAddons/pull/3554

**Comment by e-coders** [comment] 2021-09-25 17:40
?

**Comment by RedGuy12** [comment] 2021-09-25 17:46
Duplicate of #587

**Comment by e-coders** [comment] 2021-09-25 18:23
But there I've added a Embed Page. I can simply say that I'v Really not copied. You can see the code.

**Closed** 2021-09-25 18:23 UTC
Labels: type: enhancement, new addon, scope: addon

**Comment by e-coders** [comment] 2021-09-25 18:33
:((
