### ISSUE TITLE
Username filter in Messaging popup

### ISSUE THREAD

**Issue by oof-le-oof** [ScratchAddons/ScratchAddons#1208] opened 2021-01-05 00:03 UTC
Would it be possible to add a username filter to the messages popup?
Theoretically this would work to allow the user to select a username, and only view messages from that user.

Edit: 69th star. Nice.

_Originally posted by @oof-le-oof in https://github.com/ScratchAddons/ScratchAddons/discussions/987_

**Comment by Cool-Scratcher** [comment] 2021-01-05 00:53
Wow, this is a great idea... I can see many possibilities. +1.

**Comment by RedGuy12** [comment] 2021-01-05 01:08
Can't be too hard
________________________________

**Comment by WorldLanguages** [comment] 2021-06-10 21:27
Duplicate of #1038

**Closed by WorldLanguages** 2021-06-10 21:27 UTC
Labels: scope: addon, type: enhancement
