### ISSUE TITLE
Some stuff is not styled by dark mode (Front page buttons when signed out)

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#527] opened 2020-10-18 16:54 UTC
![image](https://user-images.githubusercontent.com/61319150/96374468-a50f0d80-1138-11eb-8bda-bdb7c66830b6.png)

**Comment by Explosion-Scratch** [comment] 2020-10-18 16:54
The section with the 'about scratch' button and the other ones is what I'm talking about.

**Comment by WorldLanguages** [comment] 2020-10-18 20:25
@GDUcrash

**Comment by GDUcrash** [comment] 2020-10-18 20:50
god dammit, I'll fix it tomorrow. I knew I should've spent more than 1 day on this lol

**Comment by GDUcrash** [comment] 2020-10-19 10:05
@WorldLanguages @Explosion-Scratch Ok, so i fixed the bug and also added some styles for the remix tree page

<img src="https://media.discordapp.net/attachments/510776441084968977/767689449559556126/unknown.png?width=1026&height=394">

**Comment by GDUcrash** [comment] 2020-10-20 15:38
@Explosion-Scratch the issue is now fixed!

**Closed** 2020-10-20 23:50 UTC
Labels: bug
