### ISSUE TITLE
Scratch Stats buttons on profies 

### ISSUE THREAD

**Issue by superscratch444tre** [ScratchAddons/ScratchAddons#1284] opened 2021-01-11 15:34 UTC
**Describe the new addon**

This will add quick links on profiles to ScratchStats.com and Hans5958's Scratch Stats.

**Link to the new addon**

Something like this: https://github.com/Hans5958/userscripts/blob/master/Scratch/Shorter%20Scratch%20Stats%20Links.user.js.

**Comment by RedGuy12** [comment] 2021-01-12 03:23
why a button when you can include the information right there?

**Comment by superscratch444tre** [comment] 2021-01-12 11:29
> why a button when you can include the information right there?

Yes, but that is harder to make.

**Comment by superscratch444tre** [comment] 2021-01-12 11:30
> > why a button when you can include the information right there?
> 
> Yes, but that is harder to make.

And I think the links are better.

**Comment by pufferfish101007** [comment] 2021-01-12 11:35
Including info from the scratchstats api is rejected (see https://github.com/ScratchAddons/ScratchAddons/issues/494#issuecomment-708705312), but using data from scratchstats isn't. Either way, #494 covers including information on profiles.

**Comment by mxmou** [comment] 2021-01-12 12:07
> Including info from the scratchstats api is rejected (see [#494 (comment)](https://github.com/ScratchAddons/ScratchAddons/issues/494#issuecomment-708705312)), but using data from scratchstats isn't. Either way, #494 covers including information on profiles.

I think all important data is on ScratchDB, the only problem is that Scratch Addons can't currently access it (#1203).

**Comment by Hans5958** [comment] 2021-01-12 15:04
Duplicate of #494

**Comment by Hans5958** [comment] 2021-01-12 15:05
Wait, it's probably, reopening again, I guess.

**Comment by TheColaber** [comment] 2021-01-13 03:26
duplicate of #494

**Comment by TheColaber** [comment] 2021-01-13 03:28
Duplicate of #494

**Closed by TheColaber** 2021-01-13 03:28 UTC
Labels: new addon
