### ISSUE TITLE
When duplicating anything into a script, the script runs itself.

### ISSUE THREAD

**Issue by DroneBetter** [ScratchAddons/ScratchAddons#1520] opened 2021-02-08 12:20 UTC
If you use right-click > duplicate, you drag the duplicated thing around by the point you clicked, as you'd expect if you held left click and dragged the original thing, but without having to hold down click.

However, when you release the thing (by clicking instead of letting go), Scratch detects it both as a release and a click to run the function the mouse-pointer is hovering over.

This is a Scratch bug, not a ScratchAddons one, but could ScratchAddons have a patch to fix it? When duplicating into large scripts, running them causes much lag, and (because function parameters default to blank when you run their definition instead of an instance of them) can cause infinite loops which prevent editing until it checks if the stop sign has been pressed (sometimes after ~10 seconds).

**Comment by TheColaber** [comment] 2021-02-08 12:56
Duplicate of #591

**Closed by TheColaber** 2021-02-08 12:56 UTC
Labels: status: needs triage, type: bug
