### ISSUE TITLE
Messages are slow to load

### ISSUE THREAD

**Issue by The-Abigail608** [ScratchAddons/ScratchAddons#6758] opened 2023-10-10 12:45 UTC
### Description

Messages take ~12 seconds to load when they used to take less than 10 seconds, this happens on my Windows 11 laptop on my home wifi as well as here on my school Chromebook and school wifi, at least one of my friends is also experiencing this issue.

### Steps to reproduce

1. click extension and wait for messages to load

### Environment

Browser: 117.0.5938.144
Scratch Addons version: 1.34.1
Operating system: Chrome OS Version 117.0.5938.144 (Official Build) (64-bit)

**Comment by CST1229** [comment] 2023-10-10 12:52
#6717, the issue is already fixed (so it will be in 1.35.0).

**Closed by CST1229** 2023-10-10 12:52 UTC
Labels: type: bug, status: needs triage
