### ISSUE TITLE
transition to scratch.org

### ISSUE THREAD

**Issue by Waakul** [ScratchAddons/ScratchAddons#7562] opened 2024-06-20 19:06 UTC
I believe Scratch is slowly transitioning to https://scratch.org/, I can spot changes here and there so it's probably WIP. They are having a complete redesign which means some of the addons will be broken, like the dark mode and all. The permissions can also become a headache, if we add a required permission, the extension will be disabled for the current users I believe.. #7531 might be a solution to this issue I suppose. The addons might need a complete renovation to work properly. I recommend confirming with Scratch if they are really transitioning. Turbowarp has already made some changes like changing the link at the bottom linking to scratch to the new one. I believe GarboMuffin won't do that without clarification.

**Comment by mxmou** [comment] 2024-06-20 19:08
Duplicate of #6508

**Comment by CubesterYT** [comment] 2024-06-20 19:08
Scratch is not planning to move to that domain. They state they're mainly using it for blog posts and news/similar

**Closed by mxmou** 2024-06-20 19:08 UTC
Labels: status: needs triage

**Comment by mxmou** [comment] 2024-06-20 19:10
> Scratch is not planning to move to that domain. They state they're mainly using it for blog posts and news/similar

[The announcement](https://scratch.mit.edu/discuss/topic/765450/) says they will move some pages there (About, Contact Us, Terms of Use, Download, ...).

**Comment by Waakul** [comment] 2024-06-20 19:13
> > Scratch is not planning to move to that domain. They state they're mainly using it for blog posts and news/similar
> 
> [The announcement](https://scratch.mit.edu/discuss/topic/765450/) says they will move some pages there (About, Contact Us, Terms of Use, Download, ...).

Addons need to work on those pages too?

**Comment by mxmou** [comment] 2024-06-21 06:13
> > [The announcement](https://scratch.mit.edu/discuss/topic/765450/) says they will move some pages there (About, Contact Us, Terms of Use, Download, ...).
> 
> Addons need to work on those pages too?

Few addons run on those pages - dark mode is the most important one - and users don't visit them often. Supporting them would be nice but it isn't very important.
