### ISSUE TITLE
Scratch Addons refuses to work on some pages in newest Chrome update.

### ISSUE THREAD

**Issue by MarkusPerssonMojang** [ScratchAddons/ScratchAddons#7488] opened 2024-06-01 18:44 UTC
### Description

Dark mode does not work after clicking "My stuff", Create, or Messages.
Onion Skinning does not work either.
I can tell Scratch Addons is enabled cause there is a "Color Mode" in settings.

### Steps to reproduce

1. Update Chrome to the latest version
2. Restart Computer
3. click on "My stuff", Create, or Messages
4. Scratch Addons stops working

### Demonstration(s) and additional context

![Screenshot 2024-06-01 2 38 23 PM](https://github.com/ScratchAddons/ScratchAddons/assets/121984478/d1aed3bf-cc8a-4040-abb3-e3b0a6c89d33)
![Screenshot 2024-06-01 2 38 10 PM](https://github.com/ScratchAddons/ScratchAddons/assets/121984478/6aa98b56-38b4-401e-8a2d-109bb6f4f815)
![Screenshot 2024-06-01 2 39 00 PM](https://github.com/ScratchAddons/ScratchAddons/assets/121984478/6fe4679d-0cd4-4e7b-ba0c-7944ff2bde68)
![Screenshot 2024-06-01 2 40 02 PM](https://github.com/ScratchAddons/ScratchAddons/assets/121984478/f02c3eb8-1469-4708-af3e-db3580d9680f)

### Environment

Browser: Chrome, Version 124.0.6367.225
Scratch Addons version: 1.38.1. 
Operating system: Chrome

**Comment by WorldLanguages** [comment] 2024-06-01 18:45
Disable "Necropost Highlighter"

**Comment by WorldLanguages** [comment] 2024-06-01 18:46
Duplicate of #7481

Fixed in v1.38.2 (pending Chrome review)

**Closed by WorldLanguages** 2024-06-01 18:46 UTC
Labels: type: bug, status: duplicate, scope: core
