### ISSUE TITLE
Zebra coloring

### ISSUE THREAD

**Issue by VSchris-code** [ScratchAddons/ScratchAddons#3124] opened 2021-07-27 17:26 UTC
### Is your request related to a problem? Please describe.

From looking at Snap! code, I noticed there's zebra coloring, where a block placed inside of another within the same category recieves a lighter tone. It's pretty unique when one that is used to Scratch tries Snap! for the first time, albeit I'm feeling like it can be carried over to Scratch with a addon.

### Describe the solution you'd like

Be able to change the color of the block when it's placed inside another from the same category, either by making it lighter or darker, including the hue, configurable within the addon's settings

### Describe alternatives you've considered

Pretty much nothing

### Additional context

Same as above

**Comment by Cool-Scratcher** [comment] 2021-07-27 19:37
I did a search on ocular and it seems like pulljosh suggested the same idea on the [Scratch discussion forums,](https://scratch.mit.edu/discuss/topic/274523/?page=1#post-2796442).

If you go to the discussion, you can see many users sharing their thoughts, and one of the most interesting was how this would help colorblind users. There's many other benefits, so yeah. This would be a cool addon.

I think it might be hard to implement though.

**Comment by TheColaber** [comment] 2021-07-27 19:42
Duplicate of #2742

**Closed by TheColaber** 2021-07-27 19:42 UTC
Labels: new addon, scope: addon, type: enhancement
