### ISSUE TITLE
No show messages of the Scratch Team

### ISSUE THREAD

**Issue by Miala-python** [ScratchAddons/ScratchAddons#2295] opened 2021-04-26 13:58 UTC
**Describe the bug**

>I have a message of the scratch team:
![image](https://user-images.githubusercontent.com/65893041/116094379-c59bbf80-a6a7-11eb-8b6b-a9975c83ee65.png)

**Informations**
> OS: Windows 7
> Browser: Chrome
> V1.13.0

>>Sorry, I not speak english very well.

**Comment by TheColaber** [comment] 2021-04-26 13:59
Duplicate of #1710

**Closed by TheColaber** 2021-04-26 13:59 UTC
Labels: status: needs triage, type: bug
