### ISSUE TITLE
Comment outline does not change with theme3

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#2204] opened 2021-04-18 01:13 UTC
![image](https://user-images.githubusercontent.com/72760579/115130914-a030f680-9fc1-11eb-88d9-bc3efb4e4d03.png)
Notice how the block color was purple but the comment outline is (default) red.

**Comment by mxmou** [comment] 2021-04-18 07:52
Duplicate of #1806

**Closed by mxmou** 2021-04-18 07:52 UTC
Labels: scope: addon, type: bug
