### ISSUE TITLE
Quick Access Dark and Light Theme

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#682] opened 2020-11-08 02:37 UTC
**Change Between Dark and Light Theme Quickly**

I think we should add a button to switch between the dark and light theme in the popup itself. I might be able to do this myself but lots of your code is very confusing cause I am not that advanced in JavaScript. I barely even know what his means `$("#id")` I guess its a shortcut for `document.querySelectorAll("")`. If I am able to successfully accomplish this where do I add my file?

**Comment by samuraininja360** [comment] 2020-11-08 02:38
Also which variable determines the light or dark theme?

**Comment by WorldLanguages** [comment] 2020-11-08 15:06
Duplicate of #521

**Closed by WorldLanguages** 2020-11-08 15:06 UTC
Labels: enhancement
