### ISSUE TITLE
Remix tree button not working

### ISSUE THREAD

**Issue by Cool-Scratcher** [ScratchAddons/ScratchAddons#640] opened 2020-11-03 17:42 UTC
**Describe the bug**

When the remix tree is checked in settings, the button appears on the project page but does not serve any function, and doesn't do anything when clicked.

**To Reproduce**

1. Go to the settings page in the extension.
2. Search "remix tree."
3. Enable it.
4. Go to a project page, and click on the Remix Tree button. Nothing happens.

**Expected behavior**

To append "/remixtree" to the end of the URL, to view the tree. (If there is a slash on the end already, to delete it and add "/remixtree")

**Screenshots**

<img width="325" alt="Screenshot 2020-11-03 123832" src="https://user-images.githubusercontent.com/65724251/98020903-9b8cd300-1dd1-11eb-8b3b-093c69b1f1f9.png">

**Device:**

- OS: Windows 10 64-bit
- Browser: Google Chrome
- Version: 86.0.4240.111

**Comment by WorldLanguages** [comment] 2020-11-03 20:34
Thanks so much for reporting! This is fixed on unreleased v1.3.0

(see #583)

**Closed by WorldLanguages** 2020-11-03 20:34 UTC
Labels: bug

**Comment by mxmou** [comment] 2022-04-05 20:55
Duplicate of #585
