### ISSUE TITLE
All new addons should have the new tag on the settings page

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#1505] opened 2021-02-05 19:46 UTC
**Is your feature request related to a problem? Please describe.**

I think people should be aware of all additions, not only the most important ones. Most people probably don't read changelogs.

**Describe the solution you'd like**

Show all recently added addons with the "New!" tag on the settings page.

**Comment by TheColaber** [comment] 2021-02-05 19:47
Hmm...
Duplicate of #1424
?

**Comment by mxmou** [comment] 2021-02-05 20:21
@TheColaber That one is for updated addons, not recently added addons.

**Comment by TheColaber** [comment] 2021-02-05 20:22
I see your point.

**Comment by WorldLanguages** [comment] 2021-02-05 20:51
Well, the truth is that the "new" tag was never intended to be used for all new addons. IMO it should stay as it is but I can't stop discussion ¯\_(ツ)_/¯

**Comment by TheColaber** [comment] 2021-02-05 21:29
Maybe all new addons get the NEW tag but the "best" addons should be pinned at the top

**Comment by mxmou** [comment] 2021-02-06 08:17
> Maybe all new addons get the NEW tag but the "best" addons should be pinned at the top

This wouldn't be an effective way to show everything new.

> Well, the truth is that the "new" tag was never intended to be used for all new addons. IMO it should stay as it is but I can't stop discussion ¯\_(ツ)_/¯

At least it should be renamed to "Featured", not "New" - then users would understand there might be other new addons.

One of the reasons why I suggested this is because some addons that were added recently (accessibility, show BBCode) are only useful to few users, which is why they aren't featured, but that means those users have to either read the changelog or randomly find them.

**Comment by mxmou** [comment] 2021-03-05 08:47
Long WIWO is another useful addon that people who don't read the changelog won't notice if we don't do this.

**Comment by WorldLanguages** [comment] 2021-03-05 18:34
Not sure about the details, but I'll be implementing some way to filter addons by new

**Comment by mxmou** [comment] 2021-03-05 18:45
> Not sure about the details, but I'll be implementing some way to filter addons by new

Why can't we just pin all new addons at the top? Adding many new addons at once isn't very common. Even if you think this isn't a good long term solution, it would be great if the long WIWO addon was featured in 1.11.

**Comment by WorldLanguages** [comment] 2021-03-05 19:00
@mxmou There are 5 new addons this release (AFAIK, maybe there's 1 or 2 more), I don't think pinning 5 addons at the top of the settings page for 2 weeks is a good idea
WIWO addon is a "hack" that I allow but would rather not incentivize that much. It's not the typical epic feature or customization addon. You could say the "set thumbnail" button is also like this, but that addon will always work (at least for non-moving images), while this addon will most likely stop working at some point

**Comment by WorldLanguages** [comment] 2021-03-05 19:01
We might pin all new addons at the top at some point, but in a way that is easy to ignore/collapse. Not in its current state

**Comment by mxmou** [comment] 2021-03-05 19:07
> I don't think pinning 5 addons at the top of the settings page for 2 weeks is a good idea

I suggested renaming the tag to "Featured" so users know there are other new addons. Could that be a temporary solution?

**Comment by WorldLanguages** [comment] 2021-03-05 19:43
I don't usually push new strings for translation near release

**Comment by WorldLanguages** [comment] 2021-03-24 19:51
I promise to make the main point of v1.13.0 making it easy to find, filter, enable and disable addons, which would solve this indirectly :P

**Comment by WorldLanguages** [comment] 2021-04-15 23:41
Correction: v1.14.0 :P

**Comment by TheColaber** [comment] 2021-04-27 15:32
Now that #2260 exists... any new ideas?

The filter is gone... we have subcategories. We have groups too...

**Comment by TheColaber** [comment] 2021-04-27 15:35
> We might pin all new addons at the top at some point, but in a way that is easy to ignore/collapse. Not in its current state

This is now possible with #2260.

I would also like to say that maybe we should have a new manifest property called `versionAdded` or such, so that way, we don't need to add all new addons to the array. This property is good for that reason and also for future filtering.

**Closed** 2021-05-02 15:58 UTC
Labels: scope: webpages, type: enhancement
