### ISSUE TITLE
Custom Block Names

### ISSUE THREAD

**Issue by 3dModel101** [ScratchAddons/ScratchAddons#5132] opened 2022-09-26 02:07 UTC
### Why this would be helpful/solve a problem

I sometimes would rather refer to a block by a custom name, rather than the one it's given, to fully customize my Turbowarp development.

### What this change does

This will enable the ability to customize the name of coding blocks. For example, instead of saying "next costume" you could customize the name of the block to something like "next frame".

### Demonstration(s) and additional context

![scratchblocks_exampleaddons_b f](https://user-images.githubusercontent.com/95945163/192180032-1aa3aa53-58f1-4dfb-b15f-c8c9eeb93158.png)

**Comment by mxmou** [comment] 2022-09-26 06:31
Duplicate of #1814

**Closed by mxmou** 2022-09-26 06:31 UTC
Labels: type: enhancement, new addon, scope: addon
