### ISSUE TITLE
disable cat blocks addon when it's april fools day

### ISSUE THREAD

**Issue by jeffalo** [ScratchAddons/ScratchAddons#1896] opened 2021-03-16 18:24 UTC
april fools day for 2021 currently seems to have catblocks planned. we should disable catblocks on our end to ensure ntohing wakcy happens

**Comment by retronbv** [comment] 2021-03-16 18:27
ntohing wakcy

**Comment by TheColaber** [comment] 2021-03-16 18:53
Tbh, we should disable all the addons... ST won't repeat everything from last year...

**Comment by RedGuy12** [comment] 2021-03-17 13:07
Or we can just show a note (Hey! Addons may conflict with April fools...)
But how will we know when it is? St always goes a bit early

**Comment by jeffalo** [comment] 2021-03-18 08:21
> Tbh, we should disable all the editor addons... ST won't repeat everything from last year...

we can tell what they're doing in advance https://github.com/llk/scratch-gui/tree/hotfix/totally-normal-2021

**Comment by TheColaber** [comment] 2021-03-18 12:58
I didn't see cat blocks so far... it really looks duplicate of last year without the cat blocks...

**Comment by TheColaber** [comment] 2021-03-18 13:01
Nevermind I'm wrong... https://github.com/LLK/scratch-blocks/tree/hotfix/totally-normal-2021

**Comment by FunctionalMetatable** [comment] 2021-03-20 17:54
well you never know it could just be a dummy branch just to fool people, they might have the 2021 thing private or something

**Comment by TheColaber** [comment] 2021-03-24 13:49
> After some testing, everything seems to work fine even if we run cat blocks above cat blocks.

**Closed by TheColaber** 2021-03-24 13:49 UTC
Labels: scope: core, type: enhancement
