### ISSUE TITLE
Clipped comments are misaligned when "clean up blocks +" is used and ctrl+z removes comment for no reason

### ISSUE THREAD

**Issue by hueychen27** [ScratchAddons/ScratchAddons#6838] opened 2023-11-06 00:32 UTC
### Description

Whenever you add a clipped comment to a block and you use the "clean up blocks +" feature, the comment stays in the position, but the blocks move awkwardly. When you try to undo that, the comment disappears.

### Steps to reproduce

1. Add some separate blocks.
2. Add a comment to a block and clip it.
3. Right-click and select "Clean up blocks +" in the context menu.
4. Press <kbd>ctrl</kbd>+<kbd>z</kbd> or press "Undo" in the context menu to undo.

### Demonstration(s) and additional context

https://github.com/ScratchAddons/ScratchAddons/assets/78285518/83c2a8a7-ffca-408b-8937-1939e4cedf1c

### Environment

Browser: Firefox ESR 115.3.0esr (64-bit)
Scratch Addons version: v1.35.1
Operating system: Kali Linux

**Comment by Samq64** [comment] 2023-11-06 00:40
Duplicate of #4546 and #5630.

**Closed by Samq64** 2023-11-06 00:40 UTC
Labels: type: bug, status: needs triage

**Comment by hueychen27** [comment] 2023-11-06 02:02
Oops, I did not notice.
