### ISSUE TITLE
Messages form scratch team don't get marked as read read or appear in scratch addons messages tab.

### ISSUE THREAD

**Issue by HiImBlahh** [ScratchAddons/ScratchAddons#2417] opened 2021-05-06 22:10 UTC
Messages form scratch team don't get marked as read read or appear in scratch addons messages tab.

**To Reproduce**
Go to any project or profile and comment scratch addons. wait until you are unmuted. if you look in scratch addons messages tab you won;t see scratch team message, but in your regular messages you will see it. clicking mark as read will not mark it as read.

**Expected behavior**

will show up in scratch addons messages tab and is able to be marked as read.
**Screenshots**

![Screenshot 2021-05-06 3 07 11 PM](https://user-images.githubusercontent.com/78574005/117371616-08665000-ae7d-11eb-9c5b-ddb471b4986d.png)
![Screenshot 2021-05-06 3 08 14 PM](https://user-images.githubusercontent.com/78574005/117371624-0dc39a80-ae7d-11eb-962b-bea44f423170.png)

- OS: chromeos
- Browser chrome
- Version 90.0.4430.86

**Comment by TheColaber** [comment] 2021-05-06 22:21
duplicate of #1710
(yay forth duplicate)

**Closed by TheColaber** 2021-05-06 22:21 UTC
Labels: status: needs triage, type: bug
