### ISSUE TITLE
NFE Checker

### ISSUE THREAD

**Issue by skullwithatophat** [ScratchAddons/ScratchAddons#7946] opened 2024-11-19 00:01 UTC
### Why this would be helpful

to see that projects are NFE or FE

### How this addon works

✔ = FE ⛔ = NFE 🤔 = not rated

### Additional context

its on scratchtools

**Comment by Samq64** [comment] 2024-11-19 00:20
Duplicate of #6484

**Closed by Samq64** 2024-11-19 00:20 UTC
Labels: type: enhancement, new addon, scope: addon
