### ISSUE TITLE
Differentiate L and i in usernames

### ISSUE THREAD

**Issue by Mr-Anonymous75** [ScratchAddons/ScratchAddons#2873] opened 2021-06-28 05:07 UTC
### Is your request related to a problem? Please describe.

A very common problem in scratch is impersonation - if there's a lowercase L or an uppercase i in a username, it can easily be impersonated by changing lowercase L's to uppercase i's, and uppercase i's to lowercase l's. This can be really misleading. 

### Describe the solution you'd like

While displaying usernames, if the font being used has the option, always use Ɪ - that's the uppercase i with bars at the top and bottom - and the kind of lowercase L that a lot of monospace fonts have. Otherwise, just always display uppercase L's and lowercase i's in usernames. 

### Describe alternatives you've considered

Maybe put a warning at the top of the page that tells the user that the profile they're on uses the L and i trick?
Actually, what about both of these solutions?

**Comment by fierin** [comment] 2021-06-28 14:13
Il
guess what is i and what is L?
i dint think its much a scratch addons issue as a english font issue.

**Comment by WorldLanguages** [comment] 2021-06-28 21:56
This can be moved to a discussion. This feels too out of scope for Scratch Addons.

**Closed** 2021-06-28 21:56 UTC
Labels: new addon, scope: addon, type: enhancement

**Comment by RedGuy12** [comment] 2021-07-01 21:23
I say this could be considered a duplicate of #1646

**Comment by fierin** [comment] 2021-07-02 06:01
> I say this could be considered a duplicate of #1646

this had been closed anyway.
