### ISSUE TITLE
Enabling "Preview project instructions and notes" will deactivate "Project notes tabs" until reload

### ISSUE THREAD

**Issue by geodebreaker** [ScratchAddons/ScratchAddons#7998] opened 2024-12-14 17:21 UTC
### Description

This is my first time writing a bug report, sorry for any mistakes.

When you are using "Preview project instructions and notes" and flip the switch to enable preview and then disable it, "Project notes tabs's" effect will not be displayed.

To fix, I belive you would only need to make sure "Project notes tabs" will be renabled once "Preview project instructions and notes" is turned off.

### Steps to reproduce

1. Have "Project notes tabs" and "Preview project instructions and notes" active 
2. Go to any of your own projects
3. Click the switch named preview next to the project description

### Demonstration(s) and additional context

Sorry for large images!
![Screenshot 2024-12-14 11 14 08 AM](https://github.com/user-attachments/assets/e3c13386-2310-4855-9e44-8323f05d2ba0)
![Screenshot 2024-12-14 11 14 13 AM](https://github.com/user-attachments/assets/3a25de51-ff8a-4611-bfc7-cd0586a22442)
![Screenshot 2024-12-14 11 14 18 AM](https://github.com/user-attachments/assets/359fd19b-1ff4-44bd-8a6a-88ab1acb2863)

### Environment

Browser: Chrome 130.0.6723.126
Scratch Addons version: 1.39.2
Operating system: Chrome OS

**Comment by mxmou** [comment] 2024-12-14 17:33
Duplicate of #6698

**Comment by geodebreaker** [comment] 2024-12-14 17:34
ok sorry its hard to find duplicates in 900 issues

**Closed by mxmou** 2024-12-14 17:33 UTC
Labels: type: bug, scope: addon, scope: addon compatiblity

**Comment by WorldLanguages** [comment] 2024-12-16 22:36
No worries
