### ISSUE TITLE
Custom Navbar Colors

### ISSUE THREAD

**Issue by Marc92020** [ScratchAddons/ScratchAddons#1077] opened 2020-12-20 16:50 UTC
Here I am again with a bad or impossible idea.
**Describe the new addon**
This addon would allow users to change the color of the navbar.

**Link to the new addon**
There is no link

**Comment by jeffalo** [comment] 2020-12-20 17:00
not bad nor impossible, perhaps this could be built into the 2.0->3.0 addon

**Comment by thecoder876** [comment] 2020-12-20 17:32
If you install [Stylus](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne) and then [this script](https://mxmou.github.io/customize-scratch/scratchr2.user.css) made by @mxmou, you can change the colour. The script is called Scratchr2 and its dark mode function is an addon in Scratch Addons. For some reason, the other functions aren't in the addon.

**Comment by PhoenixAndStuf** [comment] 2020-12-20 18:36
Cool idea! 😋

**Comment by mxmou** [comment] 2020-12-20 18:50
I'm working on #415, which means this feature will be available if 2.0 → 3.0 is enabled.

**Comment by thecoder876** [comment] 2020-12-20 18:54
Great!

**Comment by GrahamSH-LLK** [comment] 2020-12-20 19:49
This is pretty much a duplicate of #415.

**Comment by GrahamSH-LLK** [comment] 2020-12-20 19:49
Duplicate of #415

**Closed by GrahamSH-LLK** 2020-12-20 19:49 UTC
Labels: new addon
