### ISSUE TITLE
Edit Button on closed topics

### ISSUE THREAD

**Issue by lankybox02** [ScratchAddons/ScratchAddons#6397] opened 2023-07-14 13:36 UTC
### Why this would be helpful

Because it would just be easier to click a button instead of adding "/edit" at the title

### How this addon works

It adds an "edit" button to posts on closed topics.

**Comment by Samq64** [comment] 2023-07-14 13:43
Duplicate of #6189

**Closed by Samq64** 2023-07-14 13:43 UTC
Labels: type: enhancement, new addon, scope: addon
