### ISSUE TITLE
Blocks delete weirdly with auto hiding block palette

### ISSUE THREAD

**Issue by Jazza-231** [ScratchAddons/ScratchAddons#6224] opened 2023-06-18 08:16 UTC
### Description

What's happening: After making a custom block and collapsing the block palette, dragging blocks into the space where the palette normally is deletes them, even though the palette is collapsed.
What should happen: Blocks only delete when dragged over the icons while the palette is collapsed.

See below for more details, and the original bug report: [SA discord server](https://discord.com/channels/806602307750985799/1116706384180936714)

### Steps to reproduce

1. Have the Auto-hiding block palette addon enabled with the category hover or category click setting on
2. Have a block in the canvas off to the right to drag into the palette area
3. Make a new custom block (UPDATE: You don't even need to make the custom block, if you press cancel instead of ok and continue as normal it will still cause the bug to occur), and if you chose category hover the palette would have collapsed already, if you chose category click, click the “my blocks” category to hide the block palette
4. Try to drag a block (I recommend holding alt to make a duplicate block to be able to test repeatedly easily) into the area where the block palette should be but isn't. It should delete the block, even though you are dragging it over canvas space.
5. If you chose category hover, hover over the category icons then back over the block canvas, or if you chose category click, click on the “my blocks” category twice, and you will find that blocks no longer delete when you drag them into the area of the canvas where the block palette would normally be (in case it's not clear, this is what should happen always) UPDATE: You need to move a block anywhere on the canvas before opening and closing the palette, just doing it will not work

### Demonstration(s) and additional context

A video demonstrating a few repetitions: [video](https://cdn.discordapp.com/attachments/1116706384180936714/1116706693183701062/Auto_hiding_block_palette_bug.mp4)

### Environment

Originally tested on turbowarp desktop 1.7.1
Browser: Brave Version 1.52.126, Chromium: 114.0.5735.133
Scratch Addons version: Still happens on 1.33.0 and whatever version TW uses right now
Operating system: Windows 11 Pro

**Comment by mxmou** [comment] 2023-06-18 08:48
Duplicate of #3906

**Closed by mxmou** 2023-06-18 08:48 UTC
Labels: type: bug, scope: addon

**Comment by WorldLanguages** [comment] 2023-09-02 23:03
This should be fixed by #6613
