### ISSUE TITLE
Messages Lagging

### ISSUE THREAD

**Issue by Mbrick2** [ScratchAddons/ScratchAddons#3971] opened 2021-12-21 02:04 UTC
### Description

It says 3 (and displays 3) but I have 5

### Repoduction steps

1. Get a few messages quickly
2. Check messages
3. wait a few minutes and it will show

### Expected behaviour

Displayes it correctly

### Actual behaviour

it laaaaaaaaaaaaaaaaaaaaaags

### Environment

Firefox

**Comment by RedGuy12** [comment] 2021-12-21 02:36
Does https://api.scratch.mit.edu/users/your-username-here/messages/count display the proper number? If so, not our problem.


________________________________
From: Mbrick2 ***@***.***>
Sent: Monday, December 20, 2021 8:04:47 PM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] Messages Lagging (Issue #3971)


Description

It says 3 (and displays 3) but I have 5

Repoduction steps

  1.  Get a few messages quickly
  2.  Check messages
  3.  wait a few minutes and it will show

Expected behaviour

Displayes it correctly

Actual behaviour

it laaaaaaaaaaaaaaaaaaaaaags

Environment

Firefox

**Comment by apple502j** [comment] 2021-12-21 04:35
Duplicate of #2872

**Closed by apple502j** 2021-12-21 04:35 UTC
Labels: type: bug, status: needs triage
