### ISSUE TITLE
Hide/Show Mouse

### ISSUE THREAD

**Issue by ProjectConsolia** [ScratchAddons/ScratchAddons#4641] opened 2022-06-05 03:21 UTC
Hi! I would like if you add the ability to hide/show the mouse!

**Comment by Chiroyce1** [comment] 2022-06-05 04:47
Is this an idea for a new block that implements this functionality, or just as an addon?

**Comment by ProjectConsolia** [comment] 2022-06-05 05:11
Hi! Sorry for the late reply but yes it's for a new block.

**Comment by CST1229** [comment] 2022-06-05 05:36
Wouldn't work for people not using the addon.

**Comment by mxmou** [comment] 2022-06-05 05:59
Duplicate of #4122 (specifically "a custom block or variable that project creators can use to manually change cursor behavior")

**Closed** 2022-06-05 05:59 UTC
Labels: type: enhancement, new addon, scope: addon
