### ISSUE TITLE
conflict with Scratch Tools (in general) and Scratch Addons: "insert blocks by name"

### ISSUE THREAD

**Issue by ksdavidc** [ScratchAddons/ScratchAddons#7794] opened 2024-09-10 00:49 UTC
### Description

[ this is being crossposted to Scratch Tools.)
(I know compatibility is not supported, but am reporting since this indicates existence of a possible bug in SA as well)

It appears that something in scratchtools is in conflict with the scratchaddons “insert block by name” plugin, causing the mouse to be “locked”, i.e. moving the mouse moves the content of the block editor pane, but one can't click or otherwise get out. 

### Steps to reproduce

1. With both installed,
2.  if I activate the block suggestion popup (via either middle click or space click), 
3. sometimes (usually the 2nd time) it gets locked into a "keep moving all the code blocks with the mouse, but don't let me get out" loop.  
4. If i turn off scratchtools, it works again. 
5. Turning it on again, it works a little, but reverts.

### Demonstration(s) and additional context

https://discord.com/channels/945340853189247016/1259626053601853460

https://github.com/user-attachments/assets/4be3c3ce-7b95-4a58-88a4-eb1460c986b2

at the start of video, mouse is locked when attempting block insertion, and editor content is moving with mouse. restarting goes back to normal, allowing block suggestion popup, but subsequently locking again.
json:

[my ST.json](https://github.com/user-attachments/files/16937853/my.ST.json)
[my sa.json](https://github.com/user-attachments/files/16937854/my.sa.json)

from another user with same problem: 
[scratchtools-settings (2).json](https://github.com/user-attachments/files/16937830/scratchtools-settings.2.json)
[scratch-addons-settings (2).json](https://github.com/user-attachments/files/16937831/scratch-addons-settings.2.json)

### Environment

version: SA 1.39.1 and ST .3.9
Chrome 128.0.6613.120 (Official Build) (x86_64)
Mac Sonoma

**Comment by ksdavidc** [comment] 2024-09-10 00:49
https://github.com/STForScratch/ScratchTools/issues/964

**Comment by DNin01** [comment] 2024-09-10 17:01
Something similar used to happen (and maybe still happens) in TurboWarp when certain custom extensions are loaded. Attempting to open the popup wouldn't work and you would instead not be able to stop dragging the code area/workspace. Reloading the page without that extension loaded and everything would be normal again.

**Comment by DNin01** [comment] 2024-09-10 17:13
We don't focus on fixing issues that are caused by our code coinciding with a specific software (otherwise there would be hundreds of issues to address), but Scratch Addons is the most popular all-in-one extension for Scratch - maybe you could ask ScratchTools if they could address the issue?

Anyway, it would be helpful if we could see any error or warning messages in your console when this happens.

**Comment by mxmou** [comment] 2024-09-10 18:21
> Something similar used to happen (and maybe still happens) in TurboWarp when certain custom extensions are loaded. Attempting to open the popup wouldn't work and you would instead not be able to stop dragging the code area/workspace. Reloading the page without that extension loaded and everything would be normal again.

Which custom extensions? If it affects multiple extensions the it's probably something that can be fixed on our side.

**Comment by DNin01** [comment] 2024-09-10 18:53
> > Something similar used to happen (and maybe still happens) in TurboWarp when certain custom extensions are loaded. Attempting to open the popup wouldn't work and you would instead not be able to stop dragging the code area/workspace. Reloading the page without that extension loaded and everything would be normal again.
> 
> Which custom extensions? If it affects multiple extensions the it's probably something that can be fixed on our side.

https://extensions.turbowarp.org/NOname-awa/math-and-string.js was one of the extensions that _used to_ cause the error before @Tacodiva's big overhaul (#5391).

Speaking of which, @Tacodiva, maybe you know what's going on?

**Comment by Tacodiva** [comment] 2024-09-10 21:55
> Speaking of which, @Tacodiva, maybe you know what's going on?

I'm not sure. Is there any errors in the console? I haven't confirmed but this could be being caused by something that intercepts `doWorkspaceClick_` throwing an error.

**Comment by ksdavidc** [comment] 2024-09-10 22:42
> We don't focus on fixing issues that are caused by our code coinciding with a specific software (otherwise there would be hundreds of issues to address), but Scratch Addons is the most popular all-in-one extension for Scratch - maybe you could ask ScratchTools if they could address the issue?
> 

was done:
https://github.com/STForScratch/ScratchTools/issues/964

> Anyway, it would be helpful if we could see any error or warning messages in your console when this happens.

[scratch.mit.edu-1726007444045.log](https://github.com/user-attachments/files/16955747/scratch.mit.edu-1726007444045.log)

```
BlockTypeInfo.js:509 Uncaught TypeError: Cannot read properties of undefined (reading 'getAllVariableNamesInScopeByType')
    at BlockTypeInfo._createBlocks (BlockTypeInfo.js:509:48)
    at BlockTypeInfo.getBlocks (BlockTypeInfo.js:387:26)
    at openPopup (userscript.js:114:32)
    at Blockly.Gesture.doWorkspaceClick_ (userscript.js:448:79)
    at Blockly.Gesture.handleUp (projects.bundle.js:2:11379414)
    at HTMLDocument.s (projects.bundle.js:2:11997165)
_createBlocks @ BlockTypeInfo.js:509
getBlocks @ BlockTypeInfo.js:387
openPopup @ userscript.js:114
Blockly.Gesture.doWorkspaceClick_ @ userscript.js:448
Blockly.Gesture.handleUp @ projects.bundle.js:2
s @ projects.bundle.js:2
projects.bundle.js:2 Trying to cancel a gesture recursively.
projects.bundle.js:2 Trying to cancel a gesture recursively.

```

**Comment by Tacodiva** [comment] 2024-09-10 22:46
> Blockly.Gesture.doWorkspaceClick_ @ userscript.js:448

Called it 😎

**Comment by ksdavidc** [comment] 2024-09-11 10:42
> > Blockly.Gesture.doWorkspaceClick_ @ userscript.js:448
> 
> Called it 😎
> 
> I've looked into this and I have an idea (though I'm just looking at code on mobile so I could be totally wrong). I suspect that scratch tools is adding something to the "sprite" drop-down of the `[variable] of [sprite]` block that isn't actually a sprite (maybe something like "create new sprite"). This causes issues because middle click popup has no way to tell which options in the drop-down are possible values for the field and which are not. ScratchAddons also adds some options to drop-downs, but these are hard-coded into the middle click popup addon (see [here](https://github.com/ScratchAddons/ScratchAddons/blob/4ec52ef052c8e6951d5359315e65acd531b04863/addons/middle-click-popup/BlockTypeInfo.js#L186)). I believe this is the fault of ScratchAddons (more specifically, my fault) because this code is particularly unfriendly to anything else adding options to drop-downs. **We need some standard way of telling which drop-down values are being added externally and are not actual values for the field.** I would suggest maybe a prefix on the drop-down values ids like `special_` that would tell the middle click popup to ignore them. Scratch tools could use this prefix too. Ideally, we would rename all the special drop-down values added by scratch add-ons to have this special prefix too so we can remove the hard-coding.
> 
> If I'm right about the cause of this we might need to include some more people in this conversation for opinions.
> 
> We could also apply a quick-fix for this by adding a check to see if the options sprite is actually real (ie not undefined) but this issue of drop-down values not being handled properly will probably crop up again if we don't handle it properly at some point.


Man you're good.

Disabling the ST "Select Self" plugin fixes middle-click, and re-enabling it brings it back (with the error). What does "Select Self" do?  "adds something to the "sprite" drop-down of the `[variable] of [sprite]` block that isn't actually a sprite" ... well it is a sprite, but not a different sprite.

**Comment by WorldLanguages** [comment] 2024-09-12 01:12
> I would suggest maybe a prefix on the drop-down values ids like `special_` that would tell the middle click popup to ignore them.

Sounds like a good idea to me

**Comment by Tacodiva** [comment] 2024-09-13 07:38
![image](https://github.com/user-attachments/assets/58f6200b-1cf0-4754-8b78-d93fdf81e042)

Ok I downloaded ScratchTools and it seems like it is actually adding `_mouse_` and `_random_` to the `of` block. Above I was operating under the assumption the extra options they had added actually did something, but no... these special inputs are used in some other blocks but I have no idea why they're adding them to the `of` block. This is a bug in ScratchTool and should be fixed on their end. If it wasn't for these nonsensical inputs being added, the middle click popup would work.

**Comment by ksdavidc** [comment] 2024-09-13 13:12
I have added your info, and more, to the ST bug report. 
https://github.com/STForScratch/ScratchTools/issues/964#issuecomment-2348925505

> "Select self", , it seems, is adding menu items to certain blocks (that seem unrelated to adding self?!), for example, _mouse_ and _random_ to the of block, even though its code (https://github.com/STForScratch/ScratchTools/blob/main/features/select-self/script.js) appears to be attempting to only add "Stage" to the sensing block.

**Comment by DNin01** [comment] 2024-09-13 19:02
Thanks for the info. This issue is caused by ScratchTools, and that behavior - the root problem - seems to be a bug in ScratchTools, so we will let them fix it. Once it is addressed, the middle click popup should work fine.

**Closed by DNin01** 2024-09-13 19:02 UTC
Labels: type: bug, scope: addon
