### ISSUE TITLE
Add a "remix" button on your own projects.

### ISSUE THREAD

**Issue by CodeGuy92** [ScratchAddons/ScratchAddons#2876] opened 2021-06-28 20:37 UTC
### Is your request related to a problem? Please describe.

No, i just feel like this is a great idea. You can remix your own projects. If your project is really big, and you don't want to go inside your editor to click the "save as copy", this could be perfect,

### Describe the solution you'd like

For what?

### Describe alternatives you've considered

No alternatives.

### Additional context

No additional context.

**Comment by TheColaber** [comment] 2021-06-28 20:38
Duplicate of #1816

**Closed by TheColaber** 2021-06-28 20:38 UTC
Labels: new addon, scope: addon, type: enhancement
