### ISSUE TITLE
Wrap list items instead of disappearing

### ISSUE THREAD

**Issue by iqnite** [ScratchAddons/ScratchAddons#2711] opened 2021-06-08 12:53 UTC
### Is your request related to a problem? Please describe.

It's frustrating when long list items finish with "...".

### Describe the solution you'd like

It would be great if there is a feature that wraps the items into the next line

### Describe alternatives you've considered

Yes, I could do it manually on my projects, but it's problematic when the program has to get items from the list. And it wouldn't work on other people's projects.

### Additional context

I took this from the Better3.0 browser extension.
I have also seen it in the Scratch Addons Code, why did you cancel it?

**Comment by WorldLanguages** [comment] 2021-06-08 15:23
Duplicate of #2264

**Closed by WorldLanguages** 2021-06-08 15:23 UTC
Labels: status: needs triage, type: enhancement
