### ISSUE TITLE
editor-dark-mode: Option to change editor cyan

### ISSUE THREAD

**Issue by Secret-chest** [ScratchAddons/ScratchAddons#5972] opened 2023-04-29 16:03 UTC
### Why this would be helpful

> It's the color appearing when hovering on the add sprite colors.

The cyan feels ugly and toxic IMO. Some way to change it would be appreciated.

### My suggestion

Add a setting to `editor-dark-mode` for the cyan so it's configurable

### Additional context

At the time of posting this, the Issues tab says 600 and the PR tab says 100
![image](https://user-images.githubusercontent.com/74449186/235312114-416a02dd-4ade-49d4-b53b-4cd1ab660c90.png)

**Comment by DNin01** [comment] 2023-04-29 16:23
You mean the color that used to be the remix button color? The one that appears when hovering over options on the add sprite dropdown menus?

It's a little specific, but I see why users would want to change it, especially in customized themes such as TurboWarp Dark (in the real TurboWarp, that color is orange instead of cyan).

> At the time of posting this, the Issues tab says 600 and the PR tab says 100
> 
> ![image](https://user-images.githubusercontent.com/74449186/235312114-416a02dd-4ade-49d4-b53b-4cd1ab660c90.png)

🎉

**Comment by Secret-chest** [comment] 2023-04-29 17:09
It's the one appearing when hovering on the add sprite colours. Maybe it can be called "Secondary Accent Colour"?

**Comment by Secret-chest** [comment] 2023-05-23 08:58
bump

**Comment by mxmou** [comment] 2024-09-21 07:39
Duplicate of #5180

**Closed by mxmou** 2024-09-21 07:39 UTC
Labels: type: enhancement, scope: addon
