### ISSUE TITLE
Only show sprite pane

### ISSUE THREAD

**Issue by iqnite** [ScratchAddons/ScratchAddons#6771] opened 2023-10-14 13:17 UTC
### Why this would be helpful

Sometimes I want to only edit sprites, without the stage taking up space. But the "Hide stage" button also hides the sprite pane and the "Stage" button takes up half of the pane, making it a real pane... erm... *pain* in the neck.

### My suggestion

A button that invokes the Small stage mode, then hides the stage and puts the "Stage" bar horizontally together with the sprites, so there are 3 columns with sprites.
(See mockup below.)

### Possible alternatives

This could also be added to the "Hide stage" addon.

### Additional context

<img width="240" alt="mockup" src="https://github.com/ScratchAddons/ScratchAddons/assets/50552317/6a34e6a3-9dad-40ef-852d-17201430f733">

**Comment by Samq64** [comment] 2023-10-14 13:31
Duplicate of #6696

**Closed by Samq64** 2023-10-14 13:31 UTC
Labels: type: enhancement, scope: addon
