### ISSUE TITLE
Add Styles

### ISSUE THREAD

**Issue by CopperCopleer** [ScratchAddons/ScratchAddons#1838] opened 2021-03-13 04:54 UTC
you can change the editor color

**Comment by Genius398** [comment] 2021-03-13 08:13
> you can change the editor color

Good idea. 



@WorldLanguages

**Comment by mxmou** [comment] 2021-03-13 08:46
Duplicate of #657

**Comment by mxmou** [comment] 2021-03-13 08:47
I'm already working on this, see the second screenshot in #1805 for how it will look like.

**Closed by mxmou** 2021-03-13 08:46 UTC
Labels: new addon, scope: addon, type: enhancement
