### ISSUE TITLE
Unshare button in editor

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#2235] opened 2021-04-20 21:06 UTC
Currently, Scratch requires you to go into My Stuff to unshare a project. This addon would turn the "Shared" label into a functional unshare button.

![image](https://user-images.githubusercontent.com/43426138/115464235-65fa6b80-a1f2-11eb-88e7-13ed670b7e04.png)

> We should make that into an unshare button!

_Originally posted by @GrahamSH-LLK in https://github.com/ScratchAddons/ScratchAddons/issues/2176#issuecomment-821316371_

**Comment by TheColaber** [comment] 2021-04-20 21:07
Duplicate of #2075

**Closed by TheColaber** 2021-04-20 21:07 UTC
