### ISSUE TITLE
Investigate stuck "loading messages..." in scratch-messaging

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#2727] opened 2021-06-10 13:08 UTC
Not sure what triggers it, but I think it once happened to me and I've seen feedback about it
I don't think we made any recent code changes that should trigger something like this either, maybe a browser update changed behavior

**Comment by apple502j** [comment] 2021-06-10 13:13
Can it be Scratch being down?

**Comment by mxmou** [comment] 2021-06-10 13:14
@apple502j It happened for me when nothing was wrong with Scratch. Reloading the extension fixes it, so maybe it's a crash in the messaging addon's persistent script?

**Comment by mxmou** [comment] 2021-06-10 13:19
I'll check if there's a traceback the next time this happens, but I noticed that the code for getting Scratch Team messages doesn't seem to have any error handling. Could that be the cause?

**Comment by apple502j** [comment] 2021-06-10 13:22
If it does error, it's probably Scratch server's problem. Maybe we can check that.

**Comment by mxmou** [comment] 2021-06-10 13:27
To reproduce:
1. Open the messaging popup in a new tab, make sure that you have unread messages
2. Disconnect from the internet.
3. Keep reloading the page until "Loading messages..." appears.
4. Connect to the internet and open the popup again. Messages still don't load unless you reload the extension.

This might not happen 100% consistently but it usually does.

**Comment by TheColaber** [comment] 2021-06-10 16:55
Yeah, this also happens to me when I let my computer sleep overnight and turn it on in the morning... I think the internet being off then on is causing this issue.

**Comment by return-misaPuding** [comment] 2021-06-29 05:48
It happens to me even when I don't turn internet off... Sadly I didn't see
anything in the console

Dne čt 10. 6. 2021 15:27 uživatel Maximouse ***@***.***>
napsal:

**Comment by mxmou** [comment] 2021-08-28 10:35
Can still reproduce on v1.19.1.

**Comment by WorldLanguages** [comment] 2021-08-28 14:44
I think this happens when profile comments go down

**Comment by mxmou** [comment] 2021-08-28 17:54
> I think this happens when profile comments go down

Possibly, but it also still happens when I do [this](https://github.com/ScratchAddons/ScratchAddons/issues/2727#issuecomment-858622555).

**Comment by WorldLanguages** [comment] 2021-09-10 22:33
This should probably be worked on together with #2703, which is on the v1.21.0 milestone
A refactor should also consider future migration to background service workers, that will change how persistent scripts work.

**Comment by apple502j** [comment] 2021-09-11 07:26
@WorldLanguages Without a repro method this is impossible to debug. Can't we mark this as needs-info and put in backlog?

**Comment by return-misaPuding** [comment] 2021-10-04 15:24
Happened to me many times (it doesn't happen to me now tho) and even leaving the extension popup and opening it again many times didn't work

**Comment by apple502j** [comment] 2021-10-06 03:06
Can you open the developer tools for the extension (Extensions -> Inspect Views on Chrome, about:debugging -> Inspect on Firefox) and see if there are any strange logs?

**Comment by WorldLanguages** [comment] 2021-11-05 23:52
I'm keeping #2703 which is similar, on the v1.23.0 milestone

**Comment by apple502j** [comment] 2022-02-03 03:25
Closing; the refactor should've fixed this issue.

**Closed by apple502j** 2022-02-03 03:25 UTC
Labels: type: bug, source: feedback, priority: 3, scope: addon
