### ISSUE TITLE
When the More Links addon is enabled, words ending in "..." get linked

### ISSUE THREAD

**Issue by PhoenixAndStuf** [ScratchAddons/ScratchAddons#1450] opened 2021-01-28 23:28 UTC
**Describe the bug**

Hi, I think that you shouldn't have words ending in "..." linked. Screenshots below.

I've never ever seen this format of website links, so I think it should be normal: and to prevent people from going to unwanted websites.

**Steps to Reproduce**

1: Activate the "More Links" addon.
2: Comment any word followed by "..."
3: See error

**Expected behavior**

It should just be normal text in my opinion.

Again, I have never seen a website with a "..." format.

**Screenshot**

![BUGREPORT](https://user-images.githubusercontent.com/75099144/106211043-d4440a80-617c-11eb-9087-883205b4f47b.PNG)

**Device (please complete the following information):**

- OS: Windows 10
- Browser Microsoft Edge
- SA Version: 1.8.0

**Additional context**

You need to have the "more links" addon enabled. Otherwise it will not work for you.

**Comment by TheColaber** [comment] 2021-01-29 01:23
Duplicate of #1449, #1438, #1415, #1443, #1415
At this point, we might need a PIN :P

**Closed by TheColaber** 2021-01-29 01:23 UTC
Labels: status: needs triage, type: bug
