### ISSUE TITLE
Website dark theme affects stage

### ISSUE THREAD

**Issue by RedGuy12** [ScratchAddons/ScratchAddons#4560] opened 2022-05-12 21:39 UTC
### Description

Website dark mode affects the stage

### Reproduction steps

1. Enable dark-www (disable editor-dark-mode) with either of the Dark presets
2. Go to a project with variable monitors shown (on the project page only, not the editor)
3. See bug

### Expected behavior

The stage is unaffected
### Actual behavior

The stage is affected

### Screenshots

![image](https://user-images.githubusercontent.com/61329810/168172103-874d117d-b547-4712-8cef-a36f131e6860.png)
### Environment

not applicable
### Additional context
Reported by Cubester on Discord

**Comment by CubesterYT** [comment] 2022-05-12 21:47
Very Annoying Bug

**Comment by WorldLanguages** [comment] 2022-05-12 22:25
![image](https://user-images.githubusercontent.com/17484114/168177501-7ef1f8d3-3b56-4aba-85cd-cc46a4952677.png)

**Comment by WorldLanguages** [comment] 2022-05-12 22:28
@mxmou I can reproduce this on stable (v1.25.1) as well as master branch

Is this because of a Scratch update? Or did we really miss this for 2 months?

**Comment by Samq64** [comment] 2022-05-13 00:32
Duplicate of #3963?

**Comment by apple502j** [comment] 2022-05-15 06:01
@WorldLanguages I believe this bug has existed since the beginning. Pretty annoying too since CSS does not provide "revert to previously defined value". I'll PR a hackfix, which is just a copy of color definitions applied normally.

**Comment by apple502j** [comment] 2022-05-15 06:06
This is actually a upstream bug, see gui#5797

**Comment by WorldLanguages** [comment] 2022-05-15 15:30
Apparently, this has been a bug forever and no one noticed it. Probably because most projects don't show monitors, and most of our users use none or both of the dark mode addons.

**Comment by mxmou** [comment] 2022-05-15 16:38
> Apparently, this has been a bug forever and no one noticed it. Probably because most projects don't show monitors, and most of our users use none or both of the dark mode addons.

#981 fixed it, but the fix was apparently removed in #3710. I don't remember why I removed those lines - I probably just forgot to re-add them when moving things around in the CSS file.

**Closed** 2022-05-17 22:35 UTC
Labels: type: bug, source: feedback, priority: 3, scope: addon
