### ISSUE TITLE
An addon that provides a quick and easy way to download a “screenshot” of the stage

### ISSUE THREAD

**Issue by penguinmoose** [ScratchAddons/ScratchAddons#5108] opened 2022-09-16 01:34 UTC
### Why this would be helpful/solve a problem

Right now, I have to screenshot the stage area to get an image of the stage. Since the stage is rounded, this is not easy.

### What this addon does

This addon will add a button to the flag and stop button area (or elsewhere) that instantly downloads a “screenshot” of the stage. It will make downloading an image of the stage quick and easy.

### Possible alternatives

- The button can be placed elsewhere.
- It can be put under “file” in the header (not reccomended, it adds an extra step.
- This feature can be merged with the stage recording addon.

**Comment by DNin01** [comment] 2022-09-16 02:55
I can right click the stage and download a picture of it already.

**Comment by Norbiros** [comment] 2022-09-16 04:36
On firefox it sometimes downloads black screen...

**Comment by mxmou** [comment] 2022-09-16 07:24
Duplicate of #3715

**Closed by mxmou** 2022-09-16 07:24 UTC
Labels: type: enhancement, new addon, scope: addon
