### ISSUE TITLE
Record project video does not record variables and lists

### ISSUE THREAD

**Issue by iqnite** [ScratchAddons/ScratchAddons#3512] opened 2021-09-17 15:40 UTC
### Description

The project video addon does not record lists and variables

### Environment

- Browser: Vivaldi 4.2.2406.44
- Scratch Addons version: 1.20.0
- Operating system: Windows 11

**Comment by mxmou** [comment] 2021-09-17 15:51
Duplicate of #2057

**Closed by mxmou** 2021-09-17 15:51 UTC
Labels: type: bug, status: needs triage
